CREATE PROGRAM 27019_public_vars_tst:dba
 CALL echo("*** DM_DBIMPORT PUBLIC VARIABLES ***")
 CALL echo(build("rdm_unit_cnt  = ",rdm_unit_cnt))
 CALL echo(build("rdm_while_cnt = ",rdm_while_cnt))
 CALL echo(build("rdm_for_cnt = ",rdm_for_cnt))
 CALL echo(build("rdm_num_rows = ",rdm_num_rows))
 CALL echo(build("rdm_stat = ",rdm_stat))
 CALL echo(build("rdm_line_data = ",rdm_line_data))
 CALL echo(build("rdm_line_len = ",rdm_line_len))
 CALL echo(build("rdm_check_pos = ",rdm_check_pos))
 CALL echo(build("rdm_field_total = ",rdm_field_total))
 CALL echo(build("rdm_rptcnt = ",rdm_rptcnt))
 CALL echo(build("rdm_found_field = ",rdm_found_field))
 CALL echo(build("rdm_field_number = ",rdm_field_number))
 CALL echo(build("rdm_csv_name = ",rdm_csv_name))
 CALL echo(build("rdm_status = ",rdm_status))
 CALL echo(build("rdm_err_msg = ",rdm_err_msg))
 CALL echo(build("rdm_col_size = ",rdm_col_size))
 CALL echo(build("dm_dbi_file_name = ",dm_dbi_file_name))
 CALL echo(build("dm_dbi_load_script = ",dm_dbi_load_script))
 CALL echo(build("dm_dbi_blocks = ",dm_dbi_blocks))
 CALL echo(build("dm_dbi_file_loc = ",dm_dbi_file_loc))
 CALL echo(build("dm_dbi_stat = ",dm_dbi_stat))
 CALL echo(build("dm_dbi_load_exist = ",dm_dbi_load_exist))
 CALL echo(build("dm_dbi_csv_rows = ",dm_dbi_csv_rows))
 CALL echo(build("dm_dbi_logical = ",dm_dbi_logical))
 CALL echo(build("dm_dbi_start_row = ",dm_dbi_start_row))
 CALL echo(build("dm_dbi_end_row = ",dm_dbi_end_row))
END GO
