CREATE PROGRAM bhs_ma_clin_sum_events:dba
 RECORD events(
   1 cnt = i4
   1 qual[*]
     2 event_cd = f8
     2 event_seq = i4
     2 header1_nbr = i2
     2 header1_txt = c60
     2 header2_nbr = i2
     2 header2_txt = c60
 )
 SELECT
  FROM dummyt
  HEAD REPORT
   stat = alterlist(events->qual,10), cnt = 1, header1_txt = fillstring(60," "),
   header2_txt = fillstring(60," "),
   MACRO (increment)
    events->qual[cnt].header1_nbr = header1_nbr, events->qual[cnt].header1_txt = header1_txt, events
    ->qual[cnt].header2_nbr = header2_nbr,
    events->qual[cnt].header2_txt = header2_txt, cnt = (cnt+ 1)
    IF (mod(cnt,10)=1)
     stat = alterlist(events->qual,(cnt+ 10))
    ENDIF
   ENDMACRO
   , header1_nbr = 1,
   header1_txt = "Documentation", header2_nbr = 1, header2_txt = "Presenting Information/Assessments",
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TEMPERATURE"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TEMPERATUREROUTE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PULSERATE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SYSTOLICBLOODPRESSURE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DIASTOLICBLOODPRESSURE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RESPIRATORYRATE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"OXYGENSATURATION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LITERSPERMINUTE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MODEOFDELIVERYOXYGEN"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ANESTHESIAREACTION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BLOODTRANSFUSIONREACTION"),
   increment, header2_nbr = (header2_nbr+ 1), header2_txt = "OB Data",
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"REASONFORADMISSION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CONTRACTIONSBEGANON"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MEMBRANES"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FLUIDDESCRIPTION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALSTATION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EFFACEMENT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CERVICALDILATATION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALPRESENTATION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FUNDALHEIGHT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALWEIGHTBABYA"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALWEIGHTBABYB"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALWEIGHTBABYC"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALWEIGHTBABYD"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALWEIGHTBABYE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALWEIGHTBABYF"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALWEIGHTBABYG"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALWEIGHTBABYH"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALHEARTRATEBABYA"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALHEARTRATEBABYB"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALHEARTRATEBABYC"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALHEARTRATEBABYD"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALHEARTRATEBABYE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALHEARTRATEBABYF"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALHEARTRATEBABYG"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FETALHEARTRATEBABYH"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HERPES"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GROUPBSTREP"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"OTHERSEXUALLYTRANSMITTEDDISEASE"),
   increment, header2_nbr = (header2_nbr+ 1),
   header2_txt = "Newborn Data", events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "BIRTHLENGTH"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CHESTCIRCUMFERENCE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RESUSCITATIONATBIRTH"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"VENTILATORSUPPORT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ETTSIZE"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TUBEPOSITION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MUCOUSCOLOR"), increment,
   header2_nbr = (header2_nbr+ 1), header2_txt = "Neonate Risk", events->qual[cnt].event_cd =
   uar_get_code_by("DISPLAYKEY",72,"RISKFACTORSINUTEROMATERNAL"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "RISKFACTORSINUTERONEONATE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BIRTHCOMPLICATIONS"), increment,
   header2_nbr = (header2_nbr+ 1),
   header2_txt = "IV Data", events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "CATHETERTYPE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DATEOFINSERTION"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DATEDRESSINGCHANGE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CENTRALLINECATHETERTYPE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"IVSITE"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"IVGAUGE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NUMBEROFLUMENS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PICCLINE"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PICCGAUGE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LENGTH"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SITE"), increment, header2_nbr = (
   header2_nbr+ 1),
   header2_txt = "HEENT - Assessment", events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "HEENT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HEADDESCRIPTIONNEWBORN"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SYMMETRYOFFACE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FACIALMOVEMENT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EYESDESCRIPTIONNEWBORN"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EYECONDITION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PUPILEYECOLOR"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SCLERACOLOR"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NASALCONDITION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MOUTHCONDITIONNEWBORN"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EARCONDITIONNEWBORN"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NECKCONDITIONNEWBORN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "EVIDENCECONGENITALANOMALIES"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NORMOCEPHALIC"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FONTANELS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EYEDRAINAGELEFT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EYEDRAINAGERIGHT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EARDRAINAGERIGHT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EARDRAINAGELEFT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NARESPATENT"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CLEFTLIPPALATE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EYESNORMALAPPEARANCE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EARSNORMALAPPEARANCE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TONGUENORMALAPPEARANCE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DENTITIONAGEAPPROPRIATE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EYELOCATION"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EYESYMPTOMS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EARLOCATION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EARSYMPTOMS"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NOSELOCATION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NASALSYMPTOMS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EPISTAXISLOCATION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BLEEDINGAMOUNT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EPISTAXISRELATEDHISTORY"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MOUTHANDTHROATSYMPTOMS"), increment,
   header2_nbr = (header2_nbr+ 1),
   header2_txt = "Neurological - Assessment", events->qual[cnt].event_cd = uar_get_code_by(
    "DISPLAYKEY",72,"NEURO"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NEUROLOGICALSYMPTOMS"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ORIENTATEDTOPERSONPLACETIME"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LEVELOFCONSCIOUSNESS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HALLUCINATIONS"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SENSORYPERCEPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FONTANELS"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ANTERIORFONTANELDESCRIPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "POSTERIORFONTANELDESCRIPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CRYDESCRIPTION"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MOROREFLEX"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"REFLEXESNEWBORN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TONENEWBORN"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MOVEMENTNEWBORN"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HEADLAG"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SEIZUREACTIVITY"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SLEEPALERTSTATUSNEWBORN"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BEHAVIORNEWBORN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SUCKNORMAL"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HEADTRAUMAHISTORY"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SEIZUREHISTORY"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PRESEIZUREAURA"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HEADACHE"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TREMORS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EXTREMITYMOVEMENT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GAIT"), increment, events->qual[cnt]
   .event_cd = uar_get_code_by("DISPLAYKEY",72,"TONELUE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TONELLE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TONERUE"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TONERLE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"STRENGTHLUE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"STRENGTHLLE"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"STRENGTHRLE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"STRENGTHRUE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SENSATIONLUE"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SENSATIONLLE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SENSATIONRUE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SENSATIONRLE"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PERRLA"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PUPILSIZELEFT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PUPILSIZERIGHT"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PUPILLEFT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PUPILDESCRIPTIONLEFT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PUPILDESCRIPTIONRIGHT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PUPILREACTIONLEFT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PUPILREACTIONRIGHT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FACIALSYMMETRY"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CHARACTERISTICSOFSPEECH"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SWALLOWINGDIFFICULTY"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GLASGOWCOMASCORE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PEDIATRICCOMASCORE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"INFANTGLASGOWCOMASCORE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"APGARSCORE1MIN"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"APGARSCORE5MIN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"APGARSCORE10MIN"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"APGARSCORE20MIN"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NEOABSTINENCETOTALSCORE"),
   increment, header2_nbr = (header2_nbr+ 1), header2_txt = "Cardiovascular - Assessment",
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CARDIOVASCULAR"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CARDIOVASCULARSYMPTOMS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HEARTRHYTHMPERTELEMETRY"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HEARTRHYTHM"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HEARTSOUNDS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MURMURAUSCULTATED"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PACEMAKER"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PACEMAKERTYPE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PACEMAKERMODE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PACEMAKERMARATE"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CAPILLARYREFILL"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NAILBEDCOLORFINGERS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NAILBEDCOLORTOES"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MOTTLINGOFEXTREMITIES"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CENTRALCYANOSIS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CENTRALCYANOSISNEWBORN"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"UMBILICUSDESCRIPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"UMBILICUSVESSELCOUNT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"UMBILICUSDRAINAGE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"UMBILICUSDRAINAGEAMOUNT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "SKINTEMPERATUREUPPEREXTREMITIES"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SKINTEMPERATURELOWEREXTREMITIES"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HOMANSSIGN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RADIALPULSELEFT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RADIALPULSERIGHT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DORSALISPEDISPULSELEFT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DORSALISPEDISPULSERIGHT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CAROTIDPULSELEFT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CAROTIDPULSERIGHT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BRACHIALPULSELEFT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BRACHIALPULSERIGHT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FEMORALPULSELEFT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FEMORALPULSERIGHT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"POPLITEALPULSELEFT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"POPLITEALPULSERIGHT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"POSTTIBIALPULSELEFT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"POSTTIBIALPULSERIGHT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CLUBBINGPRESENT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EDEMA"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ANKLELEFT"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ANKLERIGHT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ARMLEFT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ARMRIGHT"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HANDLEFT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HANDRIGHT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PEDALLEFT"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PEDALRIGHT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PERIORBITALLEFT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PERIORBITALRIGHT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PRETIBIALLEFT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PRETIBIALRIGHT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SACRAL"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FEMSTOPSITE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"AVFISTULA"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"AVFISTULABRUIT"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"AVFISTULATHRILL"),
   increment, header2_nbr = (header2_nbr+ 1), header2_txt = "Respiratory - Assessment",
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RESPIRATORY"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MODEOFOXYGENDELIVERY"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LITERSPERMINUTERESP"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ADMINISTEREDVIA"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FIO2"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"OXYGENSATURATIONRESP"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RIGHTUPPERLOBEBREATHSOUNDS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "RIGHTMIDDLELOBEBREATHSOUNDS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "RIGHTLOWERLOBEBREATHSOUNDS"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LEFTUPPERLOBEBREATHSOUNDS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "LEFTLOWERLOBEBREATHSOUNDS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ANTERIOR"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"POSTERIOR"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"UPPERAIRWAY"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RESPIRATORYDISTRESS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RESPIRATORYSYMPTOMS"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RESPIRATORYPATTERN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RESPIRATORYEFFORT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ACCESSORYMUSCLESUSE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CHESTEXPANSION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"COUGH"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PATIENTONVENTILATOR"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TRACHEOSTOMYTRACHEALDEVICEPRESENT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TRACHBRANDSIZES"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CUFFINFLATED"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CHESTTUBESSPRESENT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CREPITUSPRESENT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CHESTTUBELOCATION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CHESTTUBECONNECTIVITY"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CHESTTUBECMH20SUCTION"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CHESTTUBEAIRLEAKPRESENT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CHESTTUBEDRAINAGEDESCRIPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "CHESTTUBEDRESSINGCONDITION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RESPIRATIONS"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RETRACTIONLOCATION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RETRACTIONSEVERITY"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RESPIRATORYPATTERNNEWBORN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CHESTDESCRIPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "ADDITIONALRESPSUPPORTNEEDED"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CHESTWIGGLEPRESENTANDSYMMETRICAL"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LUNGSOUNDSLEFT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LUNGSOUNDSRIGHT"),
   increment,
   header2_nbr = (header2_nbr+ 1), header2_txt = "Gastrointestinal - Assessment", events->qual[cnt].
   event_cd = uar_get_code_by("DISPLAYKEY",72,"GI"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GASTROINTESTINALSYMPTOMS"
    ), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ABDOMEN"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LASTBOWELMOVEMENT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BOWELSOUNDSLLQ"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BOWELSOUNDSLUQ"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BOWELSOUNDSRLQ"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BOWELSOUNDSRUQ"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"STOOLCOLORANDDESCRIPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LLQTENDERNESS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LUQTENDERNESS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RLQTENDERNESS"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RUQTENDERNESS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EMESISDESCRIPTION"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GASTRICTUBETYPE"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TUBESITE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "GASTRICDRAINAGEDESCRIPTION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GASTRICTUBEMETHODOFDRAINAGE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PLACEMENTCONFIRMATION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"OSTOMYGI"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"STOMADESCRIPTIONGI"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PERISTOMALSITECOLOSTOMY"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"STOMASIZE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PRODUCTSUSEDFORSTOMALCARE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ABDOMENDESCRIPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BOWELSOUNDSALLQUADRANTS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MASSPALPATED"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PAINTENDERNESSONPALPATION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"JAUNDICE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TEFGASTROSCHISISOMPHALOCELE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"STOOLING"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"STOOLCOLOR"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"STOOLDESCRIPTION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ANUSDESCRIPTIONNEWBORN"),
   increment, header2_nbr = (header2_nbr+ 1), header2_txt = "Genitourinary - Assessment",
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GU"), increment, events->qual[cnt].
   event_cd = uar_get_code_by("DISPLAYKEY",72,"GENITOURINARYSYMPTOMS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "GENITOURINARYSYMPTOMSPEDI"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"VOIDING"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BLADDERDISTENTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LASTMENSTRUALPERIOD"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LMPESTIMATED"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MENSTRUALPROBLEMS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "MENSTRUALPROBLEMSEXPLAINED"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GENITALANATOMY"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GENITALDESCRIPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GENITALDISCHARGEDRAINAGE"
    ), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GENITALDRAINAGEDISCHARGEAPPEARANCE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GENITALDRAINAGEAMOUNT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"UROSTOMYPRESENT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"UROSTOMYSTOMASIZE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"UROSTOMYSTOMADESCRIPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"UROSTOMYFUNCTIONING"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PERISTOMALSITEUROSTOMY"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PRODUCTSUSEDFORUROSTOMYSTOMALCARE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"URINEDESCRIPTION"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"URINECOLOR"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"URINEODOR"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"POSTVOIDRESIDUAL"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BLADDERSCANAMOUNT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"URINARYCATHETERTYPE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "URINARYCATHETERINTERVENTION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DATEOFINSERTION"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"URINARYCATHETERSIZE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "GENITALIADESCRIPTIONNEWBORN"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SCROTUMDESCRIPTIONNEWBORN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PENISDESCRIPTIONNEWBORN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TESTESDESCRIPTIONNEWBORN"
    ), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FEMALEGENITALIADESCRIPTIONNEWBORN"),
   increment, header2_nbr = (header2_nbr+ 1),
   header2_txt = "Musculoskeletal - Assessment", events->qual[cnt].event_cd = uar_get_code_by(
    "DISPLAYKEY",72,"MUSCULOSKELETAL"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MUSCULOSKELETALSYMPTOMS"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MUSCULOSKELETALABNORMALITY"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "MUSCULOSKELETALABNORMALITYLOCATION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ACTIVITY"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MOBILITY"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DEVICESFORAMBULATION"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"AMBULATORYDEVICES"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SPECIALORTHOPEDICDEVICES"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"JOINTLOCATION"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"JOINTASSESSMENT"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RANGEOFMOTIONDESCRIPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CLAVICLELEFT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CLAVICLERIGHT"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ARMSCONDITION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PALMERCREASES"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HANDSFINGERSDESCRIPTION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BACKSPINEDESCRIPTIONNEWBORN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "INGUINALBUTTOCKCREASESYMMETRY"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HIPSDESCRIPTIONNEWBORN"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LEGSDESCRIPTIONNEWBORN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FEETDESCRIPTIONNEWBORN"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TOESDESCRIPTIONNEWBORN"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MOVINGALLEXTREMITIES"),
   increment, header2_nbr = (header2_nbr+ 1), header2_txt = "Functional Screening - Assessment",
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SENSORYDEFICITS"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MOBILITYASSISTANCE"),
   increment, header2_nbr = (header2_nbr+ 1), header2_txt = "Developmental - Assessment",
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DEVELOPMENTAL"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FINEMOTORMILESTONES"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GROSSMOTORMILESTONES"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"COMMUNICATIONMILESTONES"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SOCIALMILESTONES"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FINEMOTORCONCERNS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"GROSSMOTORCONCERNS"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SOCIALCOMMUNICATIONCONCERNS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "PLANSFORCONTINUINGSCHOOLWORK"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BALLARDSCORE"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ESTIMATEDGESTATIONALAGEBYEXAM"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"AGEATEXAM"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CLASSIFICATIONOFNEWBORNS"),
   increment, header2_nbr = (header2_nbr+ 1),
   header2_txt = "Activity/Mobility - Assessment", events->qual[cnt].event_cd = uar_get_code_by(
    "DISPLAYKEY",72,"ACTIVITYMOBILITY"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ABLETOCOMMUNICATENEEDS"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"VISIONNORMAL"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HEARINGNORMAL"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LEARNINGDISABILITIES"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ASSISTIVEDEVICES"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BEHAVIORALPROBLEMS"),
   increment,
   header2_nbr = (header2_nbr+ 1), header2_txt = "Integumentary - Assessment", events->qual[cnt].
   event_cd = uar_get_code_by("DISPLAYKEY",72,"SKIN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SKININTEGRITY"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SKINCOLOR"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SKINTURGOR"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SKINTEMPERATURE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SKINDESCRIPTION"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SKINAPPEARANCENEWBORN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RASHTYPE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FRICTIONANDSHEAR"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MOISTURE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SKINMOISTUREBRADEN"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MUCOUSMEMBRANECOLOR"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MUCOUSMEMBRANEDESCRIPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DRYNESSNEOSKINSCORE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ERYTHEMANEOSKINSCORE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BREAKDOWNEXCORIATIONNEOSKINSCORE"),
   increment, header2_nbr = (header2_nbr+ 1), header2_txt = "Breast Assessment - Assessment",
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BREASTASYMMETRY"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SWELLING"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ERYTHEMA"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PEAUDORANGE"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SKINRETRACTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ULCERATION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SIGNSOFMASTITIS"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TENDERNESS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"INCREASEDHEAT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PRESENCEOFMASS"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"AXILLARYLYMPHADENOPATHY"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "CLAVICULARLYMPHADENOPATHY"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ENGORGED"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FILLING"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CRACKED"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"REDDENED"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SORE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ERECT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FLAT"), increment, events->qual[cnt]
   .event_cd = uar_get_code_by("DISPLAYKEY",72,"INVERTED"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MILKY"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SEROUS"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"OPALESCENT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SANGUINOUS"), increment,
   header2_nbr = (header2_nbr+ 1), header2_txt = "Braden Wound", events->qual[cnt].event_cd =
   uar_get_code_by("DISPLAYKEY",72,"BRADENSCORE"),
   increment, header2_nbr = (header2_nbr+ 1), header2_txt = "Nutritional - Assessment",
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HOMEDIET"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DIETPEDI"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "DIETCOUNSELORVISITREQUESTED"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FEEDINGABILITYADULT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EATINGDIFFICULTIES"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "COMMENTONDIFFICULTYTAKINGMEDS"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PARENTALCONCERNSABOUTCHILDSDIET"),
   increment, header2_nbr = (header2_nbr+ 1),
   header2_txt = "Psychosocial - Assessment", events->qual[cnt].event_cd = uar_get_code_by(
    "DISPLAYKEY",72,"PSYCHOSOCIALNEW"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PRIMARYCAREGIVER"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DESCRIBESPIRITUALNEEDS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DESCRIBECULTURALNEEDS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CULTURALSPIRITUALPRACTICES"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "SPIRITUALADVISORMINISTERNAME"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "SPIRITUALADVISORMINISTERPHONENUMBER"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"AFFECTBEHAVIOR"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CHILDRECEIVINGCOUNSELING"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"COPINGMEASURES"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HXOFSEXUALLYTRANSMITTEDDISEASE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ALCOHOLFREQUENCY"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CIWASCALEINITIATED"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CIGARETTEUSEPACKSDAY"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RECREATIONALDRUGUSE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DRUGTYPE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LASTUSE"), increment, header2_nbr =
   (header2_nbr+ 1),
   header2_txt = "Pain", events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PIPPSCORE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FLACCSCORE"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FACESSCALESCORE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"110PAINSCALESCORE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PRENONVERBALSCALESCORE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BEHAVIORALINDICATORS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PAININTERVENTIONS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PAINRELIEFACCEPTABLE"), increment,
   header1_nbr = (header1_nbr+ 1),
   header1_txt = "Discharge Documentation", header2_nbr = (header2_nbr+ 1), header2_txt =
   "Discharge Needs Evaluation",
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LIVINGSITUATION"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HOMEASSISTANCE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CURRENTHOMESERVICES"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CURRENTHOMETREATMENTS"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"REQUIRESEXTENSIVESERVICESREFERRALS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NEEDSSERVICESONDISCHARGE"
    ), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EQUIPMENTNEEDS"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SERVICESNEEDED"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HOMENEEDS"), increment,
   header2_nbr = (header2_nbr+ 1), header2_txt = "Cardiac Rehabilitation - Discharge", events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PATIENTATTENDINGPHASEII"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PHASEIISITEOFCARE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CARDIACORIENTATIONAPPOINTMENT"),
   increment, header2_nbr = (header2_nbr+ 1),
   header2_txt = "Nutrition Services - Discharge", events->qual[cnt].event_cd = uar_get_code_by(
    "DISPLAYKEY",72,"NUTRITIONDISCHARGESTATUS"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DIETDISCHARGE"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ADADIET"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FATCONTROLLEDDIET"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LIQUIDDIET"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CALORIESDISCHARGE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LOWCHOLESTEROL"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"POTASSIUMCONTROLLEDDIET"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PROTEINCONTROLLEDDIET"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SODIUMCONTROLLEDDIET"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DISCHARGEINFANTFORMULA"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FLUIDRESTRICTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ORALSUPPLEMENTS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CARDIACDIET"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RENALDIET"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HEPATICDIET"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PARENTERALNUTRITION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ENTERALTUBEFEEDINGS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ADDITIVES"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RATEOFINFUSION"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TIMESCHEDULE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "MEDICALNUTRITIONTHERAPYSERVICES"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PEDIATRICNUTRITION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DIABETESNUTRITION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "CARDIACPULMONARYREHABNUTRITION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"WESSONWOMENSCLINIC"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EATINGDISORDERSPROGRAMS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ONCOLOGYNUTRITION"),
   increment,
   header2_nbr = (header2_nbr+ 1), header2_txt = "Pulmonary Rehabilitation - Discharge", events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PATIENTGOINGHOMEONOXYGEN"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PORTABLEUNITREQUIRED"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"OXYGENSATRMAIR"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"OXYGENDEVICEUSEDATHOME"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"LITERFLOW"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TYPEOFHUMIDIFICATION"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TYPEPULMHOMECAREEQUIP"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"OXYGENUSEDURATION"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PREDICTEDPEAKFLOWPULMREHAB"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "PERSONALBESTPEAKFLOWPULMREHAB"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PEAKFLOWPULMREHAB"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MASKSIZE"), increment, events->qual[
   cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CPAPPRESSURE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BIPAPINSPIRATORYPRESSURE"
    ), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BIPAPEXPIRATORYPRESSURE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"CPAPBIPAPDURATION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ACEPELLA"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ABIVESTSYSTEM"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FLUTTERVALVE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SUCTIONMACHINECATHETERS"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"AIRWAYCARE"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"HOMECAREINSTRUCTIONS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "DISCHARGEMEDICALEQUIPMENTCOMPANIES"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PULMREHABINTERAGENCYDISCHASSESS"),
   increment, header2_nbr = (header2_nbr+ 1),
   header2_txt = "Rehab Evaluation - Discharge", events->qual[cnt].event_cd = uar_get_code_by(
    "DISPLAYKEY",72,"BEDMOBILITYREHAB"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TRANSFERSREHAB"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"AMBULATIONREHAB"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "AUDITORYCOMPREHENSIONREHAB"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"VERBALEXPRESSIONREHAB"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ORIENTATIONCOGNITIONREHAB"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SAFETYJUDGEMENTREHAB"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EATINGREHAB"), increment, events->
   qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DRESSINGREHAB"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"BATHGROOMINGREHAB"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"TOILETINGREHAB"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PRECAUTIONSDISCHARGE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RISKOFASPIRATION"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FUNCTIONALSWALLOWING"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SPECIALSWALLOWINGINSTRUCTIONS"),
   increment, header2_nbr = (header2_nbr+ 1), header2_txt = "Pediatric Evaluation - Discharge",
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FINEMOTORDEVELOPMENT"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PERCEPTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SENSORYMOTORDEVELOPMENT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ADLS"), increment, events->qual[cnt]
   .event_cd = uar_get_code_by("DISPLAYKEY",72,"MUSCLETONE"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"NEURODEVELOPMENT"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"MUSCLESTRENGTH"), increment, events
   ->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RANGEOFMOTION"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"RECEPTIVELANGUAGE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EXPRESSIVELANGUAGE"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PHONOLOGICALDEVELOPMENT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PRAGMATICLANGUAGE"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"COGNITIONSOCIALEMOTIONAL"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"FEEDINGSWALLOWING"),
   increment, header2_nbr = (header2_nbr+ 1), header2_txt =
   "Discharge Instructions for Patient/Family/Interagency",
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SERVICECATEGORIES"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"EQUIPMENT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"SERVICEFREQUENCY"),
   increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"DISCHARGERECOMMENDATIONS"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "DISCHARGETREATMENTFREQUENCYST"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "PATIENTDISCHARGEINSTRUCTIONS"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"PATIENTFAMILYINSTRUCTIONSREHAB"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "INTERAGENCYDISCHARGEASSESSMENTREHAB"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,
    "ADDITIONALAGENCYREFERRALINFO"), increment,
   events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"ADDITIONALINSTRUCTIONSTOPATIENT"),
   increment, events->qual[cnt].event_cd = uar_get_code_by("DISPLAYKEY",72,"COMMENTSOTHERPLANOFCARE"),
   increment, stat = alterlist(events->qual,cnt), events->cnt = cnt
  WITH nocounter
 ;end select
 SELECT INTO TABLE bhs_events
  event_seq_key = build(events->qual[d.seq].event_cd,d.seq), event_cd = events->qual[d.seq].event_cd,
  event_seq = d.seq,
  header1_nbr = events->qual[d.seq].header1_nbr, header1_txt = events->qual[d.seq].header1_txt,
  header2_nbr = events->qual[d.seq].header2_nbr,
  header2_txt = events->qual[d.seq].header2_txt
  FROM (dummyt d  WITH seq = events->cnt)
  ORDER BY event_seq_key, event_cd
  WITH organization = indexed, nocounter
 ;end select
END GO
