CREATE PROGRAM bhs_ed_contact_list
 PROMPT
  "Output to File/Printer/MINE" = "MINE"
  WITH outdev
 EXECUTE reportrtl
 DECLARE _createfonts(dummy) = null WITH protect
 DECLARE _createpens(dummy) = null WITH protect
 DECLARE pagebreak(dummy) = null WITH protect
 DECLARE finalizereport(ssendreport=vc) = null WITH protect
 DECLARE ed_disch_contact_list(ncalc=i2) = f8 WITH protect
 DECLARE ed_disch_contact_listabs(ncalc=i2,offsetx=f8,offsety=f8) = f8 WITH protect
 DECLARE initializereport(dummy) = null WITH protect
 DECLARE _hreport = i4 WITH noconstant(0), protect
 DECLARE _yoffset = f8 WITH noconstant(0.0), protect
 DECLARE _xoffset = f8 WITH noconstant(0.0), protect
 DECLARE rpt_render = i2 WITH constant(0), protect
 DECLARE _crlf = vc WITH constant(concat(char(13),char(10))), protect
 DECLARE rpt_calcheight = i2 WITH constant(1), protect
 DECLARE _yshift = f8 WITH noconstant(0.0), protect
 DECLARE _xshift = f8 WITH noconstant(0.0), protect
 DECLARE _sendto = vc WITH noconstant(""), protect
 DECLARE _rpterr = i2 WITH noconstant(0), protect
 DECLARE _rptstat = i2 WITH noconstant(0), protect
 DECLARE _oldfont = i4 WITH noconstant(0), protect
 DECLARE _oldpen = i4 WITH noconstant(0), protect
 DECLARE _dummyfont = i4 WITH noconstant(0), protect
 DECLARE _dummypen = i4 WITH noconstant(0), protect
 DECLARE _fdrawheight = f8 WITH noconstant(0.0), protect
 DECLARE _rptpage = i4 WITH noconstant(0), protect
 DECLARE _outputtype = i2 WITH noconstant(rpt_postscript), protect
 DECLARE _times80 = i4 WITH noconstant(0), protect
 DECLARE _times9b0 = i4 WITH noconstant(0), protect
 DECLARE _times10b0 = i4 WITH noconstant(0), protect
 DECLARE _times11b0 = i4 WITH noconstant(0), protect
 DECLARE _times110 = i4 WITH noconstant(0), protect
 DECLARE _times100 = i4 WITH noconstant(0), protect
 DECLARE _times90 = i4 WITH noconstant(0), protect
 DECLARE _pen0s0c0 = i4 WITH noconstant(0), protect
 DECLARE _pen14s0c0 = i4 WITH noconstant(0), protect
 SUBROUTINE pagebreak(dummy)
   SET _rptpage = uar_rptendpage(_hreport)
   SET _rptpage = uar_rptstartpage(_hreport)
   SET _yoffset = rptreport->m_margintop
 END ;Subroutine
 SUBROUTINE finalizereport(ssendreport)
   SET _rptpage = uar_rptendpage(_hreport)
   SET _rptstat = uar_rptendreport(_hreport)
   DECLARE sfilename = vc WITH noconstant(trim(ssendreport)), private
   DECLARE bprint = i2 WITH noconstant(0), private
   IF (textlen(sfilename) > 0)
    SET bprint = checkqueue(sfilename)
    IF (bprint)
     EXECUTE cpm_create_file_name "RPT", "PS"
     SET sfilename = cpm_cfn_info->file_name_path
    ENDIF
   ENDIF
   SET _rptstat = uar_rptprinttofile(_hreport,nullterm(sfilename))
   IF (bprint)
    SET spool value(sfilename) value(ssendreport) WITH deleted
   ENDIF
   DECLARE _errorfound = i2 WITH noconstant(0), protect
   DECLARE _errcnt = i2 WITH noconstant(0), protect
   SET _errorfound = uar_rptfirsterror(_hreport,rpterror)
   WHILE (_errorfound=rpt_errorfound
    AND _errcnt < 512)
     SET _errcnt = (_errcnt+ 1)
     SET stat = alterlist(rpterrors->errors,_errcnt)
     SET rpterrors->errors[_errcnt].m_severity = rpterror->m_severity
     SET rpterrors->errors[_errcnt].m_text = rpterror->m_text
     SET rpterrors->errors[_errcnt].m_source = rpterror->m_source
     SET _errorfound = uar_rptnexterror(_hreport,rpterror)
   ENDWHILE
   SET _rptstat = uar_rptdestroyreport(_hreport)
 END ;Subroutine
 SUBROUTINE ed_disch_contact_list(ncalc)
   DECLARE a1 = f8 WITH noconstant(0.0), private
   SET a1 = ed_disch_contact_listabs(ncalc,_xoffset,_yoffset)
   RETURN(a1)
 END ;Subroutine
 SUBROUTINE ed_disch_contact_listabs(ncalc,offsetx,offsety)
   DECLARE sectionheight = f8 WITH noconstant(11.000000), private
   IF (ncalc=rpt_render)
    SET _oldpen = uar_rptsetpen(_hreport,_pen14s0c0)
    SET _rptstat = uar_rptrect(_hreport,(offsetx+ 0.500),(offsety+ 0.969),7.500,8.771,
     rpt_nofill,rpt_white)
    SET rptsd->m_flags = 36
    SET rptsd->m_borders = rpt_sdnoborders
    SET rptsd->m_padding = rpt_sdnoborders
    SET rptsd->m_paddingwidth = 0.000
    SET rptsd->m_linespacing = rpt_single
    SET rptsd->m_rotationangle = 0
    SET rptsd->m_y = (offsety+ 1.042)
    SET rptsd->m_x = (offsetx+ 1.323)
    SET rptsd->m_width = 2.490
    SET rptsd->m_height = 0.198
    SET _oldfont = uar_rptsetfont(_hreport,_times110)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2(
      "If you need to find a doctor, you can call",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 1.042)
    SET rptsd->m_x = (offsetx+ 3.844)
    SET rptsd->m_width = 1.406
    SET rptsd->m_height = 0.198
    SET _dummyfont = uar_rptsetfont(_hreport,_times11b0)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Health Link",char(0)))
    SET rptsd->m_y = (offsety+ 1.042)
    SET rptsd->m_x = (offsetx+ 5.271)
    SET rptsd->m_width = 0.844
    SET rptsd->m_height = 0.198
    SET _dummyfont = uar_rptsetfont(_hreport,_times110)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("for referral at",char(0)))
    SET rptsd->m_y = (offsety+ 1.042)
    SET rptsd->m_x = (offsetx+ 6.125)
    SET rptsd->m_width = 1.010
    SET rptsd->m_height = 0.198
    SET _dummyfont = uar_rptsetfont(_hreport,_times11b0)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("(413) 794-2255",char(0)))
    SET _rptstat = uar_rptrect(_hreport,(offsetx+ 0.500),(offsety+ 1.292),7.500,0.417,
     rpt_fill,uar_rptencodecolor(242,242,242))
    SET rptsd->m_flags = 276
    SET rptsd->m_y = (offsety+ 1.292)
    SET rptsd->m_x = (offsetx+ 0.500)
    SET rptsd->m_width = 2.500
    SET rptsd->m_height = 0.427
    SET _dummyfont = uar_rptsetfont(_hreport,_times9b0)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("MEDICAL SERVICES",char(0)))
    SET rptsd->m_y = (offsety+ 1.292)
    SET rptsd->m_x = (offsetx+ 3.000)
    SET rptsd->m_width = 2.500
    SET rptsd->m_height = 0.427
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("PEDIATRIC RESOURCES",char(0)))
    SET _rptstat = uar_rptline(_hreport,(offsetx+ 3.005),(offsety+ 1.292),(offsetx+ 3.005),(offsety+
     3.438))
    SET _rptstat = uar_rptline(_hreport,(offsetx+ 5.505),(offsety+ 1.292),(offsetx+ 5.505),(offsety+
     3.438))
    SET rptsd->m_y = (offsety+ 1.292)
    SET rptsd->m_x = (offsetx+ 5.500)
    SET rptsd->m_width = 2.500
    SET rptsd->m_height = 0.427
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("EMERGENCY HELP",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 1.750)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _dummyfont = uar_rptsetfont(_hreport,_times90)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Brightwood Health Center",
      char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 1.750)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("792-5200",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.042)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate High Street Health Center",
      char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.042)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-2511",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.188)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("High Street Health Center Sexual",
      char(0)))
    SET rptsd->m_y = (offsety+ 2.323)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Assault Follow-up Evaluation",char(0)
      ))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.323)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-9176",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.594)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2(
      "Baystate Mason Square/ Neighborhood Health Center",char(0)))
    SET rptsd->m_y = (offsety+ 2.740)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Neighborhood Health Center",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.740)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-3710",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 3.146)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Wesson Womens Clinic",char(
       0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 3.146)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-5307",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 1.750)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Pediatric Associates",char(0
       )))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 1.750)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-0816",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 1.896)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.385
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Pediatric Clinic",char(0)))
    SET rptsd->m_y = (offsety+ 2.042)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.385
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("140 High Street",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.042)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-2515",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.188)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Pediatric Cardiology",char(0
       )))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.188)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-0812",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.323)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Pediatric ID",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.323)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-5379",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.448)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Pediatric Endocrine",char(0)
      ))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.448)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-0813",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.594)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Pediatric Neurology",char(0)
      ))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.594)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-7040",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.740)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Pediatric Pulmonary",char(0)
      ))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.740)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-0815",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.875)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Child Abuse/ DSS",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.875)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("800-792-5200",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 3.146)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Family Advocacy Center",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 3.146)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-9816",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 1.750)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("BMC-Emergency Dept.",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 1.750)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-3233",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 1.896)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("BMC-Social Services",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 1.896)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-3264",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.042)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("ED Follow-Up Nurse",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.042)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-4774",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.323)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Poison Control",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.323)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("800-682-9211",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.594)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.406
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Worthington Street Shelter",char(0)))
    SET rptsd->m_y = (offsety+ 2.740)
    SET rptsd->m_x = (offsetx+ 6.667)
    SET rptsd->m_width = 0.281
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Men",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.740)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("732-3069",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 2.875)
    SET rptsd->m_x = (offsetx+ 6.500)
    SET rptsd->m_width = 0.396
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Women",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 2.875)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("734-9946",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 3.021)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.698
    SET rptsd->m_height = 0.354
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2(
      "YWCA Rape Crisis Counselor and Community Shelters",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 3.146)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("733-7100",char(0)))
    SET _rptstat = uar_rptrect(_hreport,(offsetx+ 0.500),(offsety+ 3.438),7.500,0.417,
     rpt_fill,uar_rptencodecolor(242,242,242))
    SET rptsd->m_flags = 276
    SET rptsd->m_y = (offsety+ 3.438)
    SET rptsd->m_x = (offsetx+ 0.500)
    SET rptsd->m_width = 7.500
    SET rptsd->m_height = 0.427
    SET _dummyfont = uar_rptsetfont(_hreport,_times10b0)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("BAYSTATE AFFILIATED PRACTICES",char(0
       )))
    SET _rptstat = uar_rptline(_hreport,(offsetx+ 3.005),(offsety+ 3.844),(offsetx+ 3.005),(offsety+
     5.157))
    SET _rptstat = uar_rptline(_hreport,(offsetx+ 5.505),(offsety+ 3.865),(offsetx+ 5.505),(offsety+
     5.167))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 3.896)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _dummyfont = uar_rptsetfont(_hreport,_times90)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Cancer Center",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 3.896)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-9338",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.042)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Cardiology Associates",char(
       0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.042)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-7246",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.188)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate GI Associates",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.188)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-7364",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.323)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Neurology Associates",char(0
       )))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.323)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-7033",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.469)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Neurosurgery",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.469)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-4440",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.594)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate OB/Gyn Group",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.594)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-7045",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.740)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Physical Medicine &",char(0)
      ))
    SET rptsd->m_y = (offsety+ 4.875)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Rehabilitation",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.875)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-7491",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 3.896)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Plastic Surgery",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 3.896)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-5363",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.042)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Pulmonary - Adult",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.042)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-7330",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.188)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Baystate Surgical Associates",char(0)
      ))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.188)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-7020",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.469)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Belchertown Medical Assoc.",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.469)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("323-7212",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.594)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Boston Road Medical Center",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.594)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("596-5550",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.740)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Deerfield Medical Associates",char(0)
      ))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.740)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("665-8517",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.875)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Franklin Medical Group",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.875)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("773-4931",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 3.896)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Greenfield Pediatric Assoc.",char(0))
     )
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 3.896)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("772-0942",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.042)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Ludlow Medical Associates",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.042)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("583-5100",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.188)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Meadows Medical Assoc.",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.188)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("525-4555",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.323)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Northern Edge Medical Assoc.",char(0)
      ))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.323)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-8777",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.469)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Pioneer Valley Family Practice",char(
       0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.469)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("584-9990",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.594)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Pioneer Womens Health",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.594)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("773-4040",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.740)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("South Hadley Medical Assoc.",char(0))
     )
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.740)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("533-3926",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 4.875)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("West Side Medical Assoc.",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 4.875)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-9110",char(0)))
    SET _rptstat = uar_rptrect(_hreport,(offsetx+ 0.500),(offsety+ 5.167),7.500,0.417,
     rpt_fill,uar_rptencodecolor(242,242,242))
    SET rptsd->m_flags = 276
    SET rptsd->m_y = (offsety+ 5.167)
    SET rptsd->m_x = (offsetx+ 0.500)
    SET rptsd->m_width = 7.510
    SET rptsd->m_height = 0.271
    SET _dummyfont = uar_rptsetfont(_hreport,_times10b0)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("S P E C I A L T Y    C L I N I C S",
      char(0)))
    SET rptsd->m_flags = 20
    SET rptsd->m_y = (offsety+ 5.375)
    SET rptsd->m_x = (offsetx+ 0.500)
    SET rptsd->m_width = 7.500
    SET rptsd->m_height = 0.198
    SET _dummyfont = uar_rptsetfont(_hreport,_times80)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2(
      "(Referral to most specialty clinics REQUIRES the patient to have a PCP)",char(0)))
    SET _rptstat = uar_rptline(_hreport,(offsetx+ 3.005),(offsety+ 5.594),(offsetx+ 3.005),(offsety+
     6.907))
    SET _rptstat = uar_rptline(_hreport,(offsetx+ 5.505),(offsety+ 5.594),(offsetx+ 5.505),(offsety+
     6.907))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 5.625)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _dummyfont = uar_rptsetfont(_hreport,_times90)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Allergy Clinic - Pediatrics",char(0))
     )
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 5.625)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-2515",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 5.771)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Dermatology Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 5.771)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-2518",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 5.917)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Employee Health Service",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 5.917)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-3254",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.063)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("HIV/AIDS Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.063)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-3292",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.198)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Infectious Disease- Adult",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.198)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-7394",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.344)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Travel Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.344)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-7015",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.469)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Liver Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.469)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-7030",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 5.625)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Neurology Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 5.625)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-2518",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 5.771)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Occupational Health and",char(0)))
    SET rptsd->m_y = (offsety+ 5.917)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Rehabilitation",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 5.917)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("746-4006",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.063)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Pain Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.063)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-4681",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.198)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Rehabilitation Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.198)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-4279",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.344)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Renal Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.344)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-2518",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.469)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Rheumatology Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.469)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-2518",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 5.625)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Surgical Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 5.625)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-2518",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 5.771)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Specialty Clinics:",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 5.917)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("(Information)",char(0)))
    SET rptsd->m_y = (offsety+ 5.917)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-2518",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.063)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("STD Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.063)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-8354",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.198)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("TB Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.198)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-5435",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.344)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Teen Contraception Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.344)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-8101",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.469)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Trauma Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.469)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-7020",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 6.615)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Wound Care Clinic",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 6.615)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-8640",char(0)))
    SET _rptstat = uar_rptrect(_hreport,(offsetx+ 0.500),(offsety+ 6.896),7.500,0.417,
     rpt_fill,uar_rptencodecolor(242,242,242))
    SET rptsd->m_flags = 276
    SET rptsd->m_y = (offsety+ 6.896)
    SET rptsd->m_x = (offsetx+ 0.500)
    SET rptsd->m_width = 2.500
    SET rptsd->m_height = 0.427
    SET _dummyfont = uar_rptsetfont(_hreport,_times9b0)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("OUTPATIENT PSYCHIATRIC CLINICS",char(
       0)))
    SET rptsd->m_y = (offsety+ 6.896)
    SET rptsd->m_x = (offsetx+ 2.990)
    SET rptsd->m_width = 2.500
    SET rptsd->m_height = 0.427
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("BAYSTATE  PSYCHIATRIC",char(0)))
    SET _dummypen = uar_rptsetpen(_hreport,_pen0s0c0)
    SET _rptstat = uar_rptrect(_hreport,(offsetx+ 3.000),(offsety+ 8.469),2.490,0.417,
     rpt_fill,uar_rptencodecolor(242,242,242))
    SET rptsd->m_borders = bor(rpt_sdtopborder,rpt_sdbottomborder)
    SET rptsd->m_y = (offsety+ 8.469)
    SET rptsd->m_x = (offsetx+ 3.000)
    SET rptsd->m_width = 2.500
    SET rptsd->m_height = 0.427
    SET _dummypen = uar_rptsetpen(_hreport,_pen14s0c0)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("CRISIS TEAMS/INTERVENTION/DMH",char(0
       )))
    SET _rptstat = uar_rptline(_hreport,(offsetx+ 3.005),(offsety+ 6.896),(offsetx+ 3.005),(offsety+
     9.740))
    SET _rptstat = uar_rptline(_hreport,(offsetx+ 5.505),(offsety+ 6.896),(offsetx+ 5.505),(offsety+
     9.740))
    SET rptsd->m_borders = rpt_sdnoborders
    SET rptsd->m_y = (offsety+ 6.896)
    SET rptsd->m_x = (offsetx+ 5.490)
    SET rptsd->m_width = 2.500
    SET rptsd->m_height = 0.427
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("OUTPATIENT SUBSTANCE ABUSE",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 7.375)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _dummyfont = uar_rptsetfont(_hreport,_times90)
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Brightside (Riverdale Road)",char(0))
     )
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 7.375)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("788-7366",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 7.500)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Brightside (School St. Clinic)",char(
       0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 7.500)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("846-4300",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 7.792)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Center for Psychological Services",
      char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 7.792)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("739-0882",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 7.938)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Child & Family Services",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 7.938)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("737-1426",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.073)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Child Guidance Center",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 8.073)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("732-7419",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.219)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Community Care Center",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 8.219)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("736-3668",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.500)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Gandara MH- Springfield",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 8.500)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("736-0395",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.625)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Gandara MH- Holyoke",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 8.625)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("540-9881",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.771)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("MSPCC",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 8.771)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("734-4978",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.917)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Pioneer Valley Mental Health",char(0)
      ))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 8.917)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("734-3151",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 9.063)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Riverbend Behavioral Health",char(0))
     )
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 9.063)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("598-7777",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 9.198)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("River Valley- Chicopee",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 9.198)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("594-2141",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 9.344)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("River Valley- Holyoke",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 9.344)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("534-3361",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 9.490)
    SET rptsd->m_x = (offsetx+ 0.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Valley Psychiatric",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 9.490)
    SET rptsd->m_x = (offsetx+ 2.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("827-8959",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 7.375)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Behavioral Health Network",char(0)))
    SET rptsd->m_y = (offsety+ 7.500)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Crisis hotline (PCS)",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 7.500)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("733-6661",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 7.792)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("BMC Child & Adolescent",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 7.792)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-5555",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 7.938)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("BMC Adult Psychiatric",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 7.938)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-5555",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.073)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("BMC Adult Behavioral Health",char(0))
     )
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 8.073)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-5555",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.219)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("BMC Inpatient- APTU",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 8.219)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-4236",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.917)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Behavioral Health Network",char(0)))
    SET rptsd->m_y = (offsety+ 9.063)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Mt. Tom - Holyoke",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 9.063)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("536-5473",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 9.198)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Behavioral Health - Springfield",char
      (0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 9.198)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("733-6661",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 9.490)
    SET rptsd->m_x = (offsetx+ 3.042)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Crisis Program -Westfield",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 9.490)
    SET rptsd->m_x = (offsetx+ 4.646)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("568-6386",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 7.365)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("AdCare- W. Spfld",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 7.365)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("800-252-6465",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 7.490)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Alcoholics Anonymous",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 7.490)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("532-2111",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 7.625)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Al-Anon (support for families)",char(
       0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 7.625)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("782-3406",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 7.917)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Carlson Recovery Center",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 7.917)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-3971",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.198)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Habit Management",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 8.198)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("733-3488",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.344)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Methadone- Holyoke",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 8.344)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("539-2973",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.490)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Methadone- Springfield",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 8.490)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("781-1926",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 8.750)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Providence Hospital",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 8.750)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("800-274-7724",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 9.042)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Sloan Clinic",char(0)))
    SET rptsd->m_y = (offsety+ 9.188)
    SET rptsd->m_x = (offsetx+ 6.865)
    SET rptsd->m_width = 0.271
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("# 1",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 9.188)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-8409",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 9.323)
    SET rptsd->m_x = (offsetx+ 6.865)
    SET rptsd->m_width = 0.271
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("# 2",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 9.323)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("794-5555",char(0)))
    SET rptsd->m_flags = 4
    SET rptsd->m_y = (offsety+ 9.469)
    SET rptsd->m_x = (offsetx+ 5.542)
    SET rptsd->m_width = 1.813
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("Westfield Community Health",char(0)))
    SET rptsd->m_flags = 68
    SET rptsd->m_y = (offsety+ 9.469)
    SET rptsd->m_x = (offsetx+ 7.146)
    SET rptsd->m_width = 0.802
    SET rptsd->m_height = 0.177
    SET _fdrawheight = uar_rptstringdraw(_hreport,rptsd,build2("568-6600",char(0)))
    SET _dummyfont = uar_rptsetfont(_hreport,_oldfont)
    SET _dummypen = uar_rptsetpen(_hreport,_oldpen)
    SET _yoffset = (offsety+ sectionheight)
   ENDIF
   RETURN(sectionheight)
 END ;Subroutine
 SUBROUTINE initializereport(dummy)
   SET rptreport->m_recsize = 100
   SET rptreport->m_reportname = "BHS_ED_CONTACT_LIST"
   SET rptreport->m_pagewidth = 8.50
   SET rptreport->m_pageheight = 11.00
   SET rptreport->m_orientation = rpt_portrait
   SET rptreport->m_marginleft = 0.00
   SET rptreport->m_marginright = 0.00
   SET rptreport->m_margintop = 0.00
   SET rptreport->m_marginbottom = 0.00
   SET rptreport->m_horzprintoffset = _xshift
   SET rptreport->m_vertprintoffset = _yshift
   SET _yoffset = rptreport->m_margintop
   SET _xoffset = rptreport->m_marginleft
   SET _hreport = uar_rptcreatereport(rptreport,_outputtype,rpt_inches)
   SET _rpterr = uar_rptseterrorlevel(_hreport,rpt_error)
   SET _rptstat = uar_rptstartreport(_hreport)
   SET _rptpage = uar_rptstartpage(_hreport)
   CALL _createfonts(0)
   CALL _createpens(0)
 END ;Subroutine
 SUBROUTINE _createfonts(dummy)
   SET rptfont->m_recsize = 50
   SET rptfont->m_fontname = rpt_times
   SET rptfont->m_pointsize = 10
   SET rptfont->m_bold = rpt_off
   SET rptfont->m_italic = rpt_off
   SET rptfont->m_underline = rpt_off
   SET rptfont->m_strikethrough = rpt_off
   SET rptfont->m_rgbcolor = rpt_black
   SET _times100 = uar_rptcreatefont(_hreport,rptfont)
   SET rptfont->m_pointsize = 11
   SET _times110 = uar_rptcreatefont(_hreport,rptfont)
   SET rptfont->m_bold = rpt_on
   SET _times11b0 = uar_rptcreatefont(_hreport,rptfont)
   SET rptfont->m_pointsize = 9
   SET _times9b0 = uar_rptcreatefont(_hreport,rptfont)
   SET rptfont->m_bold = rpt_off
   SET _times90 = uar_rptcreatefont(_hreport,rptfont)
   SET rptfont->m_pointsize = 10
   SET rptfont->m_bold = rpt_on
   SET _times10b0 = uar_rptcreatefont(_hreport,rptfont)
   SET rptfont->m_pointsize = 8
   SET rptfont->m_bold = rpt_off
   SET _times80 = uar_rptcreatefont(_hreport,rptfont)
 END ;Subroutine
 SUBROUTINE _createpens(dummy)
   SET rptpen->m_recsize = 16
   SET rptpen->m_penwidth = 0.014
   SET rptpen->m_penstyle = 0
   SET rptpen->m_rgbcolor = rpt_black
   SET _pen14s0c0 = uar_rptcreatepen(_hreport,rptpen)
   SET rptpen->m_penwidth = 0.000
   SET _pen0s0c0 = uar_rptcreatepen(_hreport,rptpen)
 END ;Subroutine
 SET d0 = initializereport(0)
 SET d0 = ed_disch_contact_list(rpt_render)
 SET d0 = finalizereport( $OUTDEV)
END GO
