CREATE PROGRAM bhs_rpt_cv_outbound:dba
 PROMPT
  "Output to File/Printer/MINE" = "MINE",
  "Code Set" = 0,
  "Contributor Source" = 0
  WITH outdev, mf_code_set, mf_contributor_source_cd
 EXECUTE bhs_sys_stand_subroutine
 DECLARE ms_contrib_disp_key = vc WITH protect, constant(trim(uar_get_displaykey(
     $MF_CONTRIBUTOR_SOURCE_CD),3))
 DECLARE ms_report_title = vc WITH protect, constant(concat("cv_outbound_",trim(cnvtstring(
      $MF_CODE_SET),3),"_",ms_contrib_disp_key))
 DECLARE ms_filename = vc WITH protect, constant(concat(cnvtlower(ms_report_title),"_",trim(format(
     curdate,"DD-MM-YY ;;d"),3),".csv"))
 DECLARE ms_email_list = vc WITH protect, noconstant(" ")
 DECLARE ms_email_body = vc WITH protect, noconstant(" ")
 DECLARE ms_tmp = vc WITH protect, noconstant(" ")
 DECLARE ms_dclcom_str = vc WITH protect, noconstant(" ")
 DECLARE ml_dclcom_len = i4 WITH protect, noconstant(0.0)
 DECLARE mn_dclcom_stat = i2 WITH protect, noconstant(0)
 DECLARE mf_filesize = f8 WITH protect, noconstant(0.0)
 RECORD m_frec(
   1 file_desc = i4
   1 file_name = vc
   1 file_buf = vc
 ) WITH protect
 IF (( $OUTDEV="EMAIL"))
  SELECT INTO "nl:"
   FROM dm_info di
   WHERE trim(di.info_domain,3)=concat("BHS_RPT_CV_OUTBOUND:",trim(cnvtstring( $MF_CODE_SET),3),":",
    ms_contrib_disp_key)
   DETAIL
    IF (size(trim(ms_email_list,3)) > 0)
     ms_email_list = concat(trim(ms_email_list,3),", ",trim(di.info_name,3))
    ELSE
     ms_email_list = trim(di.info_name,3)
    ENDIF
   WITH format, nocounter
  ;end select
  SELECT INTO value(ms_filename)
   FROM code_value cv,
    code_value_outbound cvo
   PLAN (cv
    WHERE (cv.code_set= $MF_CODE_SET)
     AND cv.active_ind=1)
    JOIN (cvo
    WHERE cvo.code_value=outerjoin(cv.code_value)
     AND cvo.contributor_source_cd=outerjoin( $MF_CONTRIBUTOR_SOURCE_CD))
   ORDER BY cvo.alias DESC, cv.display
   HEAD REPORT
    ms_tmp = "code_value,code_set,cdf_meaning,display,description", col 0, ms_tmp
   DETAIL
    IF (trim(cvo.alias,3)="")
     row + 1, ms_tmp = build2('"',trim(cnvtstring(cv.code_value),3),'",','"',trim(cnvtstring(cv
        .code_set),3),
      '",','"',trim(cv.cdf_meaning,3),'",','"',
      trim(cv.display),'",','"',trim(cv.description),'"'), col 0,
     ms_tmp
    ENDIF
   WITH nocounter, separator = "  ", maxcol = 1100,
    maxrow = 1
  ;end select
  SET ms_dclcom_str = concat("du -m ",ms_filename," > temp_cv_outbound_filesize.txt")
  SET ml_dclcom_len = size(trim(ms_dclcom_str,3))
  SET mn_dclcom_stat = 0
  SET stat = dcl(ms_dclcom_str,ml_dclcom_len,mn_dclcom_stat)
  SET m_frec->file_name = "temp_cv_outbound_filesize.txt"
  SET m_frec->file_buf = "r"
  SET stat = cclio("OPEN",m_frec)
  SET m_frec->file_buf = notrim(fillstring(132," "))
  SET stat = cclio("GETS",m_frec)
  SET mf_filesize = cnvtreal(trim(replace(m_frec->file_buf,ms_filename,""),3))
  SET stat = cclio("CLOSE",m_frec)
  SET stat = remove("temp_cv_outbound_filesize.txt")
  IF (mf_filesize > 14.63)
   SET ms_email_body = concat("The file generated by bhs_rpt_cv_outbound for code set ",cnvtstring(
      $MF_CODE_SET)," and contributor source ",uar_get_code_display( $MF_CONTRIBUTOR_SOURCE_CD),
    " was too large to e-mail from the back end. To access the file you will have to retrieve it from ",
    logical("CCLUSERDIR"),"/",ms_filename)
   SET ms_dclcom_str = concat("echo ",ms_email_body," | mailx -s ",ms_report_title," ",
    ms_email_list)
   SET ml_dclcom_len = size(trim(ms_dclcom_str,3))
   SET mn_dclcom_stat = 0
   CALL echo(ms_dclcom_str)
   SET stat = dcl(ms_dclcom_str,ml_dclcom_len,mn_dclcom_stat)
  ELSE
   CALL emailfile(ms_filename,ms_filename,ms_email_list,ms_report_title,1)
  ENDIF
 ELSE
  SELECT INTO  $OUTDEV
   cv.code_value, cv.code_set, cv.cdf_meaning,
   cv.display, cv.description, contributor_source = uar_get_code_display(cvo.contributor_source_cd),
   cvo.contributor_source_cd, cvo.alias_type_meaning, cvo.alias
   FROM code_value cv,
    code_value_outbound cvo
   PLAN (cv
    WHERE (cv.code_set= $MF_CODE_SET)
     AND cv.active_ind=1)
    JOIN (cvo
    WHERE cvo.code_value=outerjoin(cv.code_value)
     AND cvo.contributor_source_cd=outerjoin( $MF_CONTRIBUTOR_SOURCE_CD))
   ORDER BY cvo.alias DESC, cv.display
   WITH format, nocounter, separator = "  "
  ;end select
 ENDIF
END GO
