CREATE PROGRAM chart_access_user
 PROMPT
  "Output to File/Printer/MINE " = mine,
  "Enter Beginning Date of Report in MMDDYYYY Format " = curdate,
  "Enter Ending Date of Report in MMDDYYYY Format " = curdate
 SET mrn_ind = 0.0
 SET stat = uar_get_meaning_by_codeset(4,"MRN",1,mrn_ind)
 SET beg_date = cnvtdatetime(
  IF (( $2=curdate))  $2
  ELSE cnvtdate( $2)
  ENDIF
  ,0)
 SET end_date = cnvtdatetime(
  IF (( $3=curdate))  $3
  ELSE cnvtdate( $3)
  ENDIF
  ,235959)
 SET maxsecs = 0
 IF (validate(isodbc,0)=1)
  SET maxsecs = 15
 ENDIF
 SELECT DISTINCT INTO  $1
  p.person_id, p.prsnl_id, p.ppa_first_dt_tm"DD-MMM-YYYY  HH:MM:SS;;D",
  p.ppa_last_dt_tm"DD-MMM-YYYY  HH:MM:SS;;D", p.computer_name, pe.name_full_formatted,
  pe.birth_dt_tm, pe.person_id, pa.alias,
  pa.person_id, person_alias_type_disp = uar_get_code_display(pa.person_alias_type_cd), p
  .view_caption,
  pr.name_full_formatted, position_disp = uar_get_code_display(pr.position_cd), ppa_first_dt =
  cnvtdatetime(p.ppa_first_dt_tm),
  date1 = format(p.ppa_first_dt_tm,"MM/DD/YYYY HH:MM:SS;;D"), a.name, a.person_id,
  a.updt_id, a.username, a.end_dt_tm"MM/DD/YY  HH:MM:SS;;D",
  a.start_dt_tm"MM/DD/YY  HH:MM:SS;;D", start_dt = cnvtdatetime(a.start_dt_tm), ppa_first_dt =
  cnvtdatetime(p.ppa_first_dt_tm)
  FROM person_prsnl_activity p,
   person pe,
   person_alias pa,
   prsnl pr,
   application_context a
  PLAN (a
   WHERE a.updt_dt_tm BETWEEN cnvtdatetime(
    IF (( $2=curdate))  $2
    ELSE cnvtdate( $2)
    ENDIF
    ,0) AND cnvtdatetime(
    IF (( $3=curdate))  $3
    ELSE cnvtdate( $3)
    ENDIF
    ,235959)
    AND a.application_number=600005)
   JOIN (p
   WHERE a.person_id=p.prsnl_id
    AND p.ppa_first_dt_tm BETWEEN cnvtdatetime(
    IF (( $2=curdate))  $2
    ELSE cnvtdate( $2)
    ENDIF
    ,0) AND cnvtdatetime(
    IF (( $3=curdate))  $3
    ELSE cnvtdate( $3)
    ENDIF
    ,235959)
    AND p.updt_applctx=a.applctx
    AND p.view_caption > " ")
   JOIN (pe
   WHERE p.person_id=pe.person_id)
   JOIN (pa
   WHERE p.person_id=pa.person_id
    AND pa.person_alias_type_cd=mrn_ind)
   JOIN (pr
   WHERE p.prsnl_id=pr.person_id)
  ORDER BY pr.name_full_formatted, start_dt, ppa_first_dt,
   pe.name_full_formatted, p.view_caption, 0
  HEAD REPORT
   row 1, col 51, "CHART ACCESS BY USER:",
   row + 2
  HEAD PAGE
   row + 1, col 5, "Report Generated By:",
   col 26, curuser, col 44,
   "Report Generated On:", col 66, curdate,
   col 81, "Page:", col 87,
   curpage, row + 2, col 20,
   "From:", beg_date"mmm/dd/yyyy;;d", col 69,
   "To:", col 72, end_date"mmm/dd/yyyy;;d",
   row + 2
  HEAD pr.name_full_formatted
   row + 2, name_full_formatted1 = substring(1,50,pr.name_full_formatted), col 2,
   "User's Name:", col 26, name_full_formatted1,
   row + 1, col 2, "User's Position:",
   col 26, position_disp, row + 1,
   col 2, "Patient Name:", col 29,
   "Medical Record #:", col 48, "Time Access Began:",
   col 72, "Tab Accessed:", row + 2
  HEAD start_dt
   row + 1, col 2, "Time access began into Powerchart:",
   col 35, a.start_dt_tm, row + 1,
   col 2, "Time access ended in Powerchart:", col 35,
   a.end_dt_tm, col 103, "Computer Name:",
   row + 2
  DETAIL
   IF (((row+ 2) >= maxrow))
    BREAK
   ENDIF
   computer_name1 = substring(1,20,p.computer_name), alias1 = substring(1,10,pa.alias), view_caption1
    = substring(1,30,p.view_caption),
   col 35, alias1, col 48,
   p.ppa_first_dt_tm, col 72, view_caption1,
   col 103, computer_name1, row + 1,
   name_full_formatted2 = substring(1,30,pe.name_full_formatted), col 2, name_full_formatted2,
   row + 1
  FOOT  start_dt
   row + 2
  FOOT  pr.name_full_formatted
   col 38, "***************************************************", row + 2
  WITH maxcol = 500, noheading, format = variable,
   time = value(maxsecs)
 ;end select
END GO
