CREATE PROGRAM cv_omf_functions_compiler:dba
 CALL parser("RDB ASIS('CREATE OR REPLACE FUNCTION cv_get_case_result_dt_tm_q8(')")
 CALL parser("ASIS(' i_case_id     cv_case_abstr_data.cv_case_id%TYPE, ')")
 CALL parser("ASIS(' i_cdf_meaning code_value.cdf_meaning%TYPE) ')")
 CALL parser("ASIS('RETURN cv_case_abstr_data.result_dt_tm%TYPE IS ')")
 CALL parser("ASIS(' v_dt_tm cv_case_abstr_data.result_dt_tm%TYPE; ')")
 CALL parser("ASIS('BEGIN ')")
 CALL parser("ASIS(' SELECT ')")
 CALL parser("ASIS(' cs.result_dt_tm ')")
 CALL parser("ASIS(' INTO v_dt_tm ')")
 CALL parser("ASIS(' FROM cv_case_abstr_data cs, ')")
 CALL parser("ASIS(' code_value cv, ')")
 CALL parser("ASIS(' cv_xref ref ')")
 CALL parser("ASIS(' WHERE cs.cv_case_id = i_case_id ')")
 CALL parser("ASIS(' AND cs.event_cd       = ref.event_cd ')")
 CALL parser("ASIS(' AND ref.task_assay_cd =  cv.code_value ')")
 CALL parser("ASIS(' AND cv.code_set       = 14003 ')")
 CALL parser("ASIS(' AND cv.Cdf_Meaning    = UPPER(i_cdf_meaning) ')")
 CALL parser("ASIS(' AND cv.active_ind     = 1; ')")
 CALL parser("ASIS(' RETURN (v_dt_tm); ')")
 CALL parser("ASIS(' EXCEPTION ')")
 CALL parser("ASIS(' WHEN NO_DATA_FOUND THEN ')")
 CALL parser("ASIS(' RETURN NULL; ')")
 CALL parser("ASIS(' END cv_get_case_result_dt_tm_q8; ')")
 CALL parser("ASIS('/ ')")
 CALL parser("RDB ASIS('CREATE OR REPLACE FUNCTION cv_get_case_result_dt_tm_str(')")
 CALL parser("ASIS('    i_case_id     cv_case_abstr_data.cv_case_id%TYPE,')")
 CALL parser("ASIS('    i_cdf_meaning code_value.cdf_meaning%TYPE)')")
 CALL parser("ASIS('RETURN CHAR IS')")
 CALL parser("ASIS('   v_dt_tm VARCHAR2(40);')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    SELECT')")
 CALL parser("ASIS('           TO_CHAR(cs.result_dt_tm)')")
 CALL parser("ASIS('      INTO v_dt_tm')")
 CALL parser("ASIS('      FROM cv_case_abstr_data cs,')")
 CALL parser("ASIS('           code_value cv,')")
 CALL parser("ASIS('           cv_xref ref')")
 CALL parser("ASIS('     WHERE cs.cv_case_id = i_case_id')")
 CALL parser("ASIS('       AND cs.event_cd       = ref.event_cd')")
 CALL parser("ASIS('       AND ref.task_assay_cd =  cv.code_value')")
 CALL parser("ASIS('       AND cv.code_set       = 14003')")
 CALL parser("ASIS('       AND cv.Cdf_Meaning    = UPPER(i_cdf_meaning)')")
 CALL parser("ASIS('       AND cv.active_ind     = 1;')")
 CALL parser("ASIS('   RETURN (rtrim(ltrim(v_dt_tm)));')")
 CALL parser("ASIS('EXCEPTION')")
 CALL parser("ASIS('   WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('        RETURN '-';')")
 CALL parser("ASIS('END cv_get_case_result_dt_tm_str;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('CREATE OR REPLACE FUNCTION cv_get_les_result_dt_tm_q8(')")
 CALL parser("ASIS('    i_lesion_id   cv_les_abstr_data.lesion_id%TYPE,')")
 CALL parser("ASIS('    i_cdf_meaning code_value.cdf_meaning%TYPE)')")
 CALL parser("ASIS('RETURN cv_les_abstr_data.result_dt_tm%TYPE IS')")
 CALL parser("ASIS('   v_dt_tm cv_les_abstr_data.result_dt_tm%TYPE;')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    SELECT')")
 CALL parser("ASIS('           ls.result_dt_tm')")
 CALL parser("ASIS('      INTO v_dt_tm')")
 CALL parser("ASIS('      FROM cv_les_abstr_data ls,')")
 CALL parser("ASIS('           code_value cv,')")
 CALL parser("ASIS('           cv_xref ref')")
 CALL parser("ASIS('     WHERE ls.lesion_id         = i_lesion_id')")
 CALL parser("ASIS('       AND ls.event_cd          = ref.event_cd')")
 CALL parser("ASIS('       AND ref.task_assay_cd    = cv.code_value')")
 CALL parser("ASIS('       AND cv.code_set          = 14003')")
 CALL parser("ASIS('       AND cv.Cdf_Meaning       = UPPER(i_cdf_meaning)')")
 CALL parser("ASIS('       AND cv.active_ind        = 1;')")
 CALL parser("ASIS('  RETURN (v_dt_tm);')")
 CALL parser("ASIS('EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('    RETURN NULL;')")
 CALL parser("ASIS('END cv_get_les_result_dt_tm_q8;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('CREATE OR REPLACE FUNCTION cv_get_les_result_dt_tm_str(')")
 CALL parser("ASIS('    i_lesion_id   cv_les_abstr_data.lesion_id%TYPE,')")
 CALL parser("ASIS('    i_cdf_meaning code_value.cdf_meaning%TYPE)')")
 CALL parser("ASIS('RETURN CHAR IS')")
 CALL parser("ASIS('   v_dt_tm VARCHAR2(40);')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    SELECT')")
 CALL parser("ASIS('           TO_CHAR(ls.result_dt_tm)')")
 CALL parser("ASIS('      INTO v_dt_tm')")
 CALL parser("ASIS('      FROM cv_les_abstr_data ls,')")
 CALL parser("ASIS('          code_value cv,')")
 CALL parser("ASIS('           cv_xref ref')")
 CALL parser("ASIS('     WHERE ls.lesion_id         = i_lesion_id')")
 CALL parser("ASIS('       AND ls.event_cd          = ref.event_cd')")
 CALL parser("ASIS('       AND ref.task_assay_cd    = cv.code_value')")
 CALL parser("ASIS('       AND cv.code_set          = 14003')")
 CALL parser("ASIS('       AND cv.Cdf_Meaning       = UPPER(i_cdf_meaning)')")
 CALL parser("ASIS('       AND cv.active_ind        = 1;')")
 CALL parser("ASIS('  RETURN (ltrim(rtrim(v_dt_tm)));')")
 CALL parser("ASIS('EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('    RETURN '-';')")
 CALL parser("ASIS('END cv_get_les_result_dt_tm_str;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('CREATE OR REPLACE FUNCTION cv_get_proc_result_dt_tm_q8(')")
 CALL parser("ASIS('    i_procedure_id cv_proc_abstr_data.procedure_id%TYPE,')")
 CALL parser("ASIS('    i_cdf_meaning  code_value.cdf_meaning%TYPE)')")
 CALL parser("ASIS('RETURN cv_proc_abstr_data.result_dt_tm%TYPE IS')")
 CALL parser("ASIS('    v_dt_tm cv_proc_abstr_data.result_dt_tm%TYPE;')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    SELECT')")
 CALL parser("ASIS('           proc.result_dt_tm')")
 CALL parser("ASIS('      INTO v_dt_tm')")
 CALL parser("ASIS('      FROM cv_proc_abstr_data proc,')")
 CALL parser("ASIS('           code_value cv,')")
 CALL parser("ASIS('           cv_xref ref')")
 CALL parser("ASIS('     WHERE proc.procedure_id = i_procedure_id')")
 CALL parser("ASIS('       AND proc.event_cd     = ref.event_cd')")
 CALL parser("ASIS('       AND ref.task_assay_cd = cv.code_value')")
 CALL parser("ASIS('       AND cv.cdf_meaning    = UPPER(i_cdf_meaning)')")
 CALL parser("ASIS('       AND cv.code_set       = 14003')")
 CALL parser("ASIS('       AND cv.active_ind     = 1;')")
 CALL parser("ASIS('  RETURN (v_dt_tm);')")
 CALL parser("ASIS('EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('    RETURN NULL;')")
 CALL parser("ASIS('END cv_get_proc_result_dt_tm_q8;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('CREATE OR REPLACE FUNCTION cv_get_proc_result_dt_tm_str(')")
 CALL parser("ASIS('    i_procedure_id cv_proc_abstr_data.procedure_id%TYPE,')")
 CALL parser("ASIS('    i_cdf_meaning  code_value.cdf_meaning%TYPE)')")
 CALL parser("ASIS('RETURN CHAR IS')")
 CALL parser("ASIS('    v_dt_tm VARCHAR2(40);')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    SELECT')")
 CALL parser("ASIS('           TO_CHAR(proc.result_dt_tm)')")
 CALL parser("ASIS('      INTO v_dt_tm')")
 CALL parser("ASIS('      FROM cv_proc_abstr_data proc,')")
 CALL parser("ASIS('           code_value cv,')")
 CALL parser("ASIS('           cv_xref ref')")
 CALL parser("ASIS('     WHERE proc.procedure_id = i_procedure_id')")
 CALL parser("ASIS('       AND proc.event_cd     = ref.event_cd')")
 CALL parser("ASIS('       AND ref.task_assay_cd = cv.code_value')")
 CALL parser("ASIS('       AND cv.cdf_meaning    = UPPER(i_cdf_meaning)')")
 CALL parser("ASIS('       AND cv.code_set       = 14003')")
 CALL parser("ASIS('       AND cv.active_ind     = 1;')")
 CALL parser("ASIS('  RETURN (rtrim(ltrim(v_dt_tm)));')")
 CALL parser("ASIS('EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('    RETURN '-';')")
 CALL parser("ASIS('END cv_get_proc_result_dt_tm_str;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_cv_case_nomen_id')")
 CALL parser("ASIS('       (i_case_id    cv_case_abstr_data.cv_case_id%TYPE,')")
 CALL parser("ASIS('        i_Cdf_Meaning     code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('        )')")
 CALL parser("ASIS('                          return NUMBER is')")
 CALL parser("ASIS('   v_id NUMBER;')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select  nom.nomenclature_id')")
 CALL parser("ASIS('      into v_id')")
 CALL parser("ASIS('    From cv_case_abstr_data c,')")
 CALL parser("ASIS('      code_value cv,')")
 CALL parser("ASIS('      nomenclature nom,')")
 CALL parser("ASIS('      cv_xref ref')")
 CALL parser("ASIS('    Where c.cv_case_id   = i_case_id')")
 CALL parser("ASIS('      and c.event_cd     = ref.event_cd and')")
 CALL parser("ASIS('      ref.task_assay_cd  =  cv.code_value')")
 CALL parser("ASIS('      and cv.code_set    = 14003')")
 CALL parser("ASIS('      and cv.Cdf_Meaning = UPPER(i_Cdf_Meaning) AND')")
 CALL parser("ASIS('      cv.active_ind      = 1 AND')")
 CALL parser("ASIS('      c.nomenclature_id  = nom.nomenclature_id;')")
 CALL parser("ASIS('    return(v_id);')")
 CALL parser("ASIS('EXCEPTION')")
 CALL parser("ASIS('   WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return(0);')")
 CALL parser("ASIS('END cv_get_cv_case_nomen_id;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_cv_case_nomen_str')")
 CALL parser("ASIS('        (i_case_id  cv_case_abstr_data.cv_case_id%TYPE,')")
 CALL parser("ASIS('         i_Cdf_Meaning code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('          )')")
 CALL parser("ASIS('                          return CHAR is')")
 CALL parser("ASIS('   v_desc VARCHAR2(255);')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select')")
 CALL parser("ASIS('      nom.source_string')")
 CALL parser("ASIS('      into v_desc')")
 CALL parser("ASIS('    From cv_case_abstr_data cs,')")
 CALL parser("ASIS('      nomenclature nom,')")
 CALL parser("ASIS('      code_value cv,')")
 CALL parser("ASIS('      cv_xref ref')")
 CALL parser("ASIS('    Where cs.cv_case_id      = i_case_id')")
 CALL parser("ASIS('      and cs.event_cd        = ref.event_cd and')")
 CALL parser("ASIS('      ref.task_assay_cd      = cv.code_value and')")
 CALL parser("ASIS('      ref.task_assay_cd      = cv.code_value and')")
 CALL parser("ASIS('      cv.code_set            =14003 and')")
 CALL parser("ASIS('      cv.Cdf_Meaning         = UPPER(i_Cdf_Meaning) AND')")
 CALL parser("ASIS('      cv.active_ind          = 1')")
 CALL parser("ASIS('      and cs.nomenclature_id = nom.nomenclature_id;')")
 CALL parser("ASIS('    return(v_desc);')")
 CALL parser("ASIS(' EXCEPTION')")
 CALL parser("ASIS(' WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return('-');')")
 CALL parser("ASIS('END cv_get_cv_case_nomen_str;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_cv_case_result_cd')")
 CALL parser("ASIS('        (i_case_id  cv_case_abstr_data.cv_case_id%TYPE,')")
 CALL parser("ASIS('         i_Cdf_Meaning code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('          )')")
 CALL parser("ASIS('                          return NUMBER IS')")
 CALL parser("ASIS('  v_result_cd NUMBER;')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select')")
 CALL parser("ASIS('      cs.result_cd')")
 CALL parser("ASIS('      into v_result_cd')")
 CALL parser("ASIS('    From cv_case_abstr_data cs,')")
 CALL parser("ASIS('      code_value cv,')")
 CALL parser("ASIS('      cv_xref ref')")
 CALL parser("ASIS('    Where  cs.cv_case_id     = i_case_id and')")
 CALL parser("ASIS('           cs.event_cd       = ref.event_cd and')")
 CALL parser("ASIS('           ref.task_assay_cd =  cv.code_value and')")
 CALL parser("ASIS('           cv.code_set       = 14003 and')")
 CALL parser("ASIS('           cv.Cdf_Meaning    = UPPER(i_Cdf_Meaning) AND')")
 CALL parser("ASIS('           cv.active_ind     = 1;')")
 CALL parser("ASIS('    return(v_result_cd);')")
 CALL parser("ASIS('  EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return (0);')")
 CALL parser("ASIS('END cv_get_cv_case_result_cd;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_cv_case_result_val')")
 CALL parser("ASIS('        (i_case_id  cv_case_abstr_data.cv_case_id%TYPE,')")
 CALL parser("ASIS('         i_Cdf_Meaning code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('          )')")
 CALL parser("ASIS('                          return CHAR is')")
 CALL parser("ASIS('   v_desc VARCHAR2(255);')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select')")
 CALL parser("ASIS('      cs.result_val')")
 CALL parser("ASIS('      into v_desc')")
 CALL parser("ASIS('    From cv_case_abstr_data cs,')")
 CALL parser("ASIS('      code_value cv,')")
 CALL parser("ASIS('      cv_xref ref')")
 CALL parser("ASIS('    Where  cs.cv_case_id     = i_case_id and')")
 CALL parser("ASIS('           cs.event_cd       = ref.event_cd and')")
 CALL parser("ASIS('           ref.task_assay_cd =  cv.code_value and')")
 CALL parser("ASIS('           cv.code_set       = 14003 and')")
 CALL parser("ASIS('          cv.Cdf_Meaning    = UPPER(i_Cdf_Meaning) AND')")
 CALL parser("ASIS('           cv.active_ind     = 1;')")
 CALL parser("ASIS('    return(v_desc);')")
 CALL parser("ASIS('  EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return ('-');')")
 CALL parser("ASIS('END cv_get_cv_case_result_val;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_cv_les_nomen_id')")
 CALL parser("ASIS('       (i_les_id    cv_les_abstr_data.lesion_id%TYPE,')")
 CALL parser("ASIS('        i_Cdf_Meaning     code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('        )')")
 CALL parser("ASIS('                          return NUMBER is')")
 CALL parser("ASIS('   v_id NUMBER;')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select  nom.nomenclature_id')")
 CALL parser("ASIS('      into v_id')")
 CALL parser("ASIS('    From cv_les_abstr_data les,')")
 CALL parser("ASIS('      code_value cv,')")
 CALL parser("ASIS('      nomenclature nom,')")
 CALL parser("ASIS('      cv_xref ref')")
 CALL parser("ASIS('    Where les.lesion_id     = i_les_id')")
 CALL parser("ASIS('      and les.event_cd      = ref.event_cd and')")
 CALL parser("ASIS('      ref.task_assay_cd     = cv.code_value')")
 CALL parser("ASIS('      and cv.code_set       = 14003')")
 CALL parser("ASIS('      and cv.Cdf_Meaning    = UPPER(i_Cdf_Meaning) AND')")
 CALL parser("ASIS('      cv.active_ind         = 1 AND')")
 CALL parser("ASIS('      les.nomenclature_id   = nom.nomenclature_id;')")
 CALL parser("ASIS('    return(v_id);')")
 CALL parser("ASIS(' EXCEPTION')")
 CALL parser("ASIS('   WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return(0);')")
 CALL parser("ASIS('END cv_get_cv_les_nomen_id;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_cv_les_nomen_str')")
 CALL parser("ASIS('       (i_lesion_id      cv_les_abstr_data.lesion_id%TYPE,')")
 CALL parser("ASIS('        i_Cdf_Meaning     code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('        )')")
 CALL parser("ASIS('                          return CHAR is')")
 CALL parser("ASIS('   v_desc VARCHAR2(255);')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select')")
 CALL parser("ASIS('      nom.source_string')")
 CALL parser("ASIS('      into v_desc')")
 CALL parser("ASIS('    From')")
 CALL parser("ASIS('      cv_les_abstr_data ls,')")
 CALL parser("ASIS('      cv_xref ref,')")
 CALL parser("ASIS('      code_value cv,')")
 CALL parser("ASIS('      nomenclature nom')")
 CALL parser("ASIS('    Where ls.lesion_id        = i_lesion_id and')")
 CALL parser("ASIS('       ls.event_cd            = ref.event_cd and')")
 CALL parser("ASIS('       ref.task_assay_cd      = cv.code_value and')")
 CALL parser("ASIS('       cv.code_set            = 14003')")
 CALL parser("ASIS('       and cv.Cdf_Meaning     = UPPER(i_Cdf_Meaning)')")
 CALL parser("ASIS('       and cv.active_ind      = 1')")
 CALL parser("ASIS('       and ls.nomenclature_id = nom.nomenclature_id;')")
 CALL parser("ASIS('    return(v_desc);')")
 CALL parser("ASIS(' EXCEPTION')")
 CALL parser("ASIS('   WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return('-');')")
 CALL parser("ASIS('END cv_get_cv_les_nomen_str;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_cv_les_result_val')")
 CALL parser("ASIS('       (i_lesion_id      cv_les_abstr_data.lesion_id%TYPE,')")
 CALL parser("ASIS('        i_Cdf_Meaning     code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('        )')")
 CALL parser("ASIS('                          return CHAR is')")
 CALL parser("ASIS('   v_desc VARCHAR2(255);')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select')")
 CALL parser("ASIS('      ls.result_val')")
 CALL parser("ASIS('      into v_desc')")
 CALL parser("ASIS('     From cv_les_abstr_data ls,')")
 CALL parser("ASIS('     code_value cv,')")
 CALL parser("ASIS('     cv_xref ref')")
 CALL parser("ASIS('     Where ls.lesion_id    = i_lesion_id and')")
 CALL parser("ASIS('       ls.event_cd         = ref.event_cd and')")
 CALL parser("ASIS('       ref.task_assay_cd   = cv.code_value and')")
 CALL parser("ASIS('       cv.code_set         = 14003')")
 CALL parser("ASIS('       and cv.Cdf_Meaning  = UPPER(i_Cdf_Meaning)')")
 CALL parser("ASIS('       and cv.active_ind   = 1;')")
 CALL parser("ASIS('    return(v_desc);')")
 CALL parser("ASIS(' EXCEPTION')")
 CALL parser("ASIS('   WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return('-');')")
 CALL parser("ASIS('END cv_get_cv_les_result_val;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_cv_proc_nomen_id')")
 CALL parser("ASIS('       (i_procedure_id    cv_proc_abstr_data.procedure_id%TYPE,')")
 CALL parser("ASIS('        i_Cdf_Meaning     code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('        )                  return NUMBER is')")
 CALL parser("ASIS('   v_id NUMBER;')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select  nom.nomenclature_id')")
 CALL parser("ASIS('      into v_id')")
 CALL parser("ASIS('    From')")
 CALL parser("ASIS('      cv_proc_abstr_data proc,code_value cv,nomenclature nom,cv_xref ref')")
 CALL parser("ASIS('    Where proc.procedure_id  = i_procedure_id')")
 CALL parser("ASIS('       and proc.event_cd     = ref.event_cd and')")
 CALL parser("ASIS('       ref.task_assay_cd     = cv.code_value')")
 CALL parser("ASIS('       and cv.code_set       = 14003')")
 CALL parser("ASIS('       and cv.Cdf_Meaning    = UPPER(i_Cdf_Meaning) AND')")
 CALL parser("ASIS('       cv.active_ind         = 1     AND')")
 CALL parser("ASIS('       proc.nomenclature_id  = nom.nomenclature_id;')")
 CALL parser("ASIS('    return(v_id);')")
 CALL parser("ASIS(' EXCEPTION')")
 CALL parser("ASIS('   WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return(0);')")
 CALL parser("ASIS('END cv_get_cv_proc_nomen_id;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_cv_proc_result_val')")
 CALL parser("ASIS('        (i_procedure_id  cv_proc_abstr_data.procedure_id%TYPE,')")
 CALL parser("ASIS('         i_Cdf_Meaning code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('          )')")
 CALL parser("ASIS('                          return CHAR is')")
 CALL parser("ASIS('   v_desc VARCHAR2(255);')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select')")
 CALL parser("ASIS('      proc.result_val')")
 CALL parser("ASIS('      into v_desc')")
 CALL parser("ASIS('   From')")
 CALL parser("ASIS('      cv_proc_abstr_data proc,')")
 CALL parser("ASIS('      code_value cv,')")
 CALL parser("ASIS('      cv_xref ref')")
 CALL parser("ASIS('   Where')")
 CALL parser("ASIS('       proc.procedure_id = i_procedure_id')")
 CALL parser("ASIS('       and proc.event_cd = ref.event_cd and')")
 CALL parser("ASIS('       ref.task_assay_cd = cv.code_value and')")
 CALL parser("ASIS('       cv.Cdf_Meaning    = UPPER(i_Cdf_Meaning) AND')")
 CALL parser("ASIS('       cv.code_set       =14003 and')")
 CALL parser("ASIS('       cv.active_ind     = 1;')")
 CALL parser("ASIS('    return(v_desc);')")
 CALL parser("ASIS('  EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return('-');')")
 CALL parser("ASIS('END cv_get_cv_proc_result_val;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('CREATE OR REPLACE FUNCTION cv_get_cv_count_data')")
 CALL parser("ASIS('          (i_parent_entity_id  cv_count_data.parent_entity_id%TYPE,')")
 CALL parser("ASIS('           i_count_des_key     cv_count.count_description_key%TYPE)')")
 CALL parser("ASIS('RETURN NUMBER is v_count NUMBER;')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    SELECT ccd.count INTO v_count')")
 CALL parser("ASIS('      FROM cv_count cc, cv_count_data ccd')")
 CALL parser("ASIS('     WHERE cc.count_id = ccd.count_id')")
 CALL parser("ASIS('       AND cc.count_description_key = UPPER(i_count_des_key)')")
 CALL parser("ASIS('       AND ccd.parent_entity_id = i_parent_entity_id')")
 CALL parser("ASIS('       AND ccd.active_ind     = 1;')")
 CALL parser("ASIS('   RETURN (v_count);')")
 CALL parser("ASIS('  EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('    RETURN 0;')")
 CALL parser("ASIS('  WHEN OTHERS THEN')")
 CALL parser("ASIS('    RETURN 0;')")
 CALL parser("ASIS('END cv_get_cv_count_data;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_les_abstr_result_int')")
 CALL parser("ASIS('       (i_lesion_id      cv_les_abstr_data.lesion_id%TYPE,')")
 CALL parser("ASIS('        i_Cdf_Meaning     code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('        )')")
 CALL parser("ASIS('                          return NUMBER is')")
 CALL parser("ASIS('   v_int NUMBER;')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select')")
 CALL parser("ASIS('      to_number(ls.result_val)')")
 CALL parser("ASIS('      into v_int')")
 CALL parser("ASIS('     From cv_les_abstr_data ls,')")
 CALL parser("ASIS('     code_value cv,')")
 CALL parser("ASIS('     cv_xref ref')")
 CALL parser("ASIS('     Where ls.lesion_id    = i_lesion_id and')")
 CALL parser("ASIS('       ls.event_cd         = ref.event_cd and')")
 CALL parser("ASIS('       ref.task_assay_cd   = cv.code_value and')")
 CALL parser("ASIS('       cv.code_set         = 14003')")
 CALL parser("ASIS('       and cv.Cdf_Meaning  = UPPER(i_Cdf_Meaning)')")
 CALL parser("ASIS('       and cv.active_ind   = 1;')")
 CALL parser("ASIS('    return(v_int);')")
 CALL parser("ASIS(' EXCEPTION')")
 CALL parser("ASIS('   WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return(0);')")
 CALL parser("ASIS('END cv_get_les_abstr_result_int;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_case_abstr_result_id')")
 CALL parser("ASIS('        (i_case_id  cv_case_abstr_data.cv_case_id%TYPE,')")
 CALL parser("ASIS('         i_Cdf_Meaning code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('          )')")
 CALL parser("ASIS('                          return NUMBER IS')")
 CALL parser("ASIS('  v_result_id NUMBER;')")
 CALL parser("ASIS('Begin')")
 CALL parser("ASIS('    Select')")
 CALL parser("ASIS('      cs.result_id')")
 CALL parser("ASIS('      into v_result_id')")
 CALL parser("ASIS('	From cv_case_abstr_data cs,')")
 CALL parser("ASIS('      code_value cv,')")
 CALL parser("ASIS('      cv_xref ref')")
 CALL parser("ASIS('    Where  cs.cv_case_id     = i_case_id and')")
 CALL parser("ASIS('           cs.event_cd       = ref.event_cd and')")
 CALL parser("ASIS('           ref.task_assay_cd =  cv.code_value and')")
 CALL parser("ASIS('           cv.code_set       = 14003 and')")
 CALL parser("ASIS('           cv.Cdf_Meaning    = UPPER(i_Cdf_Meaning) AND')")
 CALL parser("ASIS('           cv.active_ind     = 1;')")
 CALL parser("ASIS('    return(v_result_id);')")
 CALL parser("ASIS('  EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return (0);')")
 CALL parser("ASIS('END cv_get_case_abstr_result_id;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_proc_abstr_result_id')")
 CALL parser("ASIS('        (i_procedure_id  cv_proc_abstr_data.procedure_id%TYPE,')")
 CALL parser("ASIS('         i_Cdf_Meaning code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('          )')")
 CALL parser("ASIS('                          return NUMBER is')")
 CALL parser("ASIS('   v_result_id NUMBER;')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select')")
 CALL parser("ASIS('      proc.result_id')")
 CALL parser("ASIS('    into v_result_id')")
 CALL parser("ASIS('   From')")
 CALL parser("ASIS('      cv_proc_abstr_data proc,')")
 CALL parser("ASIS('      cv_xref ref,')")
 CALL parser("ASIS('	  code_value cv')")
 CALL parser("ASIS('   Where')")
 CALL parser("ASIS('       proc.procedure_id = i_procedure_id and')")
 CALL parser("ASIS('       proc.event_cd = ref.event_cd and')")
 CALL parser("ASIS('       ref.task_assay_cd = cv.code_value and')")
 CALL parser("ASIS('	   cv.code_set       = 14003 and')")
 CALL parser("ASIS('       cv.Cdf_Meaning    = UPPER(i_Cdf_Meaning) AND')")
 CALL parser("ASIS('       cv.active_ind     = 1;')")
 CALL parser("ASIS('    return(v_result_id);')")
 CALL parser("ASIS('  EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return(0);')")
 CALL parser("ASIS('END cv_get_proc_abstr_result_id;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_proc_abstr_result_cd')")
 CALL parser("ASIS('        (i_procedure_id  cv_proc_abstr_data.procedure_id%TYPE,')")
 CALL parser("ASIS('         i_Cdf_Meaning code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('          )')")
 CALL parser("ASIS('                          return NUMBER is')")
 CALL parser("ASIS('   v_result_cd NUMBER;')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select')")
 CALL parser("ASIS('      proc.result_cd')")
 CALL parser("ASIS('      into v_result_cd')")
 CALL parser("ASIS('   From')")
 CALL parser("ASIS('      cv_proc_abstr_data proc,')")
 CALL parser("ASIS('      code_value cv,')")
 CALL parser("ASIS('      cv_xref ref')")
 CALL parser("ASIS('   Where')")
 CALL parser("ASIS('       proc.procedure_id = i_procedure_id')")
 CALL parser("ASIS('       and proc.event_cd = ref.event_cd and')")
 CALL parser("ASIS('       ref.task_assay_cd = cv.code_value and')")
 CALL parser("ASIS('       cv.Cdf_Meaning    = UPPER(i_Cdf_Meaning) AND')")
 CALL parser("ASIS('       cv.code_set       =14003 and')")
 CALL parser("ASIS('       cv.active_ind     = 1;')")
 CALL parser("ASIS('    return(v_result_cd);')")
 CALL parser("ASIS('  EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return(0);')")
 CALL parser("ASIS('END cv_get_proc_abstr_result_cd;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_case_abstr_result_int')")
 CALL parser("ASIS('        (i_case_id  cv_case_abstr_data.cv_case_id%TYPE,')")
 CALL parser("ASIS('         i_Cdf_Meaning code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('          )')")
 CALL parser("ASIS('                          return NUMBER is')")
 CALL parser("ASIS('   v_int NUMBER;')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select')")
 CALL parser("ASIS('      to_number(cs.result_val)')")
 CALL parser("ASIS('      into v_int')")
 CALL parser("ASIS('    From cv_case_abstr_data cs,')")
 CALL parser("ASIS('      code_value cv,')")
 CALL parser("ASIS('      cv_xref ref')")
 CALL parser("ASIS('    Where  cs.cv_case_id     = i_case_id and')")
 CALL parser("ASIS('           cs.event_cd       = ref.event_cd and')")
 CALL parser("ASIS('           ref.task_assay_cd =  cv.code_value and')")
 CALL parser("ASIS('           cv.code_set       = 14003 and')")
 CALL parser("ASIS('           cv.Cdf_Meaning    = UPPER(i_Cdf_Meaning) AND')")
 CALL parser("ASIS('           cv.active_ind     = 1;')")
 CALL parser("ASIS('    return(v_int);')")
 CALL parser("ASIS('  EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return (0);')")
 CALL parser("ASIS('END cv_get_case_abstr_result_int;')")
 CALL parser("ASIS('/')")
 CALL parser("RDB ASIS('Create or replace function cv_get_proc_abstr_result_int')")
 CALL parser("ASIS('        (i_procedure_id  cv_proc_abstr_data.procedure_id%TYPE,')")
 CALL parser("ASIS('         i_Cdf_Meaning code_value.Cdf_Meaning%TYPE')")
 CALL parser("ASIS('          )')")
 CALL parser("ASIS('				return NUMBER is')")
 CALL parser("ASIS('   v_int NUMBER;')")
 CALL parser("ASIS('BEGIN')")
 CALL parser("ASIS('    Select')")
 CALL parser("ASIS('      to_number(proc.result_val)')")
 CALL parser("ASIS('      into v_int')")
 CALL parser("ASIS('   From')")
 CALL parser("ASIS('      cv_proc_abstr_data proc,')")
 CALL parser("ASIS('      code_value cv,')")
 CALL parser("ASIS('      cv_xref ref')")
 CALL parser("ASIS('   Where')")
 CALL parser("ASIS('       proc.procedure_id = i_procedure_id')")
 CALL parser("ASIS('       and proc.event_cd = ref.event_cd and')")
 CALL parser("ASIS('       ref.task_assay_cd = cv.code_value and')")
 CALL parser("ASIS('       cv.Cdf_Meaning    = UPPER(i_Cdf_Meaning) AND')")
 CALL parser("ASIS('       cv.code_set       = 14003 and')")
 CALL parser("ASIS('       cv.active_ind     = 1;')")
 CALL parser("ASIS('    return(v_int);')")
 CALL parser("ASIS('  EXCEPTION')")
 CALL parser("ASIS('  WHEN NO_DATA_FOUND THEN')")
 CALL parser("ASIS('     return(0);')")
 CALL parser("ASIS('END cv_get_proc_abstr_result_int;')")
 CALL parser("ASIS('/')")
END GO
