CREATE PROGRAM dcp_create_fld_meaning:dba
 EXECUTE orm_create_oe_field_meaning 0001, "FREETEXTORD", "Freetext Orderable"
 EXECUTE orm_create_oe_field_meaning 0002, "CONSULTDOC", "Consulting Physician"
 EXECUTE orm_create_oe_field_meaning 0007, "ACCESSION", "Accession number"
 EXECUTE orm_create_oe_field_meaning 0008, "REPPRI", "Reporting Priority"
 EXECUTE orm_create_oe_field_meaning 0009, "SPECIMEN TYPE", "Specimen Type"
 EXECUTE orm_create_oe_field_meaning 0010, "ACCESSION ID", "Accession Id"
 EXECUTE orm_create_oe_field_meaning 0012, "ISOLATIONCODE", "Isolation Code"
 EXECUTE orm_create_oe_field_meaning 0014, "RENDPHYS", "Rendering Physician"
 EXECUTE orm_create_oe_field_meaning 0015, "INDICATION", "Indication"
 EXECUTE orm_create_oe_field_meaning 0016, "OBJECTIVE", "Objective"
 EXECUTE orm_create_oe_field_meaning 0017, "PACKETRTG", "Packet Routing"
 EXECUTE orm_create_oe_field_meaning 0018, "PERFORMLOC", "Performing Location"
 EXECUTE orm_create_oe_field_meaning 0020, "ICD9", "ICD9"
 EXECUTE orm_create_oe_field_meaning 0021, "DEVICE", "Device"
 EXECUTE orm_create_oe_field_meaning 0022, "GAS%", "Gas Percentage"
 EXECUTE orm_create_oe_field_meaning 0023, "FIO2", "FIO2"
 EXECUTE orm_create_oe_field_meaning 0024, "VENT MODE", "Vent Mode"
 EXECUTE orm_create_oe_field_meaning 0025, "VT", "Tidal Volume"
 EXECUTE orm_create_oe_field_meaning 0026, "PEEP", "PEEP"
 EXECUTE orm_create_oe_field_meaning 0027, "PRSUPP", "Pressure Support"
 EXECUTE orm_create_oe_field_meaning 0028, "MINVOL", "Minute Volume"
 EXECUTE orm_create_oe_field_meaning 0029, "IERATIO", "IE Ratio"
 EXECUTE orm_create_oe_field_meaning 0030, "BODYSITE", "Body Site"
 EXECUTE orm_create_oe_field_meaning 0031, "CURRENTMEDS", "Currently Administered Medication"
 EXECUTE orm_create_oe_field_meaning 0032, "SOURCECMNT", "Source Comment"
 EXECUTE orm_create_oe_field_meaning 0033, "EPISODE#", "Outbreak/Episode Number"
 EXECUTE orm_create_oe_field_meaning 0035, "FROZREQUEST", "Frozen Section Requested"
 EXECUTE orm_create_oe_field_meaning 0036, "BLOODREQUEST", "Blood Products Requested"
 EXECUTE orm_create_oe_field_meaning 0038, "XRAYREQUEST", "XRay Requested"
 EXECUTE orm_create_oe_field_meaning 0041, "BILLFLAG", "Bill Flag"
 EXECUTE orm_create_oe_field_meaning 0042, "COLLBY", "Collected By"
 EXECUTE orm_create_oe_field_meaning 0043, "COLLPRI", "Collection Priority"
 EXECUTE orm_create_oe_field_meaning 0045, "LABLOC", "Laboratory Location"
 EXECUTE orm_create_oe_field_meaning 0046, "ORDERLOC", "Order Location"
 EXECUTE orm_create_oe_field_meaning 0047, "PRINTLBL", "Print Label"
 EXECUTE orm_create_oe_field_meaning 0048, "RSRCHACCT", "Research Account"
 EXECUTE orm_create_oe_field_meaning 0049, "LBLPRINTER", "Label Printer"
 EXECUTE orm_create_oe_field_meaning 0050, "COLLMETHOD", "Collection Method"
 EXECUTE orm_create_oe_field_meaning 0051, "REQSTARTDTTM", "Requested Start Date/Time"
 EXECUTE orm_create_oe_field_meaning 0053, "SIDE", "Side"
 EXECUTE orm_create_oe_field_meaning 0054, "PAYOR", "Payor/Ins Approval Nbr"
 EXECUTE orm_create_oe_field_meaning 0055, "PREGNANT", "Pregnant"
 EXECUTE orm_create_oe_field_meaning 0056, "LNMP", "LNMP"
 EXECUTE orm_create_oe_field_meaning 0057, "QUANTITY", "Quantity"
 EXECUTE orm_create_oe_field_meaning 0058, "CHEMO", "Under  ing Chemo/Radiation Therapy"
 EXECUTE orm_create_oe_field_meaning 0066, "MODE", "Mode"
 EXECUTE orm_create_oe_field_meaning 0067, "NBRREFILLS", "Number of Refills"
 EXECUTE orm_create_oe_field_meaning 0068, "%O2", "Percent O2"
 EXECUTE orm_create_oe_field_meaning 0070, "ACUITYLVL", "Acuity Level"
 EXECUTE orm_create_oe_field_meaning 0075, "BBUNITTYPE", "Unit Type"
 EXECUTE orm_create_oe_field_meaning 0082, "EQUIPID", "Equipment ID"
 EXECUTE orm_create_oe_field_meaning 0086, "INVENTORYLOC", "Inventory Location"
 EXECUTE orm_create_oe_field_meaning 0091, "PAYMETHOD", "Payment Method"
 EXECUTE orm_create_oe_field_meaning 0093, "NBRLBLS", "Number of Labels"
 EXECUTE orm_create_oe_field_meaning 0096, "PTFASTING", "Patient Fasting?"
 EXECUTE orm_create_oe_field_meaning 0097, "PTHASIV", "Patient Has IV?"
 EXECUTE orm_create_oe_field_meaning 0098, "PTOXYGEN", "Patient on Oxygen?"
 EXECUTE orm_create_oe_field_meaning 0099, "WEIGHT", "Weight"
 EXECUTE orm_create_oe_field_meaning 0100, "WEIGHTUNIT", "Weight Unit"
 EXECUTE orm_create_oe_field_meaning 0101, "PATOWNMED", "Patient's Owm Meds"
 EXECUTE orm_create_oe_field_meaning 0106, "REFERPHYS", "Referring Physician"
 EXECUTE orm_create_oe_field_meaning 0109, "SPECAVAIL", "Specimen Available"
 EXECUTE orm_create_oe_field_meaning 0110, "SCHEDDTTM", "Scheduled Date/Time"
 EXECUTE orm_create_oe_field_meaning 0113, "SCHEDDTTMAPPR", "Scheduled Date/Time - Approximate"
 EXECUTE orm_create_oe_field_meaning 0114, "CONSTANTIND", "Constant Indicator"
 EXECUTE orm_create_oe_field_meaning 0116, "LBLCMNT", "Label Comment"
 EXECUTE orm_create_oe_field_meaning 0117, "IVSITE", "IV Site"
 EXECUTE orm_create_oe_field_meaning 0118, "INFUSEOVER", "Infuse Over"
 EXECUTE orm_create_oe_field_meaning 0119, "FREETEXTPHYS", "Freetext Provider"
 EXECUTE orm_create_oe_field_meaning 0120, "FUTUREORDER", "Future Order"
 EXECUTE orm_create_oe_field_meaning 0121, "SCHEDULEIND", "Schedule Indicator"
 EXECUTE orm_create_oe_field_meaning 0122, "HOLDPROCESSIND", "Hold Processing Indicator"
 EXECUTE orm_create_oe_field_meaning 0123, "SCHEDULINGINSTRUCTIONS", "Scheduling Instruction"
 EXECUTE orm_create_oe_field_meaning 0124, "SCHEDAUTHNBR", "Scheduling Authorization Number"
 EXECUTE orm_create_oe_field_meaning 0125, "HOLDUNTILCOLLECTED", "Hold Until Collected"
 EXECUTE orm_create_oe_field_meaning 0126, "ENCOUNTERTYPE", "Encounter Type"
 EXECUTE orm_create_oe_field_meaning 0127, "PRIORITY", "Priority"
 EXECUTE orm_create_oe_field_meaning 0128, "SURPSUPPLIES", "Surg Supplies"
 EXECUTE orm_create_oe_field_meaning 0129, "SURGDIAGNOSIS", "Surg Diagnosis"
 EXECUTE orm_create_oe_field_meaning 0130, "ANESTHESIAPRSNLID", "Anesthesia Personnel Id"
 EXECUTE orm_create_oe_field_meaning 0131, "SURGADDON", "Surg Add On"
 EXECUTE orm_create_oe_field_meaning 0132, "CPTMODIFIER", "CPT Modifier"
 EXECUTE orm_create_oe_field_meaning 0133, "DISCERNORDDOC", "Discern Ordering Physician"
 EXECUTE orm_create_oe_field_meaning 0134, "SUSPPATHOGENS", "Suspected Pathogens"
 EXECUTE orm_create_oe_field_meaning 0135, "MEDIALBLPTR", "Media Label Printer"
 EXECUTE orm_create_oe_field_meaning 0136, "PRTMEDIALBLYN", "Print Media Label Y/N"
 EXECUTE orm_create_oe_field_meaning 0137, "OVERRIDESHARE", "Override Share Y/N"
 EXECUTE orm_create_oe_field_meaning 0201, "REASONFORCONSULT", "Reason for Consult"
 EXECUTE orm_create_oe_field_meaning 0202, "STARTMEAL", "Start Meal"
 EXECUTE orm_create_oe_field_meaning 0203, "DIETARYMODIFIERS", "Dietary Modifiers"
 EXECUTE orm_create_oe_field_meaning 0204, "BEVERAGEMODIFIERS", "Beverage Modifiers"
 EXECUTE orm_create_oe_field_meaning 0205, "DIETARYRESTRICTIONS", "Dietary Restrictions"
 EXECUTE orm_create_oe_field_meaning 0206, "DIETARYCALORIES", "Dietary Calories"
 EXECUTE orm_create_oe_field_meaning 0207, "DIETARYFLUIDPERMITTED", "Dietary Fluid Permitted"
 EXECUTE orm_create_oe_field_meaning 0208, "TOTALFLUIDPERMITTED", "Total Fluid Permitted"
 EXECUTE orm_create_oe_field_meaning 0209, "FLUIDRESTRICTIONINTERVAL", "Fluid Restriction Interval"
 EXECUTE orm_create_oe_field_meaning 0210, "DIETARYSODIUM", "Dietary Sodium"
 EXECUTE orm_create_oe_field_meaning 0211, "DIETARYFAT", "Dietary Fat"
 EXECUTE orm_create_oe_field_meaning 0212, "DIETARYPOTTASIUM", "Dietary Potassium"
 EXECUTE orm_create_oe_field_meaning 0213, "DIETARYPROTEIN", "Dietary Protein"
 EXECUTE orm_create_oe_field_meaning 0214, "NPOEXCEPTION", "NPO Exception"
 EXECUTE orm_create_oe_field_meaning 0215, "DIETARYSUPP", "Dietary Supplements"
 EXECUTE orm_create_oe_field_meaning 0216, "DIETARYSNACKS", "Dietary Snacks"
 EXECUTE orm_create_oe_field_meaning 0217, "PEDIATRICFORMULA", "Pediatric Formula"
 EXECUTE orm_create_oe_field_meaning 0218, "NUTRITIONALROUTE", "Nutritional Route"
 EXECUTE orm_create_oe_field_meaning 0219, "DIETARYFORT/ADD", "Dietary Fortifier/Additive"
 EXECUTE orm_create_oe_field_meaning 0220, "ACTIVITYASSLEVEL", "Activity Assistance Level"
 EXECUTE orm_create_oe_field_meaning 0221, "VENTILATORRATE", "Ventilator Rate"
 EXECUTE orm_create_oe_field_meaning 1103, "SPECINX", "Special Instructions"
 EXECUTE orm_create_oe_field_meaning 1105, "CANCELREASON", "Cancel Reason"
 EXECUTE orm_create_oe_field_meaning 1107, "SUSPENDREASON", "Suspend Reason"
 EXECUTE orm_create_oe_field_meaning 1108, "NURSECOLLECT", "Nurse Collect"
 EXECUTE orm_create_oe_field_meaning 1110, "RESUMEREASON", "Resume Reason"
 EXECUTE orm_create_oe_field_meaning 1112, "DCREASON", "Discontinue Reason"
 EXECUTE orm_create_oe_field_meaning 1113, "REVIEWLOCATION", "Review Location"
 EXECUTE orm_create_oe_field_meaning 1114, "REVIEWPROVIDER", "Review Provider"
 EXECUTE orm_create_oe_field_meaning 1115, "COSIGNPROVIDER", "Cosign Provider"
 EXECUTE orm_create_oe_field_meaning 1118, "TITRATEINX", "Titrate Instructions"
 EXECUTE orm_create_oe_field_meaning 1119, "TAKEHOMEMED", "Take Home Med"
 EXECUTE orm_create_oe_field_meaning 1120, "TAKEHOMEQTY", "Take Home Quantity"
 EXECUTE orm_create_oe_field_meaning 1124, "SPECIMENDESC", "Specimen Description"
 EXECUTE orm_create_oe_field_meaning 1125, "SPECPRECAUTION", "Specimen Precautions"
 EXECUTE orm_create_oe_field_meaning 1126, "CHARGESTARTDTTM", "Charge Interval Start Date/Time"
 EXECUTE orm_create_oe_field_meaning 1127, "CHARGESTOPDTTM", "Charge Interval Stop Date/Time"
 EXECUTE orm_create_oe_field_meaning 1500, "TRANSPORTMODE", "Transport Mode"
 EXECUTE orm_create_oe_field_meaning 1501, "REASONFOREXAM", "Reason For Exam"
 EXECUTE orm_create_oe_field_meaning 1550, "LASTREFILLDTTM", "Last Refill Dt Tm"
 EXECUTE orm_create_oe_field_meaning 1551, "REFILLSREMAINING", "Refills Remaining"
 EXECUTE orm_create_oe_field_meaning 1552, "QUANTITYONHAND", "Quantity On Hand"
 EXECUTE orm_create_oe_field_meaning 1557, "ADDITIONALREFILLS", "Additional Refills"
 EXECUTE orm_create_oe_field_meaning 1558, "TOTALREFILLS", "Total Refills"
 EXECUTE orm_create_oe_field_meaning 1559, "RXEXPIREDDATE", "Rx Expired Date"
 EXECUTE orm_create_oe_field_meaning 1560, "REQREFILLDATE", "Requested Refill Date"
 EXECUTE orm_create_oe_field_meaning 1561, "ORIGORDERID", "Original Order Id"
 EXECUTE orm_create_oe_field_meaning 2005, "COMPONENTCOST", "Component Cost"
 EXECUTE orm_create_oe_field_meaning 2006, "DISPENSEFROMLOC", "Dispense From Location"
 EXECUTE orm_create_oe_field_meaning 2007, "DISPENSECATEGORY", "Dispense Category"
 EXECUTE orm_create_oe_field_meaning 2008, "COMPONENTDISPENSECATEGORY", "Component Dispense Category"
 EXECUTE orm_create_oe_field_meaning 2011, "FREQ", "Frequency"
 EXECUTE orm_create_oe_field_meaning 2012, "COMPONENTFREQ", "Component Frequency"
 EXECUTE orm_create_oe_field_meaning 2014, "DRUGFORM", "Drug Form"
 EXECUTE orm_create_oe_field_meaning 2015, "DISPENSEQTY", "Dispense Quantity"
 EXECUTE orm_create_oe_field_meaning 2016, "REFILLQTY", "Refill Quantity"
 EXECUTE orm_create_oe_field_meaning 2017, "DAW", "DAW"
 EXECUTE orm_create_oe_field_meaning 2018, "SAMPLESGIVEN", "Samples Given"
 EXECUTE orm_create_oe_field_meaning 2019, "SAMPLEQTY", "Samply Quantity"
 EXECUTE orm_create_oe_field_meaning 2020, "NORFLALLD", "No Refills Allowed"
 EXECUTE orm_create_oe_field_meaning 2021, "SIG", "SIG"
 EXECUTE orm_create_oe_field_meaning 2022, "RXQTY", "Rx Quantity"
 EXECUTE orm_create_oe_field_meaning 2023, "ABNSTATUS", "ABN Status"
 EXECUTE orm_create_oe_field_meaning 2024, "NEXTDISPENSEDTTM", "Next Dispense Date/Time"
 EXECUTE orm_create_oe_field_meaning 2037, "SCH/PRN", "Scheduled / PRN"
 EXECUTE orm_create_oe_field_meaning 2043, "RATE", "Rate"
 EXECUTE orm_create_oe_field_meaning 2044, "RATEUNIT", "Rate Unit"
 EXECUTE orm_create_oe_field_meaning 2045, "COLLECTIONROUTE", "Collection Route"
 EXECUTE orm_create_oe_field_meaning 2047, "STARTBAG", "Start Bag"
 EXECUTE orm_create_oe_field_meaning 2048, "COMPONENTSTARTBAG", "Component Start Bag"
 EXECUTE orm_create_oe_field_meaning 2050, "RXROUTE", "Route Of Administration"
 EXECUTE orm_create_oe_field_meaning 2053, "STOPBAG", "Stop Bag"
 EXECUTE orm_create_oe_field_meaning 2055, "STOPTYPE", "Stop Type"
 EXECUTE orm_create_oe_field_meaning 2056, "STRENGTHDOSE", "Strength Dose"
 EXECUTE orm_create_oe_field_meaning 2057, "STRENGTHDOSEUNIT", "Strength Dose Unit"
 EXECUTE orm_create_oe_field_meaning 2058, "VOLUMEDOSE", "Volume Dose"
 EXECUTE orm_create_oe_field_meaning 2059, "VOLUMEDOSEUNIT", "Volume Dose Unit"
 EXECUTE orm_create_oe_field_meaning 2060, "TOTALVOLUME", "Total Volume"
 EXECUTE orm_create_oe_field_meaning 2061, "DURATION", "Duration"
 EXECUTE orm_create_oe_field_meaning 2062, "DURATIONUNIT", "Duration Unit"
 EXECUTE orm_create_oe_field_meaning 2063, "FREETXTDOSE", "Freetext Dose"
 EXECUTE orm_create_oe_field_meaning 2064, "INFUSEOVERUNIT", "Infuse Over Unit"
 EXECUTE orm_create_oe_field_meaning 2065, "DILUENTID", "Diluent Id"
 EXECUTE orm_create_oe_field_meaning 2066, "DILUENTVOLUME", "Diluent Volume"
 EXECUTE orm_create_oe_field_meaning 2067, "PARDOSES", "PAR Doses"
 EXECUTE orm_create_oe_field_meaning 2068, "REPLACEEVERY", "Replace Every"
 EXECUTE orm_create_oe_field_meaning 2069, "REPLACEEVERYUNIT", "Replace Every Unit"
 EXECUTE orm_create_oe_field_meaning 2070, "PHARMORDERTYPE", "Pharmacy Order Type"
 EXECUTE orm_create_oe_field_meaning 2071, "ADHOCFREQINSTANCE", "Adhoc Frequency Instance"
 EXECUTE orm_create_oe_field_meaning 2072, "PRICESCHEDULE", "Price Schedule"
 EXECUTE orm_create_oe_field_meaning 2073, "STOPDTTM", "Stop Date/Time"
 EXECUTE orm_create_oe_field_meaning 2074, "DCDISPLAYDAYS", "DC Display Days"
 EXECUTE orm_create_oe_field_meaning 2076, "TOTALDISPENSEDOSES", "Total Dispense Doses"
 EXECUTE orm_create_oe_field_meaning 2077, "PRINTIND", "Print Indicator"
 EXECUTE orm_create_oe_field_meaning 2078, "TITRATEIND", "Titrate Indicator"
 EXECUTE orm_create_oe_field_meaning 2079, "IVSEQ", "IV Seq"
 EXECUTE orm_create_oe_field_meaning 2080, "NBROFBAGS", "Number of bags in IV seq"
 EXECUTE orm_create_oe_field_meaning 2081, "IVNEXTSEQ", "Next IV Sequence"
 EXECUTE orm_create_oe_field_meaning 2082, "ORDERPRICE", "Order Price"
 EXECUTE orm_create_oe_field_meaning 2083, "ORDERCOST", "Order Cost"
 EXECUTE orm_create_oe_field_meaning 2084, "PASSMEDIND", "Pass Medication Indicator"
 EXECUTE orm_create_oe_field_meaning 2089, "FLOORSTOCKIND", "Floor Stock Indicator"
 EXECUTE orm_create_oe_field_meaning 2090, "FSOVERRIDE", "FS Override"
 EXECUTE orm_create_oe_field_meaning 2091, "DOSEQTY", "Dose Quantity"
 EXECUTE orm_create_oe_field_meaning 2092, "DOSEQTYUNIT", "Dose Quantity Unit"
 EXECUTE orm_create_oe_field_meaning 2093, "WRITEORDDISP", "Write Order Dispense Flag"
 EXECUTE orm_create_oe_field_meaning 2094, "FREQSCHEDID", "Frequency Schedule Id"
 EXECUTE orm_create_oe_field_meaning 2095, "DISPLAYONLYFREQ", "Display Only Frequency"
 EXECUTE orm_create_oe_field_meaning 2096, "NEXTDOSEDTTM", "Next Dose Dt Tm"
 EXECUTE orm_create_oe_field_meaning 2097, "DIFFINMIN", "Difference in Minutes"
 EXECUTE orm_create_oe_field_meaning 2098, "IVSETSHELLITEMID", "IV Set Shell Item Id"
 EXECUTE orm_create_oe_field_meaning 2099, "INITOVERRIDE", "Initial Dose Override"
 EXECUTE orm_create_oe_field_meaning 2100, "DRUGFORMULATION", "Drug Formulation"
 EXECUTE orm_create_oe_field_meaning 2101, "PRNINSTRUCTIONS", "PRN Instructions"
 EXECUTE orm_create_oe_field_meaning 2102, "DISPENSEQTYUNIT", "Dispense Quantity Unit"
 EXECUTE orm_create_oe_field_meaning 2103, "SAMPLEQTYUNIT", "Sample Quantity Unit"
 EXECUTE orm_create_oe_field_meaning 2104, "FREETEXTRATE", "Freetext Rate"
 EXECUTE orm_create_oe_field_meaning 2105, "DONTPRINTRXREASON", "Don't Print Rx Reason"
 EXECUTE orm_create_oe_field_meaning 2106, "PHYSICIAN ADDRESS", "Physician Address"
 EXECUTE orm_create_oe_field_meaning 2107, "PRINTDEANUMBER", "Print DEA Number"
 EXECUTE orm_create_oe_field_meaning 2108, "PHYSICIANADDRESSID", "Physician Address Id"
 EXECUTE orm_create_oe_field_meaning 3100, "DIETTYPE", "Diet Type"
 EXECUTE orm_create_oe_field_meaning 3200, "ACTIVITYTYPE", "Activity Type"
 EXECUTE orm_create_oe_field_meaning 3300, "ANESTHESIATYPE", "Anesthesia Type"
 EXECUTE orm_create_oe_field_meaning 3301, "PRIMARYPROCEDURE", "Primary Procedure"
 EXECUTE orm_create_oe_field_meaning 3302, "SURGPROCDUR", "Surg Procedure Duration"
 EXECUTE orm_create_oe_field_meaning 3303, "SURGEON1", "Surgeon1"
 EXECUTE orm_create_oe_field_meaning 3304, "SURGEON2", "Surgeon2"
 EXECUTE orm_create_oe_field_meaning 3305, "SURGEON3", "Surgeon3"
 EXECUTE orm_create_oe_field_meaning 3306, "SURGSPECIALTY", "Surg Specialty"
 EXECUTE orm_create_oe_field_meaning 3307, "SURGPROCMODIFIER1", "Surg Process Modifier1"
 EXECUTE orm_create_oe_field_meaning 3308, "SURGPROCMODIFIER2", "Surg Process Modifier2"
 EXECUTE orm_create_oe_field_meaning 3309, "SURGPROCMODIFIER3", "Surg Process Modifier3"
 EXECUTE orm_create_oe_field_meaning 3310, "CONCURRENT", "Concurrent"
 EXECUTE orm_create_oe_field_meaning 3311, "SURGEON4", "Surgeon4"
 EXECUTE orm_create_oe_field_meaning 3312, "SURGEON5", "Surgical Resident"
 EXECUTE orm_create_oe_field_meaning 3313, "ANESTHESIA1", "Anesthesiologist"
 EXECUTE orm_create_oe_field_meaning 3314, "ANESTHESIA2", "Anesthesiologist - Other"
 EXECUTE orm_create_oe_field_meaning 3315, "ANESTHESIA3", "Anesthesia Resident"
 EXECUTE orm_create_oe_field_meaning 3316, "RNANES1", "Nurse Anesthetist"
 EXECUTE orm_create_oe_field_meaning 3317, "RNFA", "RN First Assistant"
 EXECUTE orm_create_oe_field_meaning 3318, "RNPRACT", "RN Practitioner"
 EXECUTE orm_create_oe_field_meaning 3319, "SURGSETUPDUR", "Surg Setup Duration"
 EXECUTE orm_create_oe_field_meaning 3320, "SURGCLEANUPDUR", "Surg Cleanup Duration"
 EXECUTE orm_create_oe_field_meaning 3321, "SURGPROCSEQ", "Surg Procedure Sequence"
 EXECUTE orm_create_oe_field_meaning 3322, "ANESTHESIA4", "CRNA"
 EXECUTE orm_create_oe_field_meaning 3323, "ANESTHESIA5", "Anesthesiologist Assistant"
 EXECUTE orm_create_oe_field_meaning 3324, "SCHORDPHYS", "Scheduling Ordering Physician"
 EXECUTE orm_create_oe_field_meaning 3325, "SCHORDTYPE", "Scheduling Order Type"
 EXECUTE orm_create_oe_field_meaning 3326, "SURGPROCTEXT", "Surgical Procedure Text"
 EXECUTE orm_create_oe_field_meaning 3327, "SURGARRIVALDUR", "Surg Arrival Duration"
 EXECUTE orm_create_oe_field_meaning 3328, "SURGRECOVERYDUR", "Surg Recovery Duration"
 EXECUTE orm_create_oe_field_meaning 3329, "SCHEDREQDATE", "Schedule on Requested Date"
 EXECUTE orm_create_oe_field_meaning 3350, "CALLBACKPHONEIND", "Callback Phone Ind"
 EXECUTE orm_create_oe_field_meaning 3351, "CALLBACKPHONENUM", "Callback Phone Number"
 EXECUTE orm_create_oe_field_meaning 3352, "CALLBACKEXTENSION", "Callback Extension"
 EXECUTE orm_create_oe_field_meaning 3353, "CALLBACKFAXIND", "Callback Fax Ind"
 EXECUTE orm_create_oe_field_meaning 3354, "CALLBACKFAXNUMBER", "Callback Fax Number"
 EXECUTE orm_create_oe_field_meaning 3355, "CALLBACKPHONEID", "Callback Phone Id"
 EXECUTE orm_create_oe_field_meaning 3356, "ABNREASON", "ABN Reason"
 EXECUTE orm_create_oe_field_meaning 3500, "CONSULTMEDSERVICE", "Consulting Med Service"
 EXECUTE orm_create_oe_field_meaning 6000, "SPECRECDDATETIME", "Specimen Received Date and Time"
 EXECUTE orm_create_oe_field_meaning 6001, "SPECRECDBY", "Specimen Received By"
 EXECUTE orm_create_oe_field_meaning 6002, "SPECRECDLOC", "Specimen Received Location"
 EXECUTE orm_create_oe_field_meaning 6003, "CONTAINERTYPE", "Container Type"
 EXECUTE orm_create_oe_field_meaning 6004, "CONTAINERVOL", "Container Volume"
 EXECUTE orm_create_oe_field_meaning 6005, "CONTAINERID", "Container Id"
 EXECUTE orm_create_oe_field_meaning 6006, "COLLECTEDYN", "Collected Y/N"
 EXECUTE orm_create_oe_field_meaning 6007, "PRINTLABELBYORDLOC", "Print Label By Order Location"
 EXECUTE orm_create_oe_field_meaning 9000, "OTHER", "User defined field"
 EXECUTE orm_create_oe_field_meaning 9001, "PROMPT", "Prompt Test"
 COMMIT
 SET readme_data->status = "S"
 EXECUTE dm_readme_status
END GO
