CREATE PROGRAM dm_atr_refresh_task_req:dba
 SET inhouse_ind = 0
 IF (trim(ref)="C")
  SET inhouse_ind = 1
 ENDIF
 SET readme_ind = validate(request->setup_proc[1].env_id,0.0)
 SET env = fillstring(20," ")
 IF (readme_ind > 0.0)
  SELECT INTO "nl:"
   de.environment_name
   FROM dm_environment de
   WHERE (de.environment_id=request->setup_proc[1].env_id)
   DETAIL
    env = de.environment_name
   WITH nocounter
  ;end select
 ELSE
  SELECT INTO "nl:"
   de.environment_name
   FROM dm_info di,
    dm_environment de
   WHERE di.info_name="DM_ENV_ID"
    AND di.info_domain="DATA MANAGEMENT"
    AND de.environment_id=di.info_number
   DETAIL
    env = de.environment_name
   WITH nocounter
  ;end select
 ENDIF
 FREE SET tr_list
 RECORD tr_list(
   1 count = i4
   1 tr[*]
     2 t_num = i4
     2 r_num = i4
     2 f_num = i4
     2 s_dt = dq8
 )
 SET tr_list->count = 0
 SET filename = "DM_ATR_REFRESH_TASK_REQ.DAT"
 SET temp = fillstring(255," ")
 SET feature_status = fillstring(20," ")
 SELECT INTO value(filename)
  FROM dual
  DETAIL
   "/* This file is generated by the ATR refresh process */", row + 1, "/* Environment: ",
   env, " */", row + 1
   IF (readme_ind > 0.0)
    IF (inhouse_ind=1)
     "/* This process was executed as a readme step in cert in-house */", row + 1
    ELSE
     "/* This process was executed as a readme step */", row + 1
    ENDIF
   ELSE
    "/* This process was executed to refresh ATRs in cert */", row + 1
   ENDIF
   "set trace noreflog go", row + 1
  WITH nocounter, maxrow = 1, maxcol = 512,
   format = variable, formfeed = none
 ;end select
 IF (inhouse_ind=1)
  SET feature_status = "('2B')"
 ELSE
  SET feature_status = "('5')"
 ENDIF
 CALL echo("Generating list of latest Task-Request relations...")
 SELECT INTO value(filename)
  *
  FROM dm_task_request_r d
  WHERE sqlpassthru(concat("(d.task_number,d.request_number,d.schema_date) in ",
    "(select dm.task_number, dm.request_number, max(dm.schema_date) from dm_task_request_r dm, dm_features df where 1=1"
    ))
   AND sqlpassthru(concat(" UPPER(df.feature_status) in ",trim(feature_status)," "))
   AND sqlpassthru(
   " dm.feature_number = df.feature_number group by dm.task_number, dm.request_number )")
  ORDER BY d.feature_number, d.task_number, d.request_number
  HEAD REPORT
   IF (readme_ind > 0.0)
    "/* Save readme request parameters */", row + 1,
    "set process_id = request->setup_proc[1]->process_id go",
    row + 1, "set env_id = request->setup_proc[1]->env_id go", row + 1,
    row + 1
   ELSE
    tr_list->count = 0, stat = alterlist(tr_list->tr,0)
   ENDIF
   "/* Now declare new request structue for program */", row + 1, "free set request go",
   row + 1, "record request (", row + 1,
   "  1 atr_count = i4", row + 1, "  1 atr_list[*]",
   row + 1, "    2 task_number = i4", row + 1,
   "    2 request_number = i4", row + 1, "    2 deleted_ind = i2",
   row + 1, "  1 feature_number = i4", row + 1,
   "  1 schema_date = dq8", row + 1, ") go",
   row + 1, "set request->atr_count = 0 go", row + 1,
   "set stat = alterlist(request->atr_list,0) go", row + 1, "set trace symbol mark go",
   row + 1, row + 1, atr_cnt = 0,
   "/* Now populate the new request request structure */"
  HEAD d.feature_number
   row + 1, row + 1, "/* Original feature number = ",
   d.feature_number, " */", row + 1
  DETAIL
   "set request->atr_count = request->atr_count + 1 go", row + 1,
   "set stat = alterlist(request->atr_list,request->atr_count) go",
   row + 1, "set request->feature_number = 0 go", row + 1,
   "set request->atr_list[request->atr_count]->task_number = ", d.task_number, " go",
   row + 1, "set request->atr_list[request->atr_count]->request_number = ", d.request_number,
   " go", row + 1, "set request->atr_list[request->atr_count]->deleted_ind = ",
   d.deleted_ind, " go", row + 1,
   "/* schema_date = ", d.schema_date"MM/DD/YYYY;;D", " */",
   row + 1
   IF (readme_ind=0.0)
    tr_list->count = (tr_list->count+ 1), stat = alterlist(tr_list->tr,tr_list->count), tr_list->tr[
    tr_list->count].t_num = d.task_number,
    tr_list->tr[tr_list->count].r_num = d.request_number, tr_list->tr[tr_list->count].f_num = d
    .feature_number, tr_list->tr[tr_list->count].s_dt = d.schema_date
   ENDIF
   atr_cnt = (atr_cnt+ 1)
   IF (atr_cnt=500)
    row + 1, row + 1, "/* Call the import script every 500th ATR */",
    row + 1, "execute dm_atr_task_req_import go", row + 1,
    "set trace symbol go", row + 1, "set request->atr_count = 0 go",
    row + 1, "set stat = alterlist(request->atr_list,0) go", row + 1,
    row + 1, atr_cnt = 0
   ENDIF
  FOOT REPORT
   row + 1, row + 1
   IF (atr_cnt > 0)
    "/* Now call the import script */", row + 1, "execute dm_atr_task_req_import go",
    row + 1, "set trace symbol go"
   ENDIF
   IF (readme_ind > 0.0)
    row + 1, row + 1,
    "/* Destroy program request structure and use readme request again for error checking */",
    row + 1, "free set request go", row + 1,
    "record request (", row + 1, "%i cer_install:dm_readme_request.inc",
    row + 1, ") go", row + 1,
    "set request->setup_proc[1]->process_id = process_id go", row + 1,
    "set request->setup_proc[1]->env_id = env_id go",
    row + 1, row + 1, "/* Now perform error checking for readme */",
    row + 1, "execute dm_atr_refresh_check go"
   ENDIF
  WITH nocounter, maxrow = 1, maxcol = 512,
   format = variable, formfeed = none, append
 ;end select
 IF (readme_ind=0.0)
  CALL echo("Updating ATR status for Task-Request Relations...")
  UPDATE  FROM dm_feature_task_req_env dm,
    (dummyt d  WITH seq = value(size(tr_list->tr,5)))
   SET dm.status = "1"
   PLAN (d)
    JOIN (dm
    WHERE dm.environment=env
     AND (dm.task_number=tr_list->tr[d.seq].t_num)
     AND (dm.request_number=tr_list->tr[d.seq].r_num)
     AND (((dm.feature_number=tr_list->tr[d.seq].f_num)) OR (datetimecmp(dm.schema_dt_tm,cnvtdatetime
     (format(tr_list->tr[d.seq].s_dt,"DD-MMM-YYYY;;D"))) <= 0)) )
  ;end update
  COMMIT
 ENDIF
END GO
