CREATE PROGRAM dm_cdba_synonym:dba
 PROMPT
  'Enter , IN QUOTES, the connect string for the synonyms (e.g. "admin1"): ' =  $1
 FREE SET robjects
 RECORD robjects(
   1 inhouse_flag = i2
   1 qual[*]
     2 object_name = c50
     2 include_connect_string = i4
     2 exist_flag = i4
 )
 SELECT INTO "nl:"
  FROM dm_info di
  WHERE di.info_domain="DATA MANAGEMENT"
   AND di.info_name="INHOUSE DOMAIN"
  DETAIL
   robjects->inhouse_flag = 1
  WITH nocounter
 ;end select
 SET count1 = 0
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_QUESTION                   ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_QUESTION               ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TABLE_DEPENDENCY           ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_CODE_SET                   ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_COLUMNS                    ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_COLUMNS_DOC                ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_COLUMN_DOMAIN_RELTN        ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_CODE_VALUE                 ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_CODE_VALUE_SET             ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_CODE_SET_EXTENSION         ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_CODE_VALUE_EXTENSION       ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_COMMON_DATA_FOUNDATION     ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_CODE_VALUE_ALIAS           ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_COMMON_COLUMN              ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_CONSTRAINTS                ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_CONS_COLUMNS               ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_DATA_MODEL_SECTION         ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_DISK_FARM                  ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENVIRONMENT                ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_CONTROL_FILES          ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_DB_CONFIG              ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_DISK_FARM              ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_FILES                  ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_FUNCTIONS              ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_INDEX                  ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_LOGGING                ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_PRIVILEDGES            ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_REDO_LOGS              ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_ROLLBACK_SEGMENTS      ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_TABLE                  ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_USER                   ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].include_connect_string = 1
 SET robjects->qual[count1].object_name = trim("DM_ENV_USER_FUNCTIONS         ")
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_USER_PRIVLEDGES        ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_FLAGS                      ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_FUNCTION_DEPENDENCIES      ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_FUNCTION_DM_SECTION_R      ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_INDEXES                    ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_INDEXES_DOC                ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_INDEX_COLUMNS              ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_OWNER                      ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_PRODUCT_FUNCTIONS          ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_PRODUCT_INDEX_RELTN        ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_PRODUCT_TABLE_RELTN        ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_RENAMED_COLS               ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_RENAMED_TBLS               ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SCHEMA_VERSION             ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SEQUENCES                  ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_CONFIG                ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_DB_CNTL_FILES         ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_DB_CONFIG             ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_DB_REDO_LOGS          ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_DB_ROLLBACK_SEGS      ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_DB_TS                 ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_DB_VERSION            ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_DISK_FARM             ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_FILE_DISK_RELTN       ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_INDEX_INFO            ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_TABLESPACE            ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_TABLESPACE_RELTN      ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_TABLE_INFO            ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_VERSION               ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_VER_DATA_DISKS        ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_VER_DBOBJ_DISKS       ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZING_LOG                 ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_STATIC_TABLESPACES         ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TABLES                     ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TABLESPACE                 ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TABLES_DOC                 ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_MIN_TSPACE_SIZE            ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TABLE_COLUMN_DOMAIN_RELTN  ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TABLE_LIST")
 SET robjects->qual[count1].include_connect_string = 0
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SEQ                 ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SETUP_PROCESS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SETUP_PROC_LOG")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("V500_EVENT_CODE")
 SET robjects->qual[count1].include_connect_string = 0
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("V500_EVENT_SET_CODE")
 SET robjects->qual[count1].include_connect_string = 0
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("V500_EVENT_SET_CANON")
 SET robjects->qual[count1].include_connect_string = 0
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("V500_EVENT_SET_EXPLODE")
 SET robjects->qual[count1].include_connect_string = 0
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("CODE_VALUE")
 SET robjects->qual[count1].include_connect_string = 0
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("CODE_VALUE_ALIAS")
 SET robjects->qual[count1].include_connect_string = 0
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("CODE_VALUE_OUTBOUND")
 SET robjects->qual[count1].include_connect_string = 0
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("ALIAS_POOL")
 SET robjects->qual[count1].include_connect_string = 0
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_HL7_DOC")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZING_STAT")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("TREND_SEGMENT")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("SPACE_OBJECTS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_MRG_CODESET_GRP            ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_MRG_TBL_GRP                ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_SIZE_ROWS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_VARIANCE_ROWS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_FEATURES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_FEATURE_CODE_SETS_ENV")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_FEATURE_TABLES_ENV")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DBA_ALERTMON_GROUPS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DBA_ALERTMON_PATHS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DBA_ALERTMON_PREVSTATUS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DBA_ALERTMON_PATHSERVICES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DBA_ALERTMON_ERRORS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DBA_SERVICE_TYPE")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DBA_SERVICE_TIME")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_PKT_SETUP_PROCESS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_PKT_SETUP_PROC_LOG")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_PKT_SETUP_PROC_HIST")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_PKT_COM_FILE_ENV")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("SPACE_FILES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("TREND_TABLESPACE")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("REF_REPORT_LOG")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("REF_REPORT_PARMS_LOG")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("REF_INSTANCE_ID")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("REF_RPT_PARM_XREF")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("REF_REPORT_PARMS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("REF_REPORTS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("SPACE_LOG")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_CLIENT_SIZE")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_CLIENT_OBJECT_SIZE")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_CLIENT_PARAMS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_REF_DOMAIN")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_REF_DOMAIN_GROUP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_REF_DOMAIN_R")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_REF_FILTER")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("REF_DBA_FREE_SPACE")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ALPHA_FEATURES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_TABLES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_COLUMNS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_CONSTRAINTS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_CONS_COLUMNS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_INDEXES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_INDEX_COLUMNS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_CODE_VALUE_SET")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_COMMON_DATA_FOUNDATION")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_CODE_VALUE")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_CODE_SET_EXTENSION")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_CODE_VALUE_ALIAS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_CODE_VALUE_EXTENSION")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ALPHA_FEATURES_ENV")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_OCD_FEATURES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_OCD_APPLICATION")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_OCD_TASK")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_OCD_REQUEST")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_OCD_APP_TASK_R")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_OCD_TASK_REQ_R")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_APPLICATION                  ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_APPLICATION_TASK             ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_APPLICATION_TASK_R           ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_REQUEST                      ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TASK_REQUEST_R               ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_FEATURE_APP_ENV          ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_FEATURE_TASK_ENV         ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_FEATURE_APP_TASK_ENV     ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_FEATURE_REQ_ENV              ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_FEATURE_TASK_REQ_ENV     ")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENVIRONMENT_SHIP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_CON_FILES_SHIP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_FILES_SHIP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_FUNCTIONS_SHIP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_INDEX_SHIP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_REDO_LOGS_SHIP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_ROLL_SEGS_SHIP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_TABLE_SHIP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("ST_REQUEST")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("ST_SCRIPT")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("ST_SCRIPT_TABLES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("ST_PLAN")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("ST_SCRIPT_STAT")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TEAM_USERS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_TABLES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_COLUMNS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_CONSTRAINTS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_CONS_COLUMNS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_INDEXES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_INDEX_COLUMNS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_CODE_VALUE_SET")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_COMMON_DATA_FOUNDATION")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_CODE_VALUE")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_CODE_SET_EXTENSION")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_CODE_VALUE_ALIAS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_CODE_VALUE_EXTENSION")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_DM_ONE_CODE_SET")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TEMP_AFD_TABLES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TEMP_AFD_COLUMNS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TEMP_AFD_CONSTRAINTS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TEMP_AFD_CONS_COLUMNS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TEMP_AFD_INDEXES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TEMP_AFD_INDEX_COLUMNS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ENV_RELTN")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_OCD_LOG")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_OCD_LOG_SHIP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFE_SHIP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_README_HIST_SHIP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_README")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_PURGE_TABLE")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_PURGE_TEMPLATE")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_ADM_PURGE_TOKEN")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_REQUEST_PROCESSING")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_TS_PRECEDENCE")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_AFD_CODE_VALUE_GROUP")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("DM_INSTALL_PLAN")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("SPACE_TABLESPACES")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("REF_USER_REPORT")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("REF_USER_REPORT_PARMS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("REF_REPORT_EVENT")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("REF_REPORT_EVENT_PARMS")
 SET robjects->qual[count1].include_connect_string = 1
 SET count1 = (count1+ 1)
 SET stat = alterlist(robjects->qual,count1)
 SET robjects->qual[count1].object_name = trim("REPORT_SEQUENCE")
 SET robjects->qual[count1].include_connect_string = 1
 CALL echo("Checking if synonyms already exist ...")
 CALL echo("")
 CALL echo("")
 SELECT INTO "nl:"
  FROM dba_synonyms a,
   (dummyt d  WITH seq = value(count1))
  PLAN (d)
   JOIN (a
   WHERE a.synonym_name=trim(robjects->qual[d.seq].object_name)
    AND a.owner="PUBLIC")
  DETAIL
   robjects->qual[d.seq].exist_flag = 1
  WITH counter
 ;end select
 CALL echo("Attempting to rebuild synonyms ...")
 CALL echo("")
 CALL echo("")
 FOR (x = 1 TO count1)
   IF (robjects->qual[x].exist_flag)
    CALL parser(concat("rdb drop public synonym ",trim(robjects->qual[x].object_name)," go"))
   ENDIF
   CALL parser(concat("rdb create public synonym ",trim(robjects->qual[x].object_name)))
   IF ((robjects->qual[x].include_connect_string=1))
    CALL parser(concat("for ",trim(robjects->qual[x].object_name),"@", $1," go"))
   ELSE
    CALL parser(concat("for ",trim(robjects->qual[x].object_name)," go"))
   ENDIF
 ENDFOR
 CALL echo("")
 CALL echo("")
 CALL echo("*** Finished rebuilding synonyms! ***")
 CALL echo("")
 CALL echo("")
END GO
