CREATE PROGRAM dm_del_cmb_exception:dba
 IF ( NOT (validate(readme_data,0)))
  FREE SET readme_data
  RECORD readme_data(
    1 ocd = i4
    1 readme_id = f8
    1 instance = i4
    1 readme_type = vc
    1 description = vc
    1 script = vc
    1 check_script = vc
    1 data_file = vc
    1 par_file = vc
    1 blocks = i4
    1 log_rowid = vc
    1 status = vc
    1 message = c255
    1 options = vc
    1 driver = vc
    1 batch_dt_tm = dq8
  )
 ENDIF
 DELETE  FROM dm_cmb_exception dce
  WHERE dce.child_entity IN ("ACCT_ADJ_RELTN", "ACCT_CHARGE_RELTN", "ACCT_CORSP_RELTN",
  "ACCT_ORG_RELTN", "ACCT_PAYMENT_RELTN",
  "ACCT_PERSON_RELTN", "ACT_ACT_RELTN", "AP_CASE_QUERY", "AP_DIAG_RPT_REVIEW", "AP_FOLDER_ENTITY",
  "AP_FT_EVENT", "AP_PREFIX_SPEC_PROTOCOL", "BLOB_REFERENCE", "CASE_DICTATION_STATUS",
  "CASE_SPECIMEN_ADDL_INFO",
  "CSM_LST_CONTACT", "DISPENSE_HX", "FILTER_INI", "FN_CUSTOM_INSTRUCT", "FN_FAVORITE_INSTRUCT",
  "GEL_BATCH", "GL_ACCOUNT_ALIAS", "GL_ACCT_FIELD_RELTN", "GL_ACCT_FIELD_RESULT",
  "GL_ACCT_UNIT_ALIAS",
  "GL_ACCT_UNIT_FLD_RELTN", "GL_ACCT_UNIT_FLD_RESULT", "GL_COMP_UNIT_FLD_RELTN",
  "GL_COMP_UNIT_FLD_RESULT", "GL_COMPANY_ALIAS",
  "GL_COMPANY_UNIT_ALIAS", "GL_INTERFACE", "INSTR_EVENT_LOG", "INTRAOP_COUNT_CONFIRM",
  "MIC_STAT_PROCESS",
  "MM_APPROVAL", "MM_APPROVAL_LOG", "MMC_ACTIVITY_LOG", "MMC_LOG_COLUMN_PREF", "ORDER_COMMENT",
  "PAT_ED_DOC_FOLLOWUP", "PE_TRANS_RELTN", "PERSON_HLA_AB_SCN_AUDIT", "PERSON_HLA_AB_SCREEN",
  "PERSON_HLA_EVENT",
  "PERSON_HLA_EVENT_AUDIT", "PERSON_HLA_TYPE", "PERSON_HLA_TYPE_AUDIT", "PERSON_HLA_XM",
  "PERSON_HLA_XM_AUDIT",
  "PERSON_NTWK_PRVDR", "PFT_FILE_ADJ_RELTN", "PFT_REPORT_INSTANCE", "PREF_CARD_CHANGE_PROPOSAL",
  "PROP_ORDER",
  "QC_COMMENT", "QC_RESULT", "QC_RESULT_EVENT", "RR_PERFORM_RESULT", "RR_RESULT_EVENT",
  "SUMMARY_SECTION", "SUMMARY_SHEET", "TRANS_BO_RELTN", "TRANS_BR_RELTN", "UPLOAD_USER",
  "CASE_REPORT", "PROCESSING_TASK", "HLA_AB_SCREEN_RESULT", "HLA_TYP_RES_TRAY", "HLA_XM_RES_TRAY",
  "FN_OMF_ENCNTR", "TRACKING_CHECKIN", "TRACKING_EVENT", "TRACKING_LOCATOR", "OMF_ENCNTR_ST",
  "OMF_SVC_CAT_HIST_ST", "OMF_WL_PRODUCTIVITY_ST", "SN_CHARGE_QUEUE", "SN_RPT_FILTER_GRP",
  "OMF_IC_CAND_ST")
   AND dce.operation_type="COMBINE"
   AND dce.parent_entity="PERSON"
   AND dce.script_name="NONE"
  WITH nocounter
 ;end delete
 SELECT INTO "nl:"
  FROM dm_cmb_exception dce
  WHERE dce.child_entity IN ("ACCT_ADJ_RELTN", "ACCT_CHARGE_RELTN", "ACCT_CORSP_RELTN",
  "ACCT_ORG_RELTN", "ACCT_PAYMENT_RELTN",
  "ACCT_PERSON_RELTN", "ACT_ACT_RELTN", "AP_CASE_QUERY", "AP_DIAG_RPT_REVIEW", "AP_FOLDER_ENTITY",
  "AP_FT_EVENT", "AP_PREFIX_SPEC_PROTOCOL", "BLOB_REFERENCE", "CASE_DICTATION_STATUS",
  "CASE_SPECIMEN_ADDL_INFO",
  "CSM_LST_CONTACT", "DISPENSE_HX", "FILTER_INI", "FN_CUSTOM_INSTRUCT", "FN_FAVORITE_INSTRUCT",
  "GEL_BATCH", "GL_ACCOUNT_ALIAS", "GL_ACCT_FIELD_RELTN", "GL_ACCT_FIELD_RESULT",
  "GL_ACCT_UNIT_ALIAS",
  "GL_ACCT_UNIT_FLD_RELTN", "GL_ACCT_UNIT_FLD_RESULT", "GL_COMP_UNIT_FLD_RELTN",
  "GL_COMP_UNIT_FLD_RESULT", "GL_COMPANY_ALIAS",
  "GL_COMPANY_UNIT_ALIAS", "GL_INTERFACE", "INSTR_EVENT_LOG", "INTRAOP_COUNT_CONFIRM",
  "MIC_STAT_PROCESS",
  "MM_APPROVAL", "MM_APPROVAL_LOG", "MMC_ACTIVITY_LOG", "MMC_LOG_COLUMN_PREF", "ORDER_COMMENT",
  "PAT_ED_DOC_FOLLOWUP", "PE_TRANS_RELTN", "PERSON_HLA_AB_SCN_AUDIT", "PERSON_HLA_AB_SCREEN",
  "PERSON_HLA_EVENT",
  "PERSON_HLA_EVENT_AUDIT", "PERSON_HLA_TYPE", "PERSON_HLA_TYPE_AUDIT", "PERSON_HLA_XM",
  "PERSON_HLA_XM_AUDIT",
  "PERSON_NTWK_PRVDR", "PFT_FILE_ADJ_RELTN", "PFT_REPORT_INSTANCE", "PREF_CARD_CHANGE_PROPOSAL",
  "PROP_ORDER",
  "QC_COMMENT", "QC_RESULT", "QC_RESULT_EVENT", "RR_PERFORM_RESULT", "RR_RESULT_EVENT",
  "SUMMARY_SECTION", "SUMMARY_SHEET", "TRANS_BO_RELTN", "TRANS_BR_RELTN", "UPLOAD_USER",
  "CASE_REPORT", "PROCESSING_TASK", "HLA_AB_SCREEN_RESULT", "HLA_TYP_RES_TRAY", "HLA_XM_RES_TRAY",
  "FN_OMF_ENCNTR", "TRACKING_CHECKIN", "TRACKING_EVENT", "TRACKING_LOCATOR", "OMF_ENCNTR_ST",
  "OMF_SVC_CAT_HIST_ST", "OMF_WL_PRODUCTIVITY_ST", "SN_CHARGE_QUEUE", "SN_RPT_FILTER_GRP",
  "OMF_IC_CAND_ST")
   AND dce.operation_type="COMBINE"
   AND dce.parent_entity="PERSON"
   AND dce.script_name="NONE"
  WITH nocounter
 ;end select
 IF (curqual=0)
  SET readme_data->status = "S"
  SET readme_data->message = "Rows on dm_cmb_exception were successfully deleted."
  COMMIT
 ELSE
  SET readme_data->status = "F"
  SET readme_data->message = "Error deleting rows from dm_cmb_exception."
  ROLLBACK
 ENDIF
 EXECUTE dm_readme_status
END GO
