CREATE PROGRAM dm_fix_prsnl_combine:dba
 EXECUTE dm_readme_import "dm_fix_prsnl_combine.csv", "dm_dm_cmb_exception_import", 100,
 0
 SELECT INTO "nl:"
  FROM dm_cmb_exception dce
  WHERE dce.child_entity IN ("ACCT_ADJ_RELTN", "ACCT_CHARGE_RELTN", "ACCT_CORSP_RELTN",
  "ACCT_ORG_RELTN", "ACCT_PAYMENT_RELTN",
  "ACCT_PERSON_RELTN", "ACT_ACT_RELTN", "AP_CASE_QUERY", "AP_DIAG_RPT_REVIEW", "AP_FOLDER_ENTITY",
  "AP_FT_EVENT", "AP_PREFIX_SPEC_PROTOCOL", "BLOB_REFERENCE", "CASE_DICTATION_STATUS",
  "CASE_SPECIMEN_ADDL_INFO",
  "CSM_LST_CONTACT", "DISPENSE_HX", "FILTER_INI", "FN_CUSTOM_INSTRUCT", "FN_FAVORITE_INSTRUCT",
  "GEL_BATCH", "GL_ACCOUNT_ALIAS", "GL_ACCT_FIELD_RELTN", "GL_ACCT_FIELD_RESULT",
  "GL_ACCT_UNIT_ALIAS",
  "GL_ACCT_UNIT_FLD_RELTN", "GL_ACCT_UNIT_FLD_RESULT", "GL_COMP_UNIT_FLD_RELTN",
  "GL_COMP_UNIT_FLD_RESULT", "GL_COMPANY_ALIAS",
  "GL_COMPANY_UNIT_ALIAS", "GL_INTERFACE", "INSTR_EVENT_LOG", "INTRAOP_COUNT_CONFIRM",
  "MIC_STAT_PROCESS",
  "MM_APPROVAL", "MM_APPROVAL_LOG", "MMC_ACTIVITY_LOG", "MMC_LOG_COLUMN_PREF", "ORDER_COMMENT",
  "PAT_ED_DOC_FOLLOWUP", "PE_TRANS_RELTN", "PERSON_HLA_AB_SCN_AUDIT", "PERSON_HLA_AB_SCREEN",
  "PERSON_HLA_EVENT",
  "PERSON_HLA_EVENT_AUDIT", "PERSON_HLA_TYPE", "PERSON_HLA_TYPE_AUDIT", "PERSON_HLA_XM",
  "PERSON_HLA_XM_AUDIT",
  "PERSON_NTWK_PRVDR", "PFT_FILE_ADJ_RELTN", "PFT_REPORT_INSTANCE", "PREF_CARD_CHANGE_PROPOSAL",
  "PROP_ORDER",
  "QC_COMMENT", "QC_RESULT", "QC_RESULT_EVENT", "RR_PERFORM_RESULT", "RR_RESULT_EVENT",
  "SUMMARY_SECTION", "SUMMARY_SHEET", "TRANS_BO_RELTN", "TRANS_BR_RELTN", "UPLOAD_USER",
  "CASE_REPORT", "PROCESSING_TASK", "HLA_AB_SCREEN_RESULT", "HLA_TYP_RES_TRAY", "HLA_XM_RES_TRAY",
  "FN_OMF_ENCNTR", "TRACKING_CHECKIN", "TRACKING_EVENT", "TRACKING_LOCATOR", "OMF_ENCNTR_ST",
  "OMF_SVC_CAT_HIST_ST", "OMF_WL_PRODUCTIVITY_ST", "SN_CHARGE_QUEUE", "SN_RPT_FILTER_GRP",
  "OMF_IC_CAND_ST")
   AND dce.operation_type="COMBINE"
   AND dce.parent_entity="PRSNL"
   AND dce.script_name="NONE"
  WITH nocounter
 ;end select
 IF (curqual=80)
  CALL echo("PRSNL rows successfully inserted into dm_cmb_exception.")
  COMMIT
 ELSE
  CALL echo("Error in loading dm_cmb_exception")
  ROLLBACK
  GO TO exit_script
 ENDIF
 DELETE  FROM dm_cmb_exception dce
  WHERE dce.child_entity IN ("ACCT_ADJ_RELTN", "ACCT_CHARGE_RELTN", "ACCT_CORSP_RELTN",
  "ACCT_ORG_RELTN", "ACCT_PAYMENT_RELTN",
  "ACCT_PERSON_RELTN", "ACT_ACT_RELTN", "AP_CASE_QUERY", "AP_DIAG_RPT_REVIEW", "AP_FOLDER_ENTITY",
  "AP_FT_EVENT", "AP_PREFIX_SPEC_PROTOCOL", "BLOB_REFERENCE", "CASE_DICTATION_STATUS",
  "CASE_SPECIMEN_ADDL_INFO",
  "CSM_LST_CONTACT", "DISPENSE_HX", "FILTER_INI", "FN_CUSTOM_INSTRUCT", "FN_FAVORITE_INSTRUCT",
  "GEL_BATCH", "GL_ACCOUNT_ALIAS", "GL_ACCT_FIELD_RELTN", "GL_ACCT_FIELD_RESULT",
  "GL_ACCT_UNIT_ALIAS",
  "GL_ACCT_UNIT_FLD_RELTN", "GL_ACCT_UNIT_FLD_RESULT", "GL_COMP_UNIT_FLD_RELTN",
  "GL_COMP_UNIT_FLD_RESULT", "GL_COMPANY_ALIAS",
  "GL_COMPANY_UNIT_ALIAS", "GL_INTERFACE", "INSTR_EVENT_LOG", "INTRAOP_COUNT_CONFIRM",
  "MIC_STAT_PROCESS",
  "MM_APPROVAL", "MM_APPROVAL_LOG", "MMC_ACTIVITY_LOG", "MMC_LOG_COLUMN_PREF", "ORDER_COMMENT",
  "PAT_ED_DOC_FOLLOWUP", "PE_TRANS_RELTN", "PERSON_HLA_AB_SCN_AUDIT", "PERSON_HLA_AB_SCREEN",
  "PERSON_HLA_EVENT",
  "PERSON_HLA_EVENT_AUDIT", "PERSON_HLA_TYPE", "PERSON_HLA_TYPE_AUDIT", "PERSON_HLA_XM",
  "PERSON_HLA_XM_AUDIT",
  "PERSON_NTWK_PRVDR", "PFT_FILE_ADJ_RELTN", "PFT_REPORT_INSTANCE", "PREF_CARD_CHANGE_PROPOSAL",
  "PROP_ORDER",
  "QC_COMMENT", "QC_RESULT", "QC_RESULT_EVENT", "RR_PERFORM_RESULT", "RR_RESULT_EVENT",
  "SUMMARY_SECTION", "SUMMARY_SHEET", "TRANS_BO_RELTN", "TRANS_BR_RELTN", "UPLOAD_USER",
  "CASE_REPORT", "PROCESSING_TASK", "HLA_AB_SCREEN_RESULT", "HLA_TYP_RES_TRAY", "HLA_XM_RES_TRAY",
  "FN_OMF_ENCNTR", "TRACKING_CHECKIN", "TRACKING_EVENT", "TRACKING_LOCATOR", "OMF_ENCNTR_ST",
  "OMF_SVC_CAT_HIST_ST", "OMF_WL_PRODUCTIVITY_ST", "SN_CHARGE_QUEUE", "SN_RPT_FILTER_GRP",
  "OMF_IC_CAND_ST")
   AND dce.operation_type="COMBINE"
   AND dce.parent_entity="PERSON"
   AND dce.script_name="NONE"
  WITH nocounter
 ;end delete
 SELECT INTO "nl:"
  FROM dm_cmb_exception dce
  WHERE dce.child_entity IN ("ACCT_ADJ_RELTN", "ACCT_CHARGE_RELTN", "ACCT_CORSP_RELTN",
  "ACCT_ORG_RELTN", "ACCT_PAYMENT_RELTN",
  "ACCT_PERSON_RELTN", "ACT_ACT_RELTN", "AP_CASE_QUERY", "AP_DIAG_RPT_REVIEW", "AP_FOLDER_ENTITY",
  "AP_FT_EVENT", "AP_PREFIX_SPEC_PROTOCOL", "BLOB_REFERENCE", "CASE_DICTATION_STATUS",
  "CASE_SPECIMEN_ADDL_INFO",
  "CSM_LST_CONTACT", "DISPENSE_HX", "FILTER_INI", "FN_CUSTOM_INSTRUCT", "FN_FAVORITE_INSTRUCT",
  "GEL_BATCH", "GL_ACCOUNT_ALIAS", "GL_ACCT_FIELD_RELTN", "GL_ACCT_FIELD_RESULT",
  "GL_ACCT_UNIT_ALIAS",
  "GL_ACCT_UNIT_FLD_RELTN", "GL_ACCT_UNIT_FLD_RESULT", "GL_COMP_UNIT_FLD_RELTN",
  "GL_COMP_UNIT_FLD_RESULT", "GL_COMPANY_ALIAS",
  "GL_COMPANY_UNIT_ALIAS", "GL_INTERFACE", "INSTR_EVENT_LOG", "INTRAOP_COUNT_CONFIRM",
  "MIC_STAT_PROCESS",
  "MM_APPROVAL", "MM_APPROVAL_LOG", "MMC_ACTIVITY_LOG", "MMC_LOG_COLUMN_PREF", "ORDER_COMMENT",
  "PAT_ED_DOC_FOLLOWUP", "PE_TRANS_RELTN", "PERSON_HLA_AB_SCN_AUDIT", "PERSON_HLA_AB_SCREEN",
  "PERSON_HLA_EVENT",
  "PERSON_HLA_EVENT_AUDIT", "PERSON_HLA_TYPE", "PERSON_HLA_TYPE_AUDIT", "PERSON_HLA_XM",
  "PERSON_HLA_XM_AUDIT",
  "PERSON_NTWK_PRVDR", "PFT_FILE_ADJ_RELTN", "PFT_REPORT_INSTANCE", "PREF_CARD_CHANGE_PROPOSAL",
  "PROP_ORDER",
  "QC_COMMENT", "QC_RESULT", "QC_RESULT_EVENT", "RR_PERFORM_RESULT", "RR_RESULT_EVENT",
  "SUMMARY_SECTION", "SUMMARY_SHEET", "TRANS_BO_RELTN", "TRANS_BR_RELTN", "UPLOAD_USER",
  "CASE_REPORT", "PROCESSING_TASK", "HLA_AB_SCREEN_RESULT", "HLA_TYP_RES_TRAY", "HLA_XM_RES_TRAY",
  "FN_OMF_ENCNTR", "TRACKING_CHECKIN", "TRACKING_EVENT", "TRACKING_LOCATOR", "OMF_ENCNTR_ST",
  "OMF_SVC_CAT_HIST_ST", "OMF_WL_PRODUCTIVITY_ST", "SN_CHARGE_QUEUE", "SN_RPT_FILTER_GRP",
  "OMF_IC_CAND_ST")
   AND dce.operation_type="COMBINE"
   AND dce.parent_entity="PERSON"
   AND dce.script_name="NONE"
  WITH nocounter
 ;end select
 IF (curqual=0)
  CALL echo("Rows on dm_cmb_exception were successfully deleted.")
  COMMIT
 ELSE
  CALL echo("Error deleting rows from dm_cmb_exception.")
  ROLLBACK
 ENDIF
#exit_script
END GO
