CREATE PROGRAM dm_fix_tspace:dba
 SET filename =  $1
 SET filename4 = concat( $1,"4.DAT")
 SET file_undo = "FIX_TSPACE_UNDO"
 SET file_undo4 = concat(file_undo,"4.DAT")
 SET t_factor = 500
 SET one_k = 1024
 SET block_size = 8192
 SELECT INTO value(file_undo)
  u.tablespace_name, u.initial_extent, u.next_extent
  FROM user_tablespaces u
  WHERE ((u.tablespace_name="D_*") OR (u.tablespace_name="I_*"))
  ORDER BY u.tablespace_name
  HEAD REPORT
   "/*", row + 1, " * This file is generated by dm_fix_tspace",
   row + 1, " * You can include this file in CCL to restore the", row + 1,
   " * default sizing parameters to their original values.", row + 1,
   " * Check for errors in file ccluserdir:",
   file_undo4, row + 1, " */",
   row + 1, row + 1, "%o ",
   file_undo4, row + 1, row + 1
  DETAIL
   initial_space = cnvtint((u.initial_extent/ one_k)), next_space = cnvtint((u.next_extent/ one_k)),
   "rdb alter tablespace ",
   u.tablespace_name, row + 1, "  default storage (initial ",
   initial_space, "K", row + 1,
   "                      next ", next_space, "K ) go",
   row + 1, row + 1
  FOOT REPORT
   row + 1, "%o"
  WITH format = stream, noheading, formfeed = none,
   maxcol = 512, maxrow = 1
 ;end select
 SELECT INTO "nl:"
  FROM v$parameter v
  WHERE v.name="db_block_size"
  DETAIL
   block_size = cnvtint(v.value)
  WITH nocounter
 ;end select
 SELECT INTO value(filename)
  ddf.tablespace_name, total_space = sum(ddf.bytes)
  FROM dba_data_files ddf
  WHERE ((ddf.tablespace_name="D_*") OR (ddf.tablespace_name="I_*"))
  GROUP BY ddf.tablespace_name
  HEAD REPORT
   "/*", row + 1, " * This file is generated by dm_fix_tspace",
   row + 1, " */", row + 1,
   row + 1, "%o ", filename4,
   row + 1, row + 1
  DETAIL
   initial_space = (cnvtint(((total_space/ t_factor)/ one_k))+ 1)
   IF ((initial_space < ((2 * block_size)/ one_k)))
    initial_space = cnvtint(((2 * block_size)/ one_k))
   ENDIF
   next_space = (cnvtint(((total_space/ t_factor)/ one_k))+ 1)
   IF ((next_space < ((2 * block_size)/ one_k)))
    next_space = cnvtint(((2 * block_size)/ one_k))
   ENDIF
   "; Modify tablespace ", ddf.tablespace_name, row + 1,
   "rdb alter tablespace ", ddf.tablespace_name, row + 1,
   "  default storage (initial ", initial_space, "K",
   row + 1, "                      next ", next_space,
   "K ) go", row + 1, row + 1
  FOOT REPORT
   row + 1, "%o"
  WITH format = stream, noheading, formfeed = none,
   maxcol = 512, maxrow = 1
 ;end select
END GO
