CREATE PROGRAM dm_local_admin_tables:dba
 CALL parser("rdb alter table DM_TABLES_DOC_LOCAL STORAGE(NEXT 80K) go")
 CALL parser("rdb alter table DM_COLUMNS_DOC_LOCAL STORAGE(NEXT 1200K) go")
 CALL parser("rdb alter index XPKDM_COLUMNS_DOC_LOCAL STORAGE(NEXT 300K) go")
 CALL parser("rdb truncate table DM_TABLES_DOC_LOCAL reuse storage go")
 CALL parser("rdb insert into DM_TABLES_DOC_LOCAL select * from dm_tables_doc go")
 CALL parser("commit go")
 CALL parser("rdb truncate table DM_COLUMNS_DOC_LOCAL reuse storage go")
 CALL parser("rdb insert into DM_COLUMNS_DOC_LOCAL select * from DM_COLUMNS_DOC ")
 CALL parser("where table_name BETWEEN 'AA*' AND 'HZ*' go")
 CALL parser("commit go ")
 CALL parser("rdb insert into DM_COLUMNS_DOC_LOCAL select * from DM_COLUMNS_DOC ")
 CALL parser("where table_name BETWEEN 'IA*' and 'OZ*' go ")
 CALL parser("commit go ")
 CALL parser("rdb insert into DM_COLUMNS_DOC_LOCAL select * from DM_COLUMNS_DOC ")
 CALL parser("where table_name BETWEEN 'PA*' and 'ZZ*' go ")
 CALL parser("commit go ")
 CALL parser("rdb truncate table DM_CODE_SET_LOCAL reuse storage go")
 CALL parser("rdb insert into DM_CODE_SET_LOCAL select * from dm_code_set go")
 CALL parser("commit go ")
END GO
