CREATE PROGRAM dm_resizing_temp:dba
 CALL parser("rdb alter table DM_RESIZING_TEMP drop constraint XPKDM_RESIZING_TEMP go")
 CALL parser("rdb drop table dm_resizing_temp go ")
 CALL parser("drop table dm_resizing_temp go     ")
 CALL parser("rdb create table dm_resizing_temp  ")
 CALL parser("(                                  ")
 CALL parser("   tablespace_name   varchar2(30), ")
 CALL parser("   owner             varchar2(20), ")
 CALL parser("   segment_name      varchar2(40), ")
 CALL parser("   segment_type      varchar2(20), ")
 CALL parser("   tblocks           number,       ")
 CALL parser("   tbytes            number,       ")
 CALL parser("   ublocks           number,       ")
 CALL parser("   ubytes            number,       ")
 CALL parser("   luefi             number,       ")
 CALL parser("   luebi             number,       ")
 CALL parser("   lub               number        ")
 CALL parser(") tablespace D_SYS_MGMT go         ")
 CALL echo("CREATE DM_RESIZING_TEMP")
 CALL parser("rdb alter table DM_RESIZING_TEMP                   ")
 CALL parser("   add constraint XPKDM_RESIZING_TEMP              ")
 CALL parser("   primary key                                     ")
 CALL parser("   ( tablespace_name, segment_name, segment_type ) ")
 CALL parser("using index tablespace I_SYS_MGMT go               ")
 CALL parser("oragen3 'DM_RESIZING_TEMP' go")
END GO
