CREATE PROGRAM dm_schema_diff:dba
 SET old_date =  $1
 SET new_date =  $2
 SELECT INTO dm_schema_diff
  d.seq
  FROM (dummyt d  WITH seq = 1)
  DETAIL
   "; NEW TABLES", row + 1, "select * from dual",
   row + 1, 'detail "The following list are NEW Tables", row+1 ', row + 1,
   "with nocounter ", row + 1, "go",
   row + 1, "rdb select ", row + 1,
   "  t2.table_name ", row + 1, "from",
   row + 1, "  dm_tables t2", row + 1,
   "where", row + 1, '  t2.table_name > " " and',
   row + 1, '  t2.schema_date = to_date("',  $2,
   '","MM/DD/YYYY") ', row + 1, "minus",
   row + 1, "select ", row + 1,
   "  t1.table_name ", row + 1, "from",
   row + 1, "  dm_tables t1", row + 1,
   "where", row + 1, '  t1.table_name > " " and',
   row + 1, '  t1.schema_date = to_date("',  $1,
   '","MM/DD/YYYY") ', row + 1, "go",
   row + 1, "; DELETED TABLES", row + 1,
   "select * from dual", row + 1, 'detail "The following list are DELETED Tables", row+1 ',
   row + 1, "with nocounter ", row + 1,
   "go", row + 1, "rdb select ",
   row + 1, "  t2.table_name ", row + 1,
   "from", row + 1, "  dm_tables t2",
   row + 1, "where", row + 1,
   '  t2.table_name > " " and', row + 1, '  t2.schema_date = to_date("',
    $1, '","MM/DD/YYYY") ', row + 1,
   "minus", row + 1, "select ",
   row + 1, "  t1.table_name ", row + 1,
   "from", row + 1, "  dm_tables t1",
   row + 1, "where", row + 1,
   '  t1.table_name > " " and', row + 1, '  t1.schema_date = to_date("',
    $2, '","MM/DD/YYYY") ', row + 1,
   "go", row + 1, "",
   row + 1, "; NEW TABLESPACES", row + 1,
   "select * from dual", row + 1, 'detail "The following list are NEW Table Tablespaces", row+1 ',
   row + 1, "with nocounter ", row + 1,
   "go", row + 1, "rdb select ",
   row + 1, "  t2.tablespace_name", row + 1,
   "from", row + 1, "  dm_tables t2",
   row + 1, "where", row + 1,
   '  t2.tablespace_name > " " and', row + 1, '  t2.schema_date = to_date("',
    $1, '","MM/DD/YYYY") ', row + 1,
   "group by t2.tablespace_name ", row + 1, "minus",
   row + 1, "select ", row + 1,
   "  t1.tablespace_name ", row + 1, "from",
   row + 1, "  dm_tables t1", row + 1,
   "where", row + 1, '  t1.tablespace_name > " " and',
   row + 1, '  t1.schema_date = to_date("',  $2,
   '","MM/DD/YYYY") ', row + 1, "group by t1.tablespace_name ",
   row + 1, "go", row + 1,
   "; DELETED TABLESPACES", row + 1, "select * from dual",
   row + 1, 'detail "The following list are DELETED Table Tablespaces", row+1 ', row + 1,
   "with nocounter ", row + 1, "go",
   row + 1, "rdb select ", row + 1,
   "  t2.tablespace_name ", row + 1, "from",
   row + 1, "  dm_tables t2", row + 1,
   "where", row + 1, '  t2.tablespace_name > " " and',
   row + 1, '  t2.schema_date = to_date("',  $2,
   '","MM/DD/YYYY") ', row + 1, "group by t2.tablespace_name",
   row + 1, "minus", row + 1,
   "select ", row + 1, "  t1.tablespace_name ",
   row + 1, "from", row + 1,
   "  dm_tables t1", row + 1, "where",
   row + 1, '  t1.tablespace_name > " " and', row + 1,
   '  t1.schema_date = to_date("',  $1, '","MM/DD/YYYY") ',
   row + 1, "group by t1.tablespace_name", row + 1,
   "go", row + 1, "",
   row + 1, "; NEW INDEX TABLESPACES", row + 1,
   "select * from dual", row + 1, 'detail "The following list are NEW Index Tablespaces", row+1 ',
   row + 1, "with nocounter ", row + 1,
   "go", row + 1, "rdb select ",
   row + 1, "  t2.tablespace_name", row + 1,
   "from", row + 1, "  dm_indexes t2",
   row + 1, "where", row + 1,
   '  t2.tablespace_name > " " and', row + 1, '  t2.schema_date = to_date("',
    $1, '","MM/DD/YYYY") ', row + 1,
   "group by t2.tablespace_name ", row + 1, "minus",
   row + 1, "select ", row + 1,
   "  t1.tablespace_name ", row + 1, "from",
   row + 1, "  dm_indexes t1", row + 1,
   "where", row + 1, '  t1.tablespace_name > " " and',
   row + 1, '  t1.schema_date = to_date("',  $2,
   '","MM/DD/YYYY") ', row + 1, "group by t1.tablespace_name ",
   row + 1, "go", row + 1,
   "; DELETED INDEX TABLESPACES", row + 1, "select * from dual",
   row + 1, 'detail "The following list are DELETED Index Tablespaces", row+1 ', row + 1,
   "with nocounter ", row + 1, "go",
   row + 1, "rdb select ", row + 1,
   "  t2.tablespace_name ", row + 1, "from",
   row + 1, "  dm_indexes t2", row + 1,
   "where", row + 1, '  t2.tablespace_name > " " and',
   row + 1, '  t2.schema_date = to_date("',  $2,
   '","MM/DD/YYYY") ', row + 1, "group by t2.tablespace_name",
   row + 1, "minus", row + 1,
   "select ", row + 1, "  t1.tablespace_name ",
   row + 1, "from", row + 1,
   "  dm_indexes t1", row + 1, "where",
   row + 1, '  t1.tablespace_name > " " and', row + 1,
   '  t1.schema_date = to_date("',  $1, '","MM/DD/YYYY") ',
   row + 1, "group by t1.tablespace_name", row + 1,
   "go", row + 1
  WITH nocounter
 ;end select
END GO
