CREATE PROGRAM dm_size_tables_csv:dba
 EXECUTE dm_create_csv "DM_SIZE_DB_VERSION@R7ADM1"
 EXECUTE dm_create_csv "DM_SIZE_DB_TS@R7ADM1"
 EXECUTE dm_create_csv "DM_SIZE_DB_REDO_LOGS@R7ADM1"
 EXECUTE dm_create_csv "DM_SIZE_DB_CONFIG@R7ADM1"
 EXECUTE dm_create_csv "DM_SIZE_DB_CNTL_FILES@R7ADM1"
 EXECUTE dm_create_csv "DM_SIZE_DB_ROLLBACK_SEGS@R7ADM1"
END GO
