CREATE PROGRAM dmd5
 SELECT
  table_name, column_name, data_type,
  data_length
  FROM user_tab_columns
  WHERE table_name IN ("ACR", "BILL_ONLY_PROC_RELTN", "BILL_ONLY_SUBSECT_RELTN", "BORROWER_LENDER",
  "BORROWING_ENTITY",
  "CODED_EXAM_REASON", "CRITIQUE_CODE_ASSIGNMENTS", "CRITIQUE_PRSNL", "EXAM_CRITIQUE_INFO",
  "EXAM_DATA",
  "EXAM_FOLDER", "EXAM_REASON", "EXAM_ROOM_LIB_GRP_RELTN", "FILM_EXAM", "FILM_USAGE",
  "FOLDER", "FOLDER_ALIAS", "FOREIGN_CONTENT", "FOREIGN_FOLDER", "ICLASS_PERSON_RELTN",
  "IMAGE_CLASS", "IMAGE_CLASS_TYPE", "IMAGE_HISTORY", "LIBRARY_GROUP", "LIB_GRP_RELTN",
  "MAMMO_BREAST_FIND", "MAMMO_FIND", "MAMMO_FIND_DETAIL", "MAMMO_FOLLOW_UP", "MAMMO_NOTIFICATION",
  "MAMMO_PROBLEM", "MAMMO_RISK", "MAMMO_STUDY", "MAMMO_STUDY_PRSNL", "MAMMO_USER_DEF",
  "MEDIA", "MEDIA_EXAM", "ORDER_RADIOLOGY", "PROXY_EXEMPTIONS", "PROXY_GROUP",
  "PULL_FOLDERS", "PULL_LIST", "PULL_LIST_CONTROLS", "PULL_ORD_SCHED", "PULL_TRANS_REQ",
  "RAD_ACR_CODES", "RAD_BILL_CATEGORIES", "RAD_DEF_SERV_RES", "RAD_EXAM", "RAD_EXAM_PRSNL",
  "RAD_EXAM_ROOM", "RAD_FILM_ADJUST", "RAD_FOLD_TRANS_RULE", "RAD_FOLLOW_UP_CONTROL",
  "RAD_FOLLOW_UP_DEFAULT",
  "RAD_FOLLOW_UP_PRINT_CTRL", "RAD_FOLLOW_UP_RECALL", "RAD_FOL_UP_FIELD", "RAD_FOREIGN_REQ_ITEMS",
  "RAD_IMAGE_SYS_CONTROLS",
  "RAD_INT_CASE", "RAD_LOAN_INFO", "RAD_LOAN_LETTER_CONTROLS", "RAD_LOAN_LETTER_SETTINGS",
  "RAD_PACKET",
  "RAD_PROCEDURE_ASSOC", "RAD_PROCEDURE_GROUP", "RAD_QUESTIONS", "RAD_REPORT", "RAD_REPORT_DETAIL",
  "RAD_REPORT_PRSNL", "RAD_REQUEST", "RAD_REQ_CONTROLS", "RAD_RESPONSES", "RAD_RES_INFO",
  "RAD_SYS_CONTROLS", "RAD_TEMPLATE_ASSOC", "RAD_TEMPLATE_GROUP", "RAD_TRANS_STATS",
  "REPLACE_GROUPING",
  "TEMPORARY_DETAILS", "TEMPORARY_EXAM", "TEMPORARY_FOLDER", "TRACKABLE_OBJECT", "TRACK_PT_LIBRARY",
  "TRANS_EXAM_EXCLUSIONS", "TRANS_FOLD_EXCLUSIONS")
  ORDER BY table_name, column_name
 ;end select
END GO
