CREATE PROGRAM dts_large_data_return:dba
 SET reply->text = concat(reply->text,"{\rtf1\ansi\ansicpg1252\uc1 \deff4\deflang1033\deflangfe1033")
 SET reply->text = concat(reply->text,"{\fonttbl{\f0\froman\fcharset0\fprq2{\*\panose ")
 SET reply->text = concat(reply->text,"02020603050405020304}Times New Roman;}{\f1\fswiss\fcharset0")
 SET reply->text = concat(reply->text,"\fprq2{\*\panose 020b0604020202020204}Arial;}")
 SET reply->text = concat(reply->text,"{\f4\froman\fcharset0\fprq2{\*\panose 02020603050405020304}")
 SET reply->text = concat(reply->text,"Times;}{\f34\froman\fcharset238\fprq2 Times New Roman CE;}{")
 SET reply->text = concat(reply->text,"\f35\froman\fcharset204\fprq2 Times New Roman Cyr;}{\f37")
 SET reply->text = concat(reply->text,"\froman\fcharset161\fprq2 Times New Roman Greek;}")
 SET reply->text = concat(reply->text,"{\f38\froman\fcharset162\fprq2 Times New Roman Tur;}{\f39")
 SET reply->text = concat(reply->text,"\froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f40")
 SET reply->text = concat(reply->text,"\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f41")
 SET reply->text = concat(reply->text,"\froman\fcharset186\fprq2 Times New Roman Baltic;}")
 SET reply->text = concat(reply->text,"{\f42\fswiss\fcharset238\fprq2 Arial CE;}{\f43\fswiss")
 SET reply->text = concat(reply->text,"\fcharset204\fprq2 Arial Cyr;}{\f45\fswiss\fcharset161\fprq2")
 SET reply->text = concat(reply->text," Arial Greek;}{\f46\fswiss\fcharset162\fprq2 Arial Tur;}{")
 SET reply->text = concat(reply->text,"\f47\fswiss\fcharset177\fprq2 Arial (Hebrew);}")
 SET reply->text = concat(reply->text,"{\f48\fswiss\fcharset178\fprq2 Arial (Arabic);}{\f49\fswiss")
 SET reply->text = concat(reply->text,"\fcharset186\fprq2 Arial Baltic;}{\f66\froman\fcharset238")
 SET reply->text = concat(reply->text,"\fprq2 Times CE;}{\f67\froman\fcharset204\fprq2 Times Cyr;}")
 SET reply->text = concat(reply->text,"{\f69\froman\fcharset161\fprq2 Times Greek;}")
 SET reply->text = concat(reply->text,"{\f70\froman\fcharset162\fprq2 Times Tur;}{\f71\froman")
 SET reply->text = concat(reply->text,"\fcharset177\fprq2 Times (Hebrew);}{\f72\froman")
 SET reply->text = concat(reply->text,"\fcharset178\fprq2 Times (Arabic);}{\f73\froman\fcharset186")
 SET reply->text = concat(reply->text,"\fprq2 Times Baltic;}}{\colortbl;\red0\green0\blue0;\red0")
 SET reply->text = concat(reply->text,"\green0\blue255;")
 SET reply->text = concat(reply->text,"\red0\green255\blue255;\red0\green255\blue0;\red255\green0")
 SET reply->text = concat(reply->text,"\blue255;\red255\green0\blue0;\red255\green255\blue0;")
 SET reply->text = concat(reply->text,"\red255\green255\blue255;\red0\green0\blue128;\red0")
 SET reply->text = concat(reply->text,"\green128\blue128;\red0\green128\blue0;\red128\green0")
 SET reply->text = concat(reply->text,"\blue128;\red128\green0\blue0;")
 SET reply->text = concat(reply->text,"\red128\green128\blue0;\red128\green128\blue128;\red192")
 SET reply->text = concat(reply->text,"\green192\blue192;}{\stylesheet{\ql \li0\ri0\widctlpar")
 SET reply->text = concat(reply->text,"\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 \f4")
 SET reply->text = concat(reply->text,"\fs24\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 ")
 SET reply->text = concat(reply->text,"\snext0 Normal;}{")
 SET reply->text = concat(reply->text,"\s3\ql \li0\ri0\sb240\sa60\keepn\widctlpar\aspalpha\aspnum")
 SET reply->text = concat(reply->text,"\faauto\adjustright\rin0\lin0\itap0 \b\f1\fs26\lang1033")
 SET reply->text = concat(reply->text,"\langfe1033\cgrid\langnp1033\langfenp1033 \sbasedon0 \snext0")
 SET reply->text = concat(reply->text," heading 3;}{\*\cs10 \additive Default Paragraph Font;}")
 SET reply->text = concat(reply->text,"}{\info")
 SET reply->text = concat(reply->text,"{\title This is my document text}{\author JS8262}{\operator ")
 SET reply->text = concat(reply->text,"JS8262}{\creatim\yr2003\mo5\dy13\hr14\min56}{\revtim")
 SET reply->text = concat(reply->text,
  "\yr2003\mo5\dy13\hr16\min23}{\version6}{\edmins3}{\nofpages18}")
 SET reply->text = concat(reply->text,
  "{\nofwords9800}{\nofchars55865}{\*\company Cerner Corporation}")
 SET reply->text = concat(reply->text,"{\nofcharsws68606}")
 SET reply->text = concat(reply->text,"{\vern8269}}\widowctrl\ftnbj\aenddoc\noxlattoyen\expshrtn")
 SET reply->text = concat(reply->text,
  "\noultrlspc\dntblnsbdb\nospaceforul\hyphcaps0\formshade\horzdoc")
 SET reply->text = concat(reply->text,"\dgmargin\dghspace180\dgvspace180\dghorigin1800\dgvorigin1440"
  )
 SET reply->text = concat(reply->text,"\dghshow1\dgvshow1")
 SET reply->text = concat(reply->text,
  "\jexpand\viewkind1\viewscale100\pgbrdrhead\pgbrdrfoot\splytwnine")
 SET reply->text = concat(reply->text,"\ftnlytwnine\htmautsp\nolnhtadjtbl\useltbaln\alntblind")
 SET reply->text = concat(reply->text,"\lytcalctblwd\lyttblrtgr\lnbrkrule \fet0\sectd \linex0\")
 SET reply->text = concat(reply->text,"endnhere\sectlinegrid360\sectdefaultcl {\*\pnseclvl1")
 SET reply->text = concat(reply->text,"\pnucrm\pnstart1\pnindent720\pnhang{\pntxta .}}{\*\pnseclvl2")
 SET reply->text = concat(reply->text,"\pnucltr\pnstart1\pnindent720\pnhang{\pntxta .}}{\*\pnseclvl3"
  )
 SET reply->text = concat(reply->text,"\pndec\pnstart1\pnindent720\pnhang{\pntxta .}}{\*\pnseclvl4")
 SET reply->text = concat(reply->text,"\pnlcltr\pnstart1\pnindent720\pnhang{\pntxta )}}{\*\pnseclvl5"
  )
 SET reply->text = concat(reply->text,"\pndec\pnstart1\pnindent720\pnhang{\pntxtb (}{\pntxta )}}{\*")
 SET reply->text = concat(reply->text,"\pnseclvl6\pnlcltr\pnstart1\pnindent720\pnhang{\pntxtb (}{")
 SET reply->text = concat(reply->text,"\pntxta )}}{\*\pnseclvl7\pnlcrm\pnstart1\pnindent720\pnhang")
 SET reply->text = concat(reply->text,"{\pntxtb (}{\pntxta )}}{\*\pnseclvl8\pnlcltr\pnstart1")
 SET reply->text = concat(reply->text,"\pnindent720\pnhang")
 SET reply->text = concat(reply->text,"{\pntxtb (}{\pntxta )}}{\*\pnseclvl9\pnlcrm\pnstart1")
 SET reply->text = concat(reply->text,
  "\pnindent720\pnhang{\pntxtb (}{\pntxta )}}\pard\plain \ql \li0")
 SET reply->text = concat(reply->text,"\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0")
 SET reply->text = concat(reply->text,"\itap0 \f4\fs24\lang1033\langfe1033\cgrid\langnp1033")
 SET reply->text = concat(reply->text,"\langfenp1033 {")
 SET reply->text = concat(reply->text,"THIS IS THE BEGINNING OF MY DOCUMENT")
 FOR (i = 1 TO 2000)
   SET reply->text = concat(reply->text,
    "\par This is my document text. This is my document text. This is my document text.")
 ENDFOR
 SET reply->text = concat(reply->text,"\par THIS IS THE END OF MY DOCUMENT. Go Jared2")
 SET reply->text = concat(reply->text,"\par }}")
END GO
