CREATE PROGRAM edw_create_fin_encounter:dba
 SELECT INTO value(fin_enc_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE cur_list_size > 0
  DETAIL
   record_cnt = (record_cnt+ 1), col 0,
   CALL print(trim(health_system_id)),
   v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].encounter_nk,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].encounter_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].fin_encounter_sk,16))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].account_sk,16))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].billing_entity_sk,16))),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].financial_account_ident,str_find,str_replace,3),
    3)), v_bar,
   CALL print(fin_encounter->qual[d.seq].adjustment_balance_amt), v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].adj_balance_credit_debit_flg,str_find,
     str_replace,3),3)),
   v_bar,
   CALL print(fin_encounter->qual[d.seq].applied_payment_balance_amt), v_bar,
   CALL print(fin_encounter->qual[d.seq].bad_debt_balance_amt), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].bad_debt_credit_debit_flg,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].bad_debt_dt_tm,0,
      cnvtdatetimeutc(fin_encounter->qual[d.seq].bad_debt_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].bad_debt_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].bad_debt_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].bad_debt_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(fin_encounter->qual[d.seq].total_balance_amt), v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].balance_debit_credit_flg,str_find,str_replace,3
     ),3)), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].bill_status_ref,16))),
   v_bar,
   CALL print(fin_encounter->qual[d.seq].total_charge_amt), v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].charge_debit_credit_flg,str_find,str_replace,3),
    3)), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].collection_letter_flg,16))),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].combined_into_fin_encounter_sk,16))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].consolidation_flg,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].
      cardiac_rehab_start_dt_tm,0,cnvtdatetimeutc(fin_encounter->qual[d.seq].
       cardiac_rehab_start_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].cardiac_rehab_start_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].cardiac_rehab_start_dt_tm,
     cnvtint(fin_encounter->qual[d.seq].cardiac_rehab_start_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].total_cardiac_rehab_visits,str_find,str_replace,
     3))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].disch_dt_tm,0,
      cnvtdatetimeutc(fin_encounter->qual[d.seq].disch_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].disch_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].disch_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].disch_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].dunning_hold_flg,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].dunning_flg,16))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].dunning_level_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].
      dunning_level_chg_dt_tm,0,cnvtdatetimeutc(fin_encounter->qual[d.seq].dunning_level_chg_dt_tm,3)
      ),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].dunning_level_chg_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].dunning_level_chg_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].dunning_level_chg_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].dunning_level_cnt,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].dunning_no_pay_cnt,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].dunning_pay_cnt,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].dunning_unacceptable_pay_cnt,str_find,
     str_replace,3),3)), v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].ext_collection_flg,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].financial_class_ref,16))),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].ontime_paid_off_flg,str_find,str_replace,3),3)),
   v_bar,
   CALL print(fin_encounter->qual[d.seq].ins_pending_balance_fwd_amt), v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].interim_billing_flg,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].
      last_adjustment_dt_tm,0,cnvtdatetimeutc(fin_encounter->qual[d.seq].last_adjustment_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].last_adjustment_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].last_adjustment_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].last_adjustment_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].last_charge_dt_tm,
      0,cnvtdatetimeutc(fin_encounter->qual[d.seq].last_charge_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].last_charge_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].last_charge_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].last_charge_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].last_claim_dt_tm,0,
      cnvtdatetimeutc(fin_encounter->qual[d.seq].last_claim_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].last_claim_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].last_claim_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].last_claim_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].
      last_patient_pay_dt_tm,0,cnvtdatetimeutc(fin_encounter->qual[d.seq].last_patient_pay_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].last_patient_pay_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].last_patient_pay_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].last_patient_pay_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].last_payment_dt_tm,
      0,cnvtdatetimeutc(fin_encounter->qual[d.seq].last_payment_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].last_payment_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].last_payment_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].last_payment_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].
      last_statement_dt_tm,0,cnvtdatetimeutc(fin_encounter->qual[d.seq].last_statement_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].last_statement_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].last_statement_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].last_statement_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].total_statement_cnt,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].
      orig_bill_submit_dt_tm,0,cnvtdatetimeutc(fin_encounter->qual[d.seq].orig_bill_submit_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].orig_bill_submit_tm_zn,16))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].orig_bill_submit_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].orig_bill_submit_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].
      orig_bill_transmit_dt_tm,0,cnvtdatetimeutc(fin_encounter->qual[d.seq].orig_bill_transmit_dt_tm,
       3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].orig_bill_transmit_tm_zn,16))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].orig_bill_transmit_dt_tm,cnvtint
     (fin_encounter->qual[d.seq].orig_bill_transmit_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].ot_start_dt_tm,0,
      cnvtdatetimeutc(fin_encounter->qual[d.seq].ot_start_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].ot_start_tm_zn,16))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].ot_start_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].ot_start_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].total_ot_visits,str_find,str_replace,3),3)),
   v_bar,
   CALL print(fin_encounter->qual[d.seq].pat_balance_carry_forward_amt),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].payment_plan_flg,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].payment_plan_status_ref,16))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].status_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].pt_start_dt_tm,0,
      cnvtdatetimeutc(fin_encounter->qual[d.seq].pt_start_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].pt_start_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].pt_start_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].pt_start_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].total_pt_visits,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].qualifier_ref,16))), v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].recur_bill_generated_flg,str_find,str_replace,3
     ),3)),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].recur_bill_ready_flg,str_find,str_replace,3),3)
   ), v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].recur_current_month_nbr,str_find,str_replace,3),
    3)), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].recur_current_year_nbr,16))),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].recur_flg,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].recur_seq,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].sent_to_collection_flg,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].slt_start_dt_tm,0,
      cnvtdatetimeutc(fin_encounter->qual[d.seq].slt_start_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].slt_start_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].slt_start_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].slt_start_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].total_slt_visits,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].unapplied_payment_balance_amt,str_find,
     str_replace,3),3)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].zero_balance_dt_tm,
      0,cnvtdatetimeutc(fin_encounter->qual[d.seq].zero_balance_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].zero_balance_tm_zn,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].zero_balance_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].zero_balance_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].primary_health_plan_hlthpln,16))),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].resp_health_plan_hlthpln,16))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].resp_health_plan_priority_seq,16))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].primary_hold_type_flg,16))),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].primary_hold_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].daily_charge_amt,16,4))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].daily_payment_amt,16,4))),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].daily_adjustment_amt,16,4))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].
      bill_transmission_dt_tm,0,cnvtdatetimeutc(fin_encounter->qual[d.seq].bill_transmission_dt_tm,3)
      ),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].bill_transmission_tm_zn,16))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(fin_encounter->qual[d.seq].bill_transmission_dt_tm,cnvtint(
      fin_encounter->qual[d.seq].bill_transmission_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].wkfw_queue_assigned_prsnl,16))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].wkfw_queue_spvsr_prsnl,16))),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].coding_prsnl,16))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].coding_spvsr_prsnl,16))), v_bar, "3",
   v_bar, extract_dt_tm_fmt, v_bar,
   "1", v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].recur_admin_dt_tm,
      0,cnvtdatetimeutc(fin_encounter->qual[d.seq].recur_admin_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].recur_admin_dt_tm,
      0,cnvtdatetimeutc(fin_encounter->qual[d.seq].recur_admin_dt_tm,2)),fin_encounter->qual[d.seq].
     fin_enc_tm_zn,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].recur_disch_dt_tm,
      0,cnvtdatetimeutc(fin_encounter->qual[d.seq].recur_disch_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].recur_disch_dt_tm,
      0,cnvtdatetimeutc(fin_encounter->qual[d.seq].recur_disch_dt_tm,2)),fin_encounter->qual[d.seq].
     fin_enc_tm_zn,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].fin_enc_tm_zn,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].src_updt_dt_tm,0,
      cnvtdatetimeutc(fin_encounter->qual[d.seq].src_updt_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].src_updt_dt_tm,0,
      cnvtdatetimeutc(fin_encounter->qual[d.seq].src_updt_dt_tm,2)),fin_encounter->qual[d.seq].
     fin_enc_tm_zn,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].last_billed_dt_tm,
      0,cnvtdatetimeutc(fin_encounter->qual[d.seq].last_billed_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].last_billed_dt_tm,
      0,cnvtdatetimeutc(fin_encounter->qual[d.seq].last_billed_dt_tm,2)),fin_encounter->qual[d.seq].
     fin_enc_tm_zn,"MM/DD/YYYY HH:mm:ss"))), v_bar, v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_encounter->qual[d.seq].last_payment_dt_tm,
      0,cnvtdatetimeutc(fin_encounter->qual[d.seq].last_payment_dt_tm,2)),fin_encounter->qual[d.seq].
     fin_enc_tm_zn,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(fin_encounter->qual[d.seq].total_adj_amount),
   v_bar,
   CALL print(fin_encounter->qual[d.seq].total_billed_amount), v_bar,
   CALL print(fin_encounter->qual[d.seq].total_paid_amount), v_bar,
   CALL print(trim(replace(fin_encounter->qual[d.seq].line_item_ident,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].revenue_ref,16))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].procedure_code,16))), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].total_units,16))),
   v_bar,
   CALL print(fin_encounter->qual[d.seq].total_charges), v_bar,
   CALL print(fin_encounter->qual[d.seq].total_charge_amt_group), v_bar,
   CALL print(fin_encounter->qual[d.seq].total_adj),
   v_bar,
   CALL print(fin_encounter->qual[d.seq].curr_amt_due), v_bar,
   CALL print(fin_encounter->qual[d.seq].total_pay_amt), v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].src_active_ind,16))),
   v_bar,
   CALL print(trim(cnvtstring(fin_encounter->qual[d.seq].statement_cycle_sk,16))), v_bar,
   row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 2500, maxrow = 1, append
 ;end select
END GO
