CREATE PROGRAM edw_create_vendor_item:dba
 SELECT INTO value(venditem_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE cur_list_size > 0
  DETAIL
   col 0,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(concat(trim(cnvtstring(edw_vendor->qual[d.seq].vendor_inst_sk,16)),"~",trim(cnvtstring(
      edw_vendor->qual[d.seq].vendor_site_sk,16)),"~",trim(cnvtstring(edw_vendor->qual[d.seq].item_sk,
      16)))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].vendor_inst_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].vendor_site_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].item_sk,16))), v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].vendor_disp,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].vendor_desc,str_find,str_replace,3))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].vendor_type_ref,16))), v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].vendor_type_disp,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].approved_vendor_status_ref,16))), v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].approved_vendor_status_disp,str_find,str_replace,3
     ))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].output_dest_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].logical_domain_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].min_order_cost,16))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].vendor_nbr,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].tax_payer_nbr,16))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].backorder_ind,16))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].consolidate_rqstn_ind,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].acknowledgement_ind,16))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].auto_commit_po_ind,16))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].auto_commit_receipt_ind,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].tax_exempt_ind,16))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].vendor_active_ind,16))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].vendor_active_type_ref,16))),
   v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].vendor_active_type_display,str_find,str_replace,3)
    )), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_vendor->qual[d.seq].vendor_active_dt_tm,0,
      cnvtdatetimeutc(edw_vendor->qual[d.seq].vendor_active_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].vendor_active_tm_zn,16))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_vendor->qual[d.seq].vendor_active_dt_tm,cnvtint(
      edw_vendor->qual[d.seq].vendor_active_tm_zn),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].vendor_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].vendor_price_schedule_sk,16))),
   v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].vendor_site_account_number,str_find,str_replace,3)
    )), v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].vendor_site_description,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].freight_terms_ref,16))),
   v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].freight_terms_disp,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].payment_terms_ref,16))), v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].payment_terms_disp,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].po_print_format_ref,16))), v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].po_print_format_disp,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].po_transmit_type_ref,16))),
   v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].po_transmit_type_disp,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].ship_via_ref,16))), v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].ship_via_disp,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].vendor_item_lead_time,16))), v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].vendor_item_lead_time_uom_ref,16))), v_bar,
   CALL print(trim(replace(edw_vendor->qual[d.seq].vendor_item_lead_time_uom_disp,str_find,
     str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(edw_vendor->qual[d.seq].price_review_ind,16))), v_bar,
   "3", v_bar, extract_dt_tm_fmt,
   v_bar, row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
END GO
