CREATE PROGRAM edw_create_wait_list:dba
 SELECT INTO value(wait_lst_extractfile)
  FROM (dummyt d  WITH seq = size(wait_list->qual,5))
  WHERE (((wait_list->qual[d.seq].wait_list_sk > 0)) OR ((wait_list->qual[d.seq].wait_list_sk=- (1))
  ))
  DETAIL
   record_cnt = (record_cnt+ 1), col 0,
   CALL print(trim(health_system_id)),
   v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(replace(wait_list->qual[d.seq].encounter_nk,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].encounter_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].wait_list_sk,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].
      adj_waiting_start_dt_tm,0,cnvtdatetimeutc(wait_list->qual[d.seq].adj_waiting_start_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].adj_wait_start_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].adj_waiting_start_dt_tm,cnvtint(
      wait_list->qual[d.seq].adj_wait_start_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].admit_booking_ref,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].admit_category_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].admit_decision_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].admit_decision_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].admit_decision_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].admit_decision_dt_tm,cnvtint(
      wait_list->qual[d.seq].admit_decision_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].admit_guaranteed_dt_tm,
      0,cnvtdatetimeutc(wait_list->qual[d.seq].admit_guaranteed_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].admit_guaranteed_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].admit_guaranteed_dt_tm,cnvtint(
      wait_list->qual[d.seq].admit_guaranteed_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].admit_offer_outcome_ref,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].admit_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].anesthetic_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].appointment_ref,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].appt_loc,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].appt_synonym_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].appt_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].attendance_ref,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].attenddoc_clin_service_ref,16))),
   v_bar,
   CALL print(build(wait_list->qual[d.seq].auto_blood_ind)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].change_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].change_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].change_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].change_dt_tm,cnvtint(wait_list->
      qual[d.seq].change_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].change_prsnl,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].wl_comment_long_text_sk,16))),
   v_bar,
   CALL print(trim(replace(wait_list->qual[d.seq].commissioner_reference_txt,str_find,str_replace,3),
    3)), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].decline_status_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].decline_status_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].decline_status_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].decline_status_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].decline_status_dt_tm,cnvtint(
      wait_list->qual[d.seq].decline_status_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].delay_status_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].delay_status_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].delay_status_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].delay_status_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].delay_status_dt_tm,cnvtint(wait_list
      ->qual[d.seq].delay_status_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].est_admit_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].est_admit_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].est_admit_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].est_admit_dt_tm,cnvtint(wait_list->
      qual[d.seq].est_admit_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].est_length_procedure_ref,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].financial_class_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].
      financial_class_eff_dt_tm,0,cnvtdatetimeutc(wait_list->qual[d.seq].financial_class_eff_dt_tm,3)
      ),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].financial_class_eff_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].financial_class_eff_dt_tm,cnvtint(
      wait_list->qual[d.seq].financial_class_eff_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].fnctnl_deficiency_cause_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].fnctnl_deficiency_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].last_dna_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].last_dna_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].last_dna_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].last_dna_dt_tm,cnvtint(wait_list->
      qual[d.seq].last_dna_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].patient_loc,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].management_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].operation_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].
      orig_request_rcvd_dt_tm,0,cnvtdatetimeutc(wait_list->qual[d.seq].orig_request_rcvd_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].orig_request_rcvd_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].orig_request_rcvd_dt_tm,cnvtint(
      wait_list->qual[d.seq].orig_request_rcvd_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(replace(wait_list->qual[d.seq].other_med_condition_txt,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].pend_acceptance_dt_tm,
      0,cnvtdatetimeutc(wait_list->qual[d.seq].pend_acceptance_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].pend_acceptance_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].pend_acceptance_dt_tm,cnvtint(
      wait_list->qual[d.seq].pend_acceptance_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].
      pend_notification_dt_tm,0,cnvtdatetimeutc(wait_list->qual[d.seq].pend_notification_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].pend_notification_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].pend_notification_dt_tm,cnvtint(
      wait_list->qual[d.seq].pend_notification_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].pend_place_priority_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].
      pend_place_priority_dt_tm,0,cnvtdatetimeutc(wait_list->qual[d.seq].pend_place_priority_dt_tm,3)
      ),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].pend_place_priority_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].pend_place_priority_dt_tm,cnvtint(
      wait_list->qual[d.seq].pend_place_priority_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].planned_admit_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].planned_admit_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].planned_admit_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].planned_admit_dt_tm,cnvtint(
      wait_list->qual[d.seq].planned_admit_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].planned_procedure_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].
      planned_procedure_dt_tm,0,cnvtdatetimeutc(wait_list->qual[d.seq].planned_procedure_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].planned_procedure_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].planned_procedure_dt_tm,cnvtint(
      wait_list->qual[d.seq].planned_procedure_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(build(wait_list->qual[d.seq].pre_admit_attend_ind)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].
      pre_admit_clin_appt_dt_tm,0,cnvtdatetimeutc(wait_list->qual[d.seq].pre_admit_clin_appt_dt_tm,3)
      ),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].pre_admit_clin_appt_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].pre_admit_clin_appt_dt_tm,cnvtint(
      wait_list->qual[d.seq].pre_admit_clin_appt_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].pre_prov_admit_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].pre_prov_admit_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].pre_prov_admit_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].pre_prov_admit_dt_tm,cnvtint(
      wait_list->qual[d.seq].pre_prov_admit_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].
      provisional_admit_dt_tm,0,cnvtdatetimeutc(wait_list->qual[d.seq].provisional_admit_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].provisional_admit_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].provisional_admit_dt_tm,cnvtint(
      wait_list->qual[d.seq].provisional_admit_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].reason_for_change_ref,16))),
   v_bar,
   CALL print(trim(replace(wait_list->qual[d.seq].reason_for_removal_txt,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].reason_for_removal_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].recommend_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].recommend_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].recommend_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].recommend_dt_tm,cnvtint(wait_list->
      qual[d.seq].recommend_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].referral_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].referral_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].referral_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].referral_dt_tm,cnvtint(wait_list->
      qual[d.seq].referral_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].referral_reason_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].referral_source_ref,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].referral_type_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].removal_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].removal_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].removal_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].removal_dt_tm,cnvtint(wait_list->
      qual[d.seq].removal_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].requested_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].requested_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].requested_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].requested_dt_tm,cnvtint(wait_list->
      qual[d.seq].requested_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].resource_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].sch_appointment_sk,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].schedule_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].schedule_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].schedule_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].schedule_dt_tm,cnvtint(wait_list->
      qual[d.seq].schedule_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].service_type_requested_ref,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].stand_by_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].status_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].status_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].status_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].status_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].status_dt_tm,cnvtint(wait_list->
      qual[d.seq].status_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].status_end_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].status_end_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].status_end_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].status_end_dt_tm,cnvtint(wait_list->
      qual[d.seq].status_end_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].status_review_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].status_review_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].status_review_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].status_review_dt_tm,cnvtint(
      wait_list->qual[d.seq].status_review_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].supra_service_request_ref,16))), v_bar,
   CALL print(build(wait_list->qual[d.seq].suspended_days)),
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].urgency_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].urgency_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].urgency_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].urgency_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].urgency_dt_tm,cnvtint(wait_list->
      qual[d.seq].urgency_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].waiting_end_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].waiting_end_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].waiting_end_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].waiting_end_dt_tm,cnvtint(wait_list
      ->qual[d.seq].waiting_end_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,wait_list->qual[d.seq].waiting_start_dt_tm,0,
      cnvtdatetimeutc(wait_list->qual[d.seq].waiting_start_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].waiting_start_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(wait_list->qual[d.seq].waiting_start_dt_tm,cnvtint(
      wait_list->qual[d.seq].waiting_start_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   "3", v_bar, extract_dt_tm_fmt,
   v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].active_ind,16))), v_bar,
   CALL print(trim(cnvtstring(wait_list->qual[d.seq].referral_sk))), v_bar,
   CALL print(trim(wait_list->qual[d.seq].wl_comment_long_text)),
   v_bar, row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
 SET script_version = "004 13/04/18 CG026914 575586"
END GO
