CREATE PROGRAM edw_create_fin_charges:dba
 SELECT INTO value(fin_charges_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE cur_list_size > 0
  DETAIL
   col 0,
   CALL print(trim(health_system_id)), v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].fin_encntr_sk,16))),
   v_bar,
   CALL print(trim(edw_charge->qual[d.seq].encounter_nk)), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].encntr_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].fin_charges_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].bill_item_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].charge_type_cd,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].abn_status_cd,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].activity_type_cd,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_charge->qual[d.seq].adjusted_dt_tm,0,
      cnvtdatetimeutc(edw_charge->qual[d.seq].adjusted_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].adjusted_tz))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_charge->qual[d.seq].adjusted_dt_tm,cnvtint(edw_charge->
      qual[d.seq].adjusted_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].alpha_nomen_id,16))), v_bar,
   CALL print(trim(replace(edw_charge->qual[d.seq].charge_description,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].cost_center_cd,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_charge->qual[d.seq].credited_dt_tm,0,
      cnvtdatetimeutc(edw_charge->qual[d.seq].credited_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].credited_tz))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_charge->qual[d.seq].credited_dt_tm,cnvtint(edw_charge->
      qual[d.seq].credited_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].department_cd,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].discount_amount,11,2))),
   v_bar,
   CALL print(trim(edw_charge->qual[d.seq].epsdt_ind)), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].gross_price,11,2))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].health_plan_id,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].institution_cd,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].item_copay,11,2))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].item_deductible_amt,11,2))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].item_extended_price,11,2))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].item_list_price,11,2))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].item_price,11,2))),
   v_bar,
   CALL print(build(edw_charge->qual[d.seq].item_quantity)), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].item_reimbursement,11,2))), v_bar,
   CALL print(build(edw_charge->qual[d.seq].manual_ind)),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].med_service_cd,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].order_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].ord_loc_cd,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].parent_charge_item_id,16))), v_bar,
   CALL print(build(edw_charge->qual[d.seq].patient_responsibility_flag)), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].payor_id,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].payor_type_cd,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].perf_loc_cd,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].perf_phys_id,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].posted_cd,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_charge->qual[d.seq].posted_dt_tm,0,
      cnvtdatetimeutc(edw_charge->qual[d.seq].posted_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].posted_tz))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_charge->qual[d.seq].posted_dt_tm,cnvtint(edw_charge->
      qual[d.seq].posted_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(build(edw_charge->qual[d.seq].process_flag)), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].ref_phys_id,16))),
   v_bar,
   CALL print(build(edw_charge->qual[d.seq].server_process_flag)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_charge->qual[d.seq].service_dt_tm,0,
      cnvtdatetimeutc(edw_charge->qual[d.seq].service_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].service_tz))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_charge->qual[d.seq].service_dt_tm,cnvtint(edw_charge->
      qual[d.seq].service_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_charge->qual[d.seq].start_dt_tm,0,
      cnvtdatetimeutc(edw_charge->qual[d.seq].start_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].start_tz))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_charge->qual[d.seq].start_dt_tm,cnvtint(edw_charge->
      qual[d.seq].start_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_charge->qual[d.seq].stop_dt_tm,0,
      cnvtdatetimeutc(edw_charge->qual[d.seq].stop_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"
     ))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].stop_tz))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_charge->qual[d.seq].stop_dt_tm,cnvtint(edw_charge->
      qual[d.seq].stop_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].tier_group_cd,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].verify_phys_id,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].updt_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].poster_supervisor_id,16))), v_bar,
   CALL print(trim(edw_charge->qual[d.seq].gl_account_sk)),
   v_bar,
   CALL print(trim(edw_charge->qual[d.seq].gl_rsp_unit_sk)), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].total_charge_amount,11,2))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_charge->qual[d.seq].gl_interface_dt_tm,0,
      cnvtdatetimeutc(edw_charge->qual[d.seq].gl_interface_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].gl_interface_tz))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_charge->qual[d.seq].gl_interface_dt_tm,cnvtint(
      edw_charge->qual[d.seq].gl_interface_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].hcpcs_nomen_id,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].cpt_nomen_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].icd9_nomen_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].revenue_code,16))),
   v_bar,
   CALL print(trim(replace(edw_charge->qual[d.seq].cdm_code,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].billing_amount,11,2))), v_bar,
   CALL print(build(edw_charge->qual[d.seq].billing_quantity)),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].billing_entity_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].client_org_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].collection_priority_cd,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].cr_acct_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].dr_acct_id,16))), v_bar,
   CALL print(build(edw_charge->qual[d.seq].late_chrg_flag)),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].pft_charge_status_cd,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].pft_charge_status_reason_cd,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].interface_file_id,16))),
   v_bar, "3", v_bar,
   extract_dt_tm_fmt, v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].charge_active_ind,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].charge_event_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].cdm_nomen_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].credit_nomen_id,16))),
   v_bar,
   CALL print(trim(replace(edw_charge->qual[d.seq].credit_note_txt,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].credit_reason,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].credit_prsnl,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].fin_class_cd,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].ord_phys_id,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_charge->qual[d.seq].activity_dt_tm,0,
      cnvtdatetimeutc(edw_charge->qual[d.seq].activity_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].activity_tz))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_charge->qual[d.seq].activity_dt_tm,cnvtint(edw_charge->
      qual[d.seq].activity_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].hcpcs_charge_mod_id,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].cpt_charge_mod_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].icd9_charge_mod_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].cdm_charge_mod_id,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].credit_charge_mod_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].price_sched_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].activity_id,16))),
   v_bar,
   CALL print(trim(replace(edw_charge->qual[d.seq].cdm_code_desc,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(replace(edw_charge->qual[d.seq].ndc,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].icd10_nomen_id,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].icd10_charge_mod_id,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].offset_ind,16))), v_bar,
   CALL print(trim(cnvtstring(edw_charge->qual[d.seq].pft_charge_id,16))),
   v_bar, row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
 SET script_version = "011 02/06/18 mf025696"
END GO
