CREATE PROGRAM edw_create_hm_recommend:dba
 SELECT INTO value(hm_recmd_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE cur_list_size > 0
  DETAIL
   col 0,
   CALL print(trim(health_system_id)), v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(cnvtstring(edw_hm_recommend->qual[d.seq].hm_recommend_inst_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_hm_recommend->qual[d.seq].person_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_hm_recommend->qual[d.seq].hm_expect_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_hm_recommend->qual[d.seq].hm_expect_step_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_hm_recommend->qual[d.seq].due_override_hm_action_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_hm_recommend->qual[d.seq].freq_override_hm_action_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_hm_recommend->qual[d.seq].assigned_by_prsnl,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_hm_recommend->qual[d.seq].due_dt_tm,0,
      cnvtdatetimeutc(edw_hm_recommend->qual[d.seq].due_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(default_time_zone,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_hm_recommend->qual[d.seq].due_dt_tm,cnvtint(
      default_time_zone),"MMddyyyyHHmmsscc"),"0000000000000000","0","                ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_hm_recommend->qual[d.seq].expire_dt_tm,0,
      cnvtdatetimeutc(edw_hm_recommend->qual[d.seq].expire_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(default_time_zone,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_hm_recommend->qual[d.seq].expire_dt_tm,cnvtint(
      default_time_zone),"MMddyyyyHHmmsscc"),"0000000000000000","0","                ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_hm_recommend->qual[d.seq].near_due_dt_tm,
      0,cnvtdatetimeutc(edw_hm_recommend->qual[d.seq].near_due_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(default_time_zone,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_hm_recommend->qual[d.seq].near_due_dt_tm,cnvtint(
      default_time_zone),"MMddyyyyHHmmsscc"),"0000000000000000","0","                ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_hm_recommend->qual[d.seq].overdue_dt_tm,0,
      cnvtdatetimeutc(edw_hm_recommend->qual[d.seq].overdue_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(default_time_zone,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_hm_recommend->qual[d.seq].overdue_dt_tm,cnvtint(
      default_time_zone),"MMddyyyyHHmmsscc"),"0000000000000000","0","                ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_hm_recommend->qual[d.seq].qualified_dt_tm,
      0,cnvtdatetimeutc(edw_hm_recommend->qual[d.seq].qualified_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(default_time_zone,16))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_hm_recommend->qual[d.seq].qualified_dt_tm,cnvtint(
      default_time_zone),"MMddyyyyHHmmsscc"),"0000000000000000","0","                ","0",
    "1")),
   v_bar,
   CALL print(trim(cnvtstring(edw_hm_recommend->qual[d.seq].frequency_val,16))), v_bar,
   CALL print(trim(cnvtstring(edw_hm_recommend->qual[d.seq].frequency_unit_ref,16))), v_bar,
   CALL print(trim(replace(edw_hm_recommend->qual[d.seq].expectation_ftdesc,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(edw_hm_recommend->qual[d.seq].status_flg,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_hm_recommend->qual[d.seq].first_due_dt_tm,
      0,cnvtdatetimeutc(edw_hm_recommend->qual[d.seq].first_due_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(default_time_zone,16))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_hm_recommend->qual[d.seq].first_due_dt_tm,cnvtint(
      default_time_zone),"MMddyyyyHHmmsscc"),"0000000000000000","0","                ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_hm_recommend->qual[d.seq].
      last_satisfaction_dt_tm,0,cnvtdatetimeutc(edw_hm_recommend->qual[d.seq].last_satisfaction_dt_tm,
       3)),utc_timezone_index,"MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(default_time_zone,16))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_hm_recommend->qual[d.seq].last_satisfaction_dt_tm,
     cnvtint(default_time_zone),"MMddyyyyHHmmsscc"),"0000000000000000","0","                ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_hm_recommend->qual[d.seq].last_satisfaction_sk,16))), v_bar,
   CALL print(trim(replace(edw_hm_recommend->qual[d.seq].last_satisfaction_source,str_find,
     str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(edw_hm_recommend->qual[d.seq].last_satisfied_by_prsnl,16))), v_bar,
   "3", v_bar, extract_dt_tm_fmt,
   v_bar, row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
END GO
