CREATE PROGRAM edw_create_surgical_case:dba
 SELECT INTO value(surg_cs_extractfile)
  FROM (dummyt d  WITH seq = size(edw_surgical_case->qual,5))
  WHERE (edw_surgical_case->qual[d.seq].surgical_case_sk > 0)
  DETAIL
   record_count = (record_count+ 1), col 0,
   CALL print(trim(health_system_id)),
   v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(replace(edw_surgical_case->qual[d.seq].encounter_nk,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].encounter_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].surgical_case_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].person_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].sch_appointment_sk,16))),
   v_bar,
   CALL print(trim(replace(edw_surgical_case->qual[d.seq].surgical_case_nbr_formatted,str_find,
     str_replace,3),3)), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].sched_priority_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].sched_patient_type_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].case_level_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].asa_class_ref,16))), v_bar,
   CALL print(trim(edw_surgical_case->qual[d.seq].add_on_ind,3)),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].institution_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].dept_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].sched_surgical_area_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].surgical_area_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].sched_or_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].or_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].primary_surgeon_prsnl,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].case_surgeon_specialty_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].sched_anesthesia_prsnl,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].anesthesia_prsnl,16))), v_bar,
   CALL print(trim(edw_surgical_case->qual[d.seq].additional_supplies_ind,3)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].check_in_dt_tm,
      0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].check_in_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].check_in_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].check_in_dt_tm,cnvtint(
      edw_surgical_case->qual[d.seq].check_in_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].check_in_by_prsnl,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].complete_ind))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].cancel_dt_tm,0,
      cnvtdatetimeutc(edw_surgical_case->qual[d.seq].cancel_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].cancel_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].cancel_dt_tm,cnvtint(
      edw_surgical_case->qual[d.seq].cancel_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].cancel_reason_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].cancel_requested_by_person_sk,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      sched_start_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].sched_start_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].sched_start_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].sched_start_dt_tm,cnvtint(
      edw_surgical_case->qual[d.seq].sched_start_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].start_dt_tm,0,
      cnvtdatetimeutc(edw_surgical_case->qual[d.seq].start_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].start_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].start_dt_tm,cnvtint(
      edw_surgical_case->qual[d.seq].start_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      sched_stop_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].sched_stop_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].sched_stop_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].sched_stop_dt_tm,cnvtint(
      edw_surgical_case->qual[d.seq].sched_stop_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].stop_dt_tm,0,
      cnvtdatetimeutc(edw_surgical_case->qual[d.seq].stop_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].stop_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].stop_dt_tm,cnvtint(
      edw_surgical_case->qual[d.seq].stop_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(edw_surgical_case->qual[d.seq].sched_setup_duration,3)), v_bar,
   CALL print(trim(edw_surgical_case->qual[d.seq].sched_cleanup_duration,3)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      request_transport_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].
       request_transport_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].request_transport_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].request_transport_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].request_transport_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      in_preop_holding_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].in_preop_holding_dt_tm,
       3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].in_preop_holding_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].in_preop_holding_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].in_preop_holding_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      anesthesia_start_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].anesthesia_start_dt_tm,
       3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].anesthesia_start_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].anesthesia_start_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].anesthesia_start_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].or_setup_dt_tm,
      0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].or_setup_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].or_setup_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].or_setup_dt_tm,cnvtint(
      edw_surgical_case->qual[d.seq].or_setup_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].or_ready_dt_tm,
      0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].or_ready_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].or_ready_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].or_ready_dt_tm,cnvtint(
      edw_surgical_case->qual[d.seq].or_ready_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      out_preop_holding_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].
       out_preop_holding_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].out_preop_holding_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].out_preop_holding_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].out_preop_holding_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      patient_in_or_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].patient_in_or_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].patient_in_or_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].patient_in_or_dt_tm,cnvtint(
      edw_surgical_case->qual[d.seq].patient_in_or_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      anesth_induction_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].anesth_induction_dt_tm,
       3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].anesth_induction_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].anesth_induction_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].anesth_induction_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      surgeon_in_room_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].surgeon_in_room_dt_tm,3)
      ),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].surgeon_in_room_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].surgeon_in_room_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].surgeon_in_room_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      ready_for_surgeon_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].
       ready_for_surgeon_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].ready_for_surgeon_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].ready_for_surgeon_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].ready_for_surgeon_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      closing_start_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].closing_start_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].closing_start_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].closing_start_dt_tm,cnvtint(
      edw_surgical_case->qual[d.seq].closing_start_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      patient_out_or_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].patient_out_or_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].patient_out_or_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].patient_out_or_dt_tm,cnvtint
     (edw_surgical_case->qual[d.seq].patient_out_or_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      patient_in_pacu_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].patient_in_pacu_dt_tm,3)
      ),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].patient_in_pacu_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].patient_in_pacu_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].patient_in_pacu_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      anesthesia_stop_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].anesthesia_stop_dt_tm,3)
      ),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].anesthesia_stop_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].anesthesia_stop_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].anesthesia_stop_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      anesth_prov_stop_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].anesth_prov_stop_dt_tm,
       3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].anesth_prov_stop_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].anesth_prov_stop_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].anesth_prov_stop_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      patient_out_pacu_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].patient_out_pacu_dt_tm,
       3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].patient_out_pacu_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].patient_out_pacu_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].patient_out_pacu_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      patient_in_pacu_ii_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].
       patient_in_pacu_ii_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].patient_in_pacu_ii_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].patient_in_pacu_ii_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].patient_in_pacu_ii_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      patient_out_pacu_ii_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].
       patient_out_pacu_ii_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].patient_out_pacu_ii_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].patient_out_pacu_ii_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].patient_out_pacu_ii_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      cleanup_start_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].cleanup_start_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].cleanup_start_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].cleanup_start_dt_tm,cnvtint(
      edw_surgical_case->qual[d.seq].cleanup_start_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      cleanup_stop_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].cleanup_stop_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].cleanup_stop_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].cleanup_stop_dt_tm,cnvtint(
      edw_surgical_case->qual[d.seq].cleanup_stop_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(substring(1,2000,replace(edw_surgical_case->qual[d.seq].ft_preop_diag,str_find,
      str_replace,3)),3)),
   v_bar,
   CALL print(trim(substring(1,2000,replace(edw_surgical_case->qual[d.seq].ft_postop_diag,str_find,
      str_replace,3)),3)), v_bar,
   CALL print(build(edw_surgical_case->qual[d.seq].room_cost_patient_duration_amt)), v_bar,
   CALL print(build(edw_surgical_case->qual[d.seq].room_cost_surgery_duration_amt)),
   v_bar,
   CALL print(build(edw_surgical_case->qual[d.seq].total_attendees_cost_amt)), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].sched_sch_slot_type_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].sch_slot_type_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].sch_calendar_sk,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      preop_antibio_admin_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].
       preop_antibio_admin_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].preop_antibio_admin_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].preop_antibio_admin_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].preop_antibio_admin_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].
      surgical_time_out_dt_tm,0,cnvtdatetimeutc(edw_surgical_case->qual[d.seq].
       surgical_time_out_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].surgical_time_out_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case->qual[d.seq].surgical_time_out_dt_tm,
     cnvtint(edw_surgical_case->qual[d.seq].surgical_time_out_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   "3", v_bar, extract_dt_tm_fmt,
   v_bar,
   CALL print(trim(edw_surgical_case->qual[d.seq].active_ind,3)), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].sched_or_shift_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].or_shift_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].wound_class_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].block_instance_sk,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].create_dt_tm,0,
      cnvtdatetimeutc(edw_surgical_case->qual[d.seq].create_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case->qual[d.seq].create_tm_zn,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case->qual[d.seq].create_dt_tm,0,
      cnvtdatetimeutc(edw_surgical_case->qual[d.seq].create_dt_tm,2)),edw_surgical_case->qual[d.seq].
     create_tm_zn,"MM/DD/YYYY HH:mm:ss"))), v_bar, row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
 SET script_version = "008 10/16/2018 SB026554"
END GO
