CREATE PROGRAM edw_create_fin_pay_adj:dba
 SELECT INTO value(fin_pay_adj_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE cur_list_size > 0
  DETAIL
   col 0,
   CALL print(trim(health_system_id)), v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].fin_encntr_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].fin_pay_adj_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].fin_bill_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].fin_batch_trans_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].trans_activity_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].activity_event_ref,16))), v_bar,
   CALL print(build(edw_pay_adj->qual[d.seq].activity_productivity_flg)),
   v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].activity_productivity_wt,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pay_adj->qual[d.seq].activity_dt_tm,0,
      cnvtdatetimeutc(edw_pay_adj->qual[d.seq].activity_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].activity_tz))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pay_adj->qual[d.seq].activity_dt_tm,cnvtint(edw_pay_adj
      ->qual[d.seq].activity_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pay_adj->qual[d.seq].created_dt_tm,0,
      cnvtdatetimeutc(edw_pay_adj->qual[d.seq].created_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].created_tz))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pay_adj->qual[d.seq].created_dt_tm,cnvtint(edw_pay_adj
      ->qual[d.seq].created_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(build(edw_pay_adj->qual[d.seq].bill_ind)), v_bar,
   CALL print(build(edw_pay_adj->qual[d.seq].gl_posted_ind)),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pay_adj->qual[d.seq].posted_dt_tm,0,
      cnvtdatetimeutc(edw_pay_adj->qual[d.seq].posted_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].posted_tz))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pay_adj->qual[d.seq].posted_dt_tm,cnvtint(edw_pay_adj->
      qual[d.seq].posted_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(build(edw_pay_adj->qual[d.seq].supression_flg)), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].transaction_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].transaction_sub_type_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].transaction_status_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].trans_status_reason_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].transaction_reason_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].transaction_amt,11,2))), v_bar,
   CALL print(build(edw_pay_adj->qual[d.seq].trans_credit_debit_flg)), v_bar,
   CALL print(trim(replace(edw_pay_adj->qual[d.seq].credit_card_auth_nbr_txt,str_find,str_replace,3),
    3)),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pay_adj->qual[d.seq].
      credit_card_beg_eff_dt_tm,0,cnvtdatetimeutc(edw_pay_adj->qual[d.seq].credit_card_beg_eff_dt_tm,
       3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].credit_card_beg_eff_tz))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pay_adj->qual[d.seq].credit_card_beg_eff_dt_tm,cnvtint(
      edw_pay_adj->qual[d.seq].credit_card_beg_eff_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pay_adj->qual[d.seq].
      credit_card_end_eff_dt_tm,0,cnvtdatetimeutc(edw_pay_adj->qual[d.seq].credit_card_end_eff_dt_tm,
       3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].credit_card_end_eff_tz))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pay_adj->qual[d.seq].credit_card_end_eff_dt_tm,cnvtint(
      edw_pay_adj->qual[d.seq].credit_card_end_eff_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].change_due_amt,11,2))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pay_adj->qual[d.seq].check_dt_tm,0,
      cnvtdatetimeutc(edw_pay_adj->qual[d.seq].check_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].check_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pay_adj->qual[d.seq].check_dt_tm,cnvtint(edw_pay_adj->
      qual[d.seq].check_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].current_currency_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].deposit_status_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].original_currency_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].payment_method_ref,16))), v_bar,
   CALL print(trim(replace(edw_pay_adj->qual[d.seq].payment_number_txt,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(replace(edw_pay_adj->qual[d.seq].payor_name,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].posting_method_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pay_adj->qual[d.seq].
      pay_detail_posted_dt_tm,0,cnvtdatetimeutc(edw_pay_adj->qual[d.seq].pay_detail_posted_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].pay_detail_posted_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pay_adj->qual[d.seq].pay_detail_posted_dt_tm,cnvtint(
      edw_pay_adj->qual[d.seq].pay_detail_posted_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].tendered_amt,11,2))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].total_payment_amt,11,2))), v_bar,
   CALL print(build(edw_pay_adj->qual[d.seq].gl_account_sk)), v_bar,
   CALL print(build(edw_pay_adj->qual[d.seq].gl_rsp_unit_sk)),
   v_bar, "3", v_bar,
   extract_dt_tm_fmt, v_bar,
   CALL print("1"),
   v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].health_plan_hlthpln,16))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].priority_seq,16))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].created_prsnl,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].trans_alias_sk,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pay_adj->qual[d.seq].activity_dt_tm,0,
      cnvtdatetimeutc(edw_pay_adj->qual[d.seq].activity_dt_tm,2)),edw_pay_adj->qual[d.seq].
     activity_tz,"MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].bill_type_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].total_trans_amt,16,4))), v_bar,
   CALL print(trim(cnvtstring(edw_pay_adj->qual[d.seq].hp_bo_hp_reltn_sk,16))), v_bar, row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
 SET script_version = "009 02/06/18 mf025696"
END GO
