CREATE PROGRAM edw_create_fin_bill:dba
 SELECT INTO value(fin_bill_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE cur_list_size > 0
  DETAIL
   record_cnt = (record_cnt+ 1), col 0,
   CALL print(trim(health_system_source_id)),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].fin_encounter_sk,16))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].fin_bill_sk,16))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].bill_version_nbr,16))),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].bill_type_ref,16))), v_bar,
   CALL print(trim(replace(fin_bill->qual[d.seq].balance_amt,str_find,str_replace,3))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].balance_credit_debit_flg))),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].balance_due_amt,16))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].balance_due_credit_debit_flg))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].balance_fwd_amt,16))),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].balance_fwd_credit_debit_flg))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].bill_class_ref,16))), v_bar,
   CALL print(trim(replace(fin_bill->qual[d.seq].bill_nbr_disp,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].bill_status_ref,16))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].bill_status_reason_ref,16))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].claim_file_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].claim_serial_nbr,16))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].claim_event_status_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_bill->qual[d.seq].claim_status_ctrl_dt_tm,
      0,cnvtdatetimeutc(fin_bill->qual[d.seq].claim_status_ctrl_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].claim_status_ctrl_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_bill->qual[d.seq].claim_status_ctrl_dt_tm,cnvtint(
      fin_bill->qual[d.seq].claim_status_ctrl_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].contract_mgmt_status_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].demand_flg))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_bill->qual[d.seq].from_service_dt_tm,0,
      cnvtdatetimeutc(fin_bill->qual[d.seq].from_service_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].from_service_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(fin_bill->qual[d.seq].from_service_dt_tm,cnvtint(fin_bill->
      qual[d.seq].from_service_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_bill->qual[d.seq].to_service_dt_tm,0,
      cnvtdatetimeutc(fin_bill->qual[d.seq].to_service_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].to_service_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(fin_bill->qual[d.seq].to_service_dt_tm,cnvtint(fin_bill->
      qual[d.seq].to_service_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_bill->qual[d.seq].claim_event_gen_dt_tm,0,
      cnvtdatetimeutc(fin_bill->qual[d.seq].claim_event_gen_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].claim_event_gen_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(fin_bill->qual[d.seq].claim_event_gen_dt_tm,cnvtint(
      fin_bill->qual[d.seq].claim_event_gen_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].image_flg))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].interim_bill_flg))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_bill->qual[d.seq].last_adjustment_dt_tm,0,
      cnvtdatetimeutc(fin_bill->qual[d.seq].last_adjustment_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].last_adjustment_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_bill->qual[d.seq].last_adjustment_dt_tm,cnvtint(
      fin_bill->qual[d.seq].last_adjustment_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_bill->qual[d.seq].last_payment_dt_tm,0,
      cnvtdatetimeutc(fin_bill->qual[d.seq].last_payment_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].last_payment_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_bill->qual[d.seq].last_payment_dt_tm,cnvtint(fin_bill->
      qual[d.seq].last_payment_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].manual_review_flg))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].media_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].media_sub_type_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].new_amt,16))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].new_amt_credit_debit_flg))), v_bar,
   CALL print(trim(replace(fin_bill->qual[d.seq].page_cnt,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].ra_claim_field_ref,16))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].ra_claim_status_ref,16))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].claim_resp_party_ref,16))),
   v_bar,
   CALL print(trim(replace(fin_bill->qual[d.seq].route_user_name,str_find,str_replace,3))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].submission_route_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_bill->qual[d.seq].submit_dt_tm,0,
      cnvtdatetimeutc(fin_bill->qual[d.seq].submit_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"
     ))),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].submit_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_bill->qual[d.seq].submit_dt_tm,cnvtint(fin_bill->qual[d
      .seq].submit_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_bill->qual[d.seq].transmission_dt_tm,0,
      cnvtdatetimeutc(fin_bill->qual[d.seq].transmission_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].transmission_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(fin_bill->qual[d.seq].transmission_dt_tm,cnvtint(fin_bill->
      qual[d.seq].transmission_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].health_plan_hlthpln,16))),
   v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].priority_seq))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_bill->qual[d.seq].denial_dt_tm,0,
      cnvtdatetimeutc(fin_bill->qual[d.seq].denial_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"
     ))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].denial_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(fin_bill->qual[d.seq].denial_dt_tm,cnvtint(fin_bill->qual[d
      .seq].denial_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_bill->qual[d.seq].demographic_mod_dt_tm,0,
      cnvtdatetimeutc(fin_bill->qual[d.seq].demographic_mod_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].demographic_mod_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(fin_bill->qual[d.seq].demographic_mod_dt_tm,cnvtint(
      fin_bill->qual[d.seq].demographic_mod_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,fin_bill->qual[d.seq].encntr_combine_dt_tm,0,
      cnvtdatetimeutc(fin_bill->qual[d.seq].encntr_combine_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].encntr_combine_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(fin_bill->qual[d.seq].encntr_combine_dt_tm,cnvtint(fin_bill
      ->qual[d.seq].encntr_combine_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   "3", v_bar, extract_dt_tm_fmt,
   v_bar,
   CALL print(trim(replace(fin_bill->qual[d.seq].src_active_ind,str_find,str_replace,3))), v_bar,
   CALL print(trim(cnvtstring(fin_bill->qual[d.seq].bo_hp_reltn_sk,16))), v_bar, row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
 SET script_version = "003 07/25/16 mf025696"
END GO
