CREATE PROGRAM edw_create_pha_ord_files
 SELECT INTO value(pha_ord_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE cur_list_size > 0
  DETAIL
   pha_ord_file_cnt = (pha_ord_file_cnt+ 1), col 0,
   CALL print(trim(health_system_id)),
   v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].order_sk,16))), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].pharm_order_sk,16))),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].iv_ind)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].multiple_ingredient_ind)), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].med_order_type_ref,16))),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].rx_mask)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].rx_diluent_ind)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].rx_additive_ind)),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].rx_med_ind)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].rx_tpn_ind)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].rx_sliding_scale_ind)),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].rx_tapering_dose_ind)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].rx_pca_ind)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].infuse_over)),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].infuse_unit_ref)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].duration)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].duration_unit_ref)),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].take_home_med)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].take_home_med_qty)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].sample_given_ind)),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].sample_given_qty)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].sample_given_qty_unit_ref)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].total_volume)),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].route_type_ref)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].claim_flg)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].coordinate_of_benefit_ind)),
   v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].dispense_as_written_ref,16))), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].days_supply)), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].dispense_category_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,pha_ord->qual[d.seq].expire_dt_tm,0,
      cnvtdatetimeutc(pha_ord->qual[d.seq].expire_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].expire_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(pha_ord->qual[d.seq].expire_dt_tm,cnvtint(pha_ord->qual[d
      .seq].expire_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].fill_nbr)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].floorstock_ind)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].floorstock_override_ind)),
   v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].frequency_sk,16))), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].future_loc,16))), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].order_hlthpln,16))),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].ignore_ind)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].iv_set_cnt)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].last_clin_rev_act_seq)),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,pha_ord->qual[d.seq].last_clin_rev_act_dt_tm,
      0,cnvtdatetimeutc(pha_ord->qual[d.seq].last_clin_rev_act_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].last_clin_rev_act_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(pha_ord->qual[d.seq].last_clin_rev_act_dt_tm,cnvtint(
      pha_ord->qual[d.seq].last_clin_rev_act_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].last_clin_rev_com_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].last_clin_rev_prsnl,16))), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].last_clin_rev_spvs_prsnl,16))),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].last_clin_review_ingr_seq)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].last_fill_action_seq)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,pha_ord->qual[d.seq].last_fill_action_dt_tm,0,
      cnvtdatetimeutc(pha_ord->qual[d.seq].last_fill_action_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].last_fill_action_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(pha_ord->qual[d.seq].last_fill_action_dt_tm,cnvtint(pha_ord
      ->qual[d.seq].last_fill_action_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].last_fill_action_com_type_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].last_fill_action_prsnl,16))), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].last_fill_spvs_prsnl,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,pha_ord->qual[d.seq].last_refill_dt_tm,0,
      cnvtdatetimeutc(pha_ord->qual[d.seq].last_refill_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].last_refill_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(pha_ord->qual[d.seq].last_refill_dt_tm,cnvtint(pha_ord->
      qual[d.seq].last_refill_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].next_iv_seq)),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].order_dispense_ind)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].order_type_flg)), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].parent_order_sk,16))),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].par_dose)), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].pharm_type_ref,16))), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].remaining_qty)),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].remaining_refill_cnt)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].replace_interval)), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].replace_interval_unit_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].research_account_sk,16))), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].total_dispense_doses)), v_bar,
   CALL print(trim(pha_ord->qual[d.seq].total_rx_qty)),
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].rx_transfer_cnt)), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].unverified_action_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].unverified_comm_type_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].unverified_route_ref,16))), v_bar,
   CALL print(trim(cnvtstring(pha_ord->qual[d.seq].unverified_rx_ord_priority_ref,16))), v_bar, "3",
   v_bar, extract_dt_tm_fmt, v_bar,
   "1", v_bar, v_bar,
   v_bar, v_bar, v_bar,
   v_bar,
   CALL print(trim(pha_ord->qual[d.seq].order_dispense_loc)), v_bar,
   v_bar, row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
 SET script_version = "004 11/19/07 ND013822"
END GO
