CREATE PROGRAM edw_create_pregnancy:dba
 SELECT INTO value(preginst_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE cur_list_size > 0
  DETAIL
   col 0,
   CALL print(trim(health_system_id)), v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].pregnancy_inst_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].parent_pregnancy_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].person_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].problem_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].pregnancy_org,16))), v_bar,
   CALL print(trim(edw_pregnancy->qual[d.seq].sensitive_ind)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pregnancy->qual[d.seq].preg_start_dt_tm,0,
      cnvtdatetimeutc(edw_pregnancy->qual[d.seq].preg_start_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].preg_start_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pregnancy->qual[d.seq].preg_start_dt_tm,cnvtint(
      edw_pregnancy->qual[d.seq].preg_start_tm_zn),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pregnancy->qual[d.seq].preg_end_dt_tm,0,
      cnvtdatetimeutc(edw_pregnancy->qual[d.seq].preg_end_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].preg_end_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pregnancy->qual[d.seq].preg_end_dt_tm,cnvtint(
      edw_pregnancy->qual[d.seq].preg_end_tm_zn),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")), v_bar,
   CALL print(trim(replace(edw_pregnancy->qual[d.seq].override_comment,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pregnancy->qual[d.seq].confirmed_dt_tm,0,
      cnvtdatetimeutc(edw_pregnancy->qual[d.seq].confirmed_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].confirmed_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pregnancy->qual[d.seq].confirmed_dt_tm,cnvtint(
      edw_pregnancy->qual[d.seq].confirmed_tm_zn),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")),
   v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].confirmation_method_ref,16))), v_bar,
   CALL print(trim(edw_pregnancy->qual[d.seq].historical_ind)), v_bar,
   CALL print(trim(edw_pregnancy->qual[d.seq].src_active_ind)),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pregnancy->qual[d.seq].
      src_beg_effective_dt_tm,0,cnvtdatetimeutc(edw_pregnancy->qual[d.seq].src_beg_effective_dt_tm,3)
      ),utc_timezone_index,"MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pregnancy->qual[d.seq].src_beg_effective_dt_tm,cnvtint(
      edw_pregnancy->qual[d.seq].src_tz),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pregnancy->qual[d.seq].
      src_end_effective_dt_tm,0,cnvtdatetimeutc(edw_pregnancy->qual[d.seq].src_end_effective_dt_tm,3)
      ),utc_timezone_index,"MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pregnancy->qual[d.seq].src_end_effective_dt_tm,cnvtint(
      edw_pregnancy->qual[d.seq].src_tz),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].src_tz,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pregnancy->qual[d.seq].create_dt_tm,0,
      cnvtdatetimeutc(edw_pregnancy->qual[d.seq].create_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].create_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pregnancy->qual[d.seq].create_dt_tm,cnvtint(
      edw_pregnancy->qual[d.seq].create_tm_zn),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].create_prsnl,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pregnancy->qual[d.seq].review_dt_tm,0,
      cnvtdatetimeutc(edw_pregnancy->qual[d.seq].review_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].review_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pregnancy->qual[d.seq].review_dt_tm,cnvtint(
      edw_pregnancy->qual[d.seq].review_tm_zn),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")),
   v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].review_prsnl,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pregnancy->qual[d.seq].cancel_dt_tm,0,
      cnvtdatetimeutc(edw_pregnancy->qual[d.seq].cancel_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].cancel_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pregnancy->qual[d.seq].cancel_dt_tm,cnvtint(
      edw_pregnancy->qual[d.seq].cancel_tm_zn),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].cancel_prsnl,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pregnancy->qual[d.seq].labor_start_dt_tm,
      0,cnvtdatetimeutc(edw_pregnancy->qual[d.seq].labor_start_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].labor_start_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pregnancy->qual[d.seq].labor_start_dt_tm,cnvtint(
      edw_pregnancy->qual[d.seq].confirmed_tm_zn),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].labor_start_prsnl,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pregnancy->qual[d.seq].labor_cancel_dt_tm,
      0,cnvtdatetimeutc(edw_pregnancy->qual[d.seq].labor_cancel_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].labor_cancel_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pregnancy->qual[d.seq].labor_cancel_dt_tm,cnvtint(
      edw_pregnancy->qual[d.seq].labor_cancel_tm_zn),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")),
   v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].labor_cancel_prsnl,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_pregnancy->qual[d.seq].delete_dt_tm,0,
      cnvtdatetimeutc(edw_pregnancy->qual[d.seq].delete_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].delete_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_pregnancy->qual[d.seq].delete_dt_tm,cnvtint(
      edw_pregnancy->qual[d.seq].delete_tm_zn),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_pregnancy->qual[d.seq].delete_prsnl,16))), v_bar, "3",
   v_bar, extract_dt_tm_fmt, v_bar,
   row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
END GO
