CREATE PROGRAM edw_create_med_admin_files
 SELECT INTO value(med_admn_extractfile)
  FROM (dummyt d  WITH seq = value(rec_cnt))
  WHERE rec_cnt > 0
  DETAIL
   col 0,
   CALL print(trim(health_system_id)), v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(replace(med_admin->qual[d.seq].encounter_nk,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].person_sk,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].encounter_sk,16))), v_bar,
   CALL print(trim(med_admin->qual[d.seq].med_admin_sk)),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].event_sk,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].med_admin_event_sk,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].order_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].dosage,16,4))), v_bar,
   CALL print(build(datetimezoneformat(evaluate(curutc,1,med_admin->qual[d.seq].admin_end_dt_tm,0,
      cnvtdatetimeutc(med_admin->qual[d.seq].admin_end_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].admin_end_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(med_admin->qual[d.seq].admin_end_dt_tm,cnvtint(med_admin->
      qual[d.seq].admin_end_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].method_ref,16))), v_bar,
   CALL print(trim(replace(med_admin->qual[d.seq].note,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].admin_prsnl,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].patient_location_loc,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].route_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].site_ref,16))), v_bar,
   CALL print(build(datetimezoneformat(evaluate(curutc,1,med_admin->qual[d.seq].start_dt_tm,0,
      cnvtdatetimeutc(med_admin->qual[d.seq].start_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].start_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(med_admin->qual[d.seq].start_dt_tm,cnvtint(med_admin->qual[
      d.seq].start_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(build(med_admin->qual[d.seq].strength)), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].strength_unit_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].diluent_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].dosage_unit_ref,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].immunization_type_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].infused_volume,16,4))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].infused_volume_unit_ref,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].infusion_rate,16,4))),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].infusion_time_ref,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].infusion_unit_ref,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].initial_dosage,16,4))),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].initial_volume,16,4))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].iv_event_ref,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].medication_form_ref,16))),
   v_bar,
   CALL print(trim(med_admin->qual[d.seq].reason_required_flg)), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].refusal_ref,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].remaining_volume,16,4))),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].remaining_volume_unit_ref,16))), v_bar,
   CALL print(trim(med_admin->qual[d.seq].response_required_flg)), v_bar,
   CALL print(build(datetimezoneformat(evaluate(curutc,1,med_admin->qual[d.seq].substance_exp_dt_tm,0,
      cnvtdatetimeutc(med_admin->qual[d.seq].substance_exp_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].substance_exp_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(med_admin->qual[d.seq].substance_exp_dt_tm,cnvtint(
      med_admin->qual[d.seq].substance_exp_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(replace(med_admin->qual[d.seq].substance_lot_nbr,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].substance_manufacturer_ref,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].med_admin_ordbl,16))), v_bar,
   CALL print(build(datetimezoneformat(evaluate(curutc,1,med_admin->qual[d.seq].system_entry_dt_tm,0,
      cnvtdatetimeutc(med_admin->qual[d.seq].system_entry_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].system_entry_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(med_admin->qual[d.seq].system_entry_dt_tm,cnvtint(med_admin
      ->qual[d.seq].system_entry_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].total_intake_volume,16,4))),
   v_bar,
   CALL print(trim(med_admin->qual[d.seq].consent_received_ind)), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].approved_prsnl,16))), v_bar, "3",
   v_bar,
   CALL print(trim(extract_dt_tm_fmt)), v_bar,
   CALL print(build(med_admin->qual[d.seq].active_ind)), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].comments_long_text_sk,16))),
   v_bar,
   CALL print(trim(replace(med_admin->qual[d.seq].freetext_reason,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].manf_ref,16))), v_bar,
   CALL print(trim(cnvtstring(med_admin->qual[d.seq].dose_quantity,16,4))),
   v_bar, row + 1
  WITH check, noheading, nocounter,
   format = lfstream, maxcol = 1999, maxrow = 1,
   append
 ;end select
 SET script_version = "011 01/02/16 MF025696"
END GO
