CREATE PROGRAM edw_create_encntr_leave:dba
 SELECT INTO value(enc_leav_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE cur_list_size > 0
  DETAIL
   col 0,
   CALL print(trim(health_system_id)), v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(enc_leav->qual[d.seq].encounter_nk)),
   v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].encounter_sk,16))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].enc_leave_sk,16))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].active_ind,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_leav->qual[d.seq].auto_discharge_dt_tm,0,
      cnvtdatetimeutc(enc_leav->qual[d.seq].auto_discharge_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].auto_discharge_tm_zn))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].auto_discharge_tm_vld_flg))),
   v_bar,
   CALL print(trim(replace(enc_leav->qual[d.seq].cancel_comment,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_leav->qual[d.seq].cancel_dt_tm,0,
      cnvtdatetimeutc(enc_leav->qual[d.seq].cancel_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].cancel_tm_zn))),
   v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].cancel_tm_vld_flg))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].cancel_reason_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].cancel_prsnl,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_leav->qual[d.seq].estimated_return_dt_tm,
      0,cnvtdatetimeutc(enc_leav->qual[d.seq].estimated_return_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].estimated_return_tm_zn))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].estimated_return_tm_vld_flg))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_leav->qual[d.seq].hold_removal_dt_tm,0,
      cnvtdatetimeutc(enc_leav->qual[d.seq].hold_removal_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].hold_removal_tm_zn))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].hold_removal_tm_vld_flg))),
   v_bar,
   CALL print(trim(replace(enc_leav->qual[d.seq].leave_comment,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_leav->qual[d.seq].leave_dt_tm,0,
      cnvtdatetimeutc(enc_leav->qual[d.seq].leave_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].leave_tm_zn))),
   v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].leave_tm_vld_flg))), v_bar,
   CALL print(trim(replace(enc_leav->qual[d.seq].leave_ind,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(replace(enc_leav->qual[d.seq].leave_location,str_find,str_replace,3),3)),
   v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].leave_reason_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].leave_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].leave_prsnl,16))),
   v_bar,
   CALL print(trim(replace(enc_leav->qual[d.seq].return_comment,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_leav->qual[d.seq].return_dt_tm,0,
      cnvtdatetimeutc(enc_leav->qual[d.seq].return_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].return_tm_zn))),
   v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].return_tm_vld_flg))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].return_loc,16))), v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].return_reason_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(enc_leav->qual[d.seq].return_prsnl,16))), v_bar,
   "3", v_bar, extract_dt_tm_fmt,
   row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
 SET script_version = "000 25-MAY-2007 SB013134"
END GO
