CREATE PROGRAM edw_create_encntr_flex_files:dba
 SELECT INTO value(enc_flex_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE (enc_flex->qual[d.seq].enc_flex_hist_sk > 0)
  DETAIL
   encntr_flex_file_cnt = (encntr_flex_file_cnt+ 1), col 0,
   CALL print(trim(health_system_id)),
   v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(replace(enc_flex->qual[d.seq].encounter_nk,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].encounter_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].enc_flex_hist_sk,16))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].accommodation_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].accommodation_request_ref,16))),
   v_bar,
   CALL print(build(enc_flex->qual[d.seq].active_ind)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_flex->qual[d.seq].activity_dt_tm,0,
      cnvtdatetimeutc(enc_flex->qual[d.seq].activity_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].activity_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(enc_flex->qual[d.seq].activity_dt_tm,cnvtint(enc_flex->
      qual[d.seq].activity_tm_zn),"hhmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].admit_mode_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].admit_source_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].admit_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].alternate_lvl_care_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_flex->qual[d.seq].
      alt_lvl_care_decomp_dt_tm,0,cnvtdatetimeutc(enc_flex->qual[d.seq].alt_lvl_care_decomp_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].alt_lvl_care_decomp_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(enc_flex->qual[d.seq].alt_lvl_care_decomp_dt_tm,cnvtint(
      enc_flex->qual[d.seq].alt_lvl_care_decomp_tm_zn),"hhmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_flex->qual[d.seq].
      alternate_lvl_care_dt_tm,0,cnvtdatetimeutc(enc_flex->qual[d.seq].alternate_lvl_care_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].alternate_lvl_care_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(enc_flex->qual[d.seq].alternate_lvl_care_dt_tm,cnvtint(
      enc_flex->qual[d.seq].alternate_lvl_care_tm_zn),"hhmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].change_bit,16))),
   v_bar,
   CALL print(trim(replace(enc_flex->qual[d.seq].change_bit_txt,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].discharge_disposition_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_flex->qual[d.seq].discharge_dt_tm,0,
      cnvtdatetimeutc(enc_flex->qual[d.seq].discharge_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].discharge_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(enc_flex->qual[d.seq].discharge_dt_tm,cnvtint(enc_flex->
      qual[d.seq].discharge_tm_zn),"hhmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].discharge_to_loc_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].encounter_status_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].patient_type_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_flex->qual[d.seq].inpatient_admit_dt_tm,0,
      cnvtdatetimeutc(enc_flex->qual[d.seq].inpatient_admit_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].inpatient_admit_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(enc_flex->qual[d.seq].inpatient_admit_dt_tm,cnvtint(
      enc_flex->qual[d.seq].inpatient_admit_tm_zn),"hhmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].isolation_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].current_loc,16))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].temporary_loc,16))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].medical_service_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].mental_category_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].mental_health_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_flex->qual[d.seq].mental_health_dt_tm,0,
      cnvtdatetimeutc(enc_flex->qual[d.seq].mental_health_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].mental_health_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(enc_flex->qual[d.seq].mental_health_dt_tm,cnvtint(enc_flex
      ->qual[d.seq].mental_health_tm_zn),"hhmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].organization_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].patient_classification_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].person_sk,16))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].placement_auth_prsnl,16))),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].psychiatric_status_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].region_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_flex->qual[d.seq].admit_dt_tm,0,
      cnvtdatetimeutc(enc_flex->qual[d.seq].admit_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss")
    )),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].admit_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(enc_flex->qual[d.seq].admit_dt_tm,cnvtint(enc_flex->qual[d
      .seq].admit_tm_zn),"hhmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].tracking_bit,16))),
   v_bar,
   CALL print(trim(replace(enc_flex->qual[d.seq].tracking_bit_txt,str_find,str_replace,3),3)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_flex->qual[d.seq].transaction_dt_tm,0,
      cnvtdatetimeutc(enc_flex->qual[d.seq].transaction_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm:ss"))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].transaction_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(enc_flex->qual[d.seq].transaction_dt_tm,cnvtint(enc_flex->
      qual[d.seq].transaction_tm_zn),"hhmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].transfer_reason_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].trauma_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_flex->qual[d.seq].trauma_dt_tm,0,
      cnvtdatetimeutc(enc_flex->qual[d.seq].trauma_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"
     ))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].trauma_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(enc_flex->qual[d.seq].trauma_dt_tm,cnvtint(enc_flex->qual[d
      .seq].triage_tm_zn),"hhmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].triage_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_flex->qual[d.seq].triage_dt_tm,0,
      cnvtdatetimeutc(enc_flex->qual[d.seq].triage_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm:ss"
     ))), v_bar,
   CALL print(trim(cnvtstring(enc_flex->qual[d.seq].triage_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(enc_flex->qual[d.seq].triage_dt_tm,cnvtint(enc_flex->qual[d
      .seq].triage_tm_zn),"hhmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   "3", v_bar, extract_dt_tm_fmt,
   row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
 SET script_version = "003 05/07/20 BS074648"
END GO
