CREATE PROGRAM edw_create_surgical_case_proc:dba
 SELECT INTO value(surg_p_extractfile)
  FROM (dummyt d  WITH seq = size(edw_surgical_case_proc->qual,5))
  WHERE (edw_surgical_case_proc->qual[d.seq].surgical_case_proc_sk > 0)
  DETAIL
   record_count = (record_count+ 1), col 0, health_system_id,
   v_bar, health_system_source_id, v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].surgical_case_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].surgical_case_proc_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].order_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].sched_procedure_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].procedure_ref,16))),
   v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].sched_primary_proc_ind,3)), v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].sched_proc_cnt,3)), v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].primary_proc_ind,3)),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].sched_prim_surgeon_prsnl,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].prim_surgeon_prsnl,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].expected_case_level_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].sched_anesthesia_type_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].anesthesia_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].expected_wound_class_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].wound_class_ref,16))), v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].sched_blood_product_req_ind,3)), v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].sched_frozen_section_req_ind,3)),
   v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].sched_specimen_req_ind,3)), v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].sched_xray_req_ind,3)), v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].sched_xray_tech_req_ind,3)),
   v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].sched_implant_req_ind,3)), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].spec_not_collected_reason_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case_proc->qual[d.seq].
      proc_start_dt_tm,0,cnvtdatetimeutc(edw_surgical_case_proc->qual[d.seq].proc_start_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].proc_start_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case_proc->qual[d.seq].proc_start_dt_tm,
     cnvtint(edw_surgical_case_proc->qual[d.seq].proc_start_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case_proc->qual[d.seq].
      proc_stop_dt_tm,0,cnvtdatetimeutc(edw_surgical_case_proc->qual[d.seq].proc_stop_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].proc_stop_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case_proc->qual[d.seq].proc_stop_dt_tm,cnvtint
     (edw_surgical_case_proc->qual[d.seq].proc_stop_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].sched_proc_duration,3)),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].sched_user_defined_field1_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].user_defined_field1_code_set,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].sched_user_defined_field2_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].user_defined_field2_code_set,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].sched_user_defined_field3_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].user_defined_field3_code_set,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].sched_user_defined_field4_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].user_defined_field4_code_set,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].sched_user_defined_field5_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].user_defined_field5_code_set,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].proc_surgeon_specialty_ref,16))),
   v_bar,
   CALL print(trim(replace(edw_surgical_case_proc->qual[d.seq].proc_txt,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(replace(edw_surgical_case_proc->qual[d.seq].sched_modifier_txt,str_find,
     str_replace,3))), v_bar,
   CALL print(trim(replace(edw_surgical_case_proc->qual[d.seq].modifier_txt,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].codified_modifier_txt,3)),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].complete_ind))), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].doc_terminated_reason_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_surgical_case_proc->qual[d.seq].
      doc_terminated_dt_tm,0,cnvtdatetimeutc(edw_surgical_case_proc->qual[d.seq].doc_terminated_dt_tm,
       3)),utc_timezone_index,"MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].doc_terminated_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(edw_surgical_case_proc->qual[d.seq].doc_terminated_dt_tm,
     cnvtint(edw_surgical_case_proc->qual[d.seq].doc_terminated_tm_zn),"HHmmsscc"),"00000000","0",
    "        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].doc_terminated_by_prsnl,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].perioperative_doc_type_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_surgical_case_proc->qual[d.seq].segment_ref,16))), v_bar, "3",
   v_bar, extract_dt_tm_fmt, v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].active_ind,3)), v_bar,
   CALL print(trim(edw_surgical_case_proc->qual[d.seq].concurrent_ind,3)),
   v_bar, row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
 SET script_version = "004 02/01/2007 MG010594"
END GO
