CREATE PROGRAM edw_create_item_loc:dba
 SELECT INTO value(itemloc_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE cur_list_size > 0
  DETAIL
   col 0,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(concat(trim(cnvtstring(edw_item_loc->qual[d.seq].item_sk,16)),"~",trim(cnvtstring(
      edw_item_loc->qual[d.seq].item_loc,16)),"~",trim(cnvtstring(edw_item_loc->qual[d.seq].
      locator_ref,16)),
    "~",trim(cnvtstring(edw_item_loc->qual[d.seq].relationship_type_ref,16)),"~",trim(cnvtstring(
      edw_item_loc->qual[d.seq].package_type_sk,16)))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].item_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].item_loc,16))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].locator_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].package_type_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].relationship_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].average_item_cost,16,4))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].standard_item_cost,16,4))),
   v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].manufacturer_retail_cost,16,4))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].qoh_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].qoh_qty,16,4))),
   v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].acc_stockout_freq_ref,16))), v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].avg_daily_usage)), v_bar,
   CALL print(build(edw_item_loc->qual[d.seq].avg_weeks_order_qty)),
   v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].fixed_order_qty,16,4))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,edw_item_loc->qual[d.seq].last_syscalc_dt_tm,
      0,cnvtdatetimeutc(edw_item_loc->qual[d.seq].last_syscalc_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].last_syscalc_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(edw_item_loc->qual[d.seq].last_syscalc_dt_tm,cnvtint(
      edw_item_loc->qual[d.seq].last_syscalc_tm_zn),"MMddyyyyHHmmsscc"),"0000000000000000","0",
    "                ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].locator_qty,16,4))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].locator_type_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].lock_ind,16))), v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].maximum_lvl)), v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].max_days_adu)),
   v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].minimum_lvl)), v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].min_days_adu)), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].reorder_method_ref,16))),
   v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].reorder_point)), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].reorder_type_ref,16))), v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].safety_stock_qty)),
   v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].seasonal_item_ind)), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].syscalc_abc_class_ind,16))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].syscalc_freq_nbr_days,16,4))),
   v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].syscalc_par_lvl_ind)), v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].syscalc_reorder_point_ind)), v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].syscalc_safety_stock_ind)),
   v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].abc_class_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].charge_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].cost_center_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].countback_flg,16))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].count_cycle_ref,16))), v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].first_dose_flg)),
   v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].instance_ind)), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].list_role_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].lot_tracking_lvl_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].override_clsfctn_ref,16))), v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].sch_qty)), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].sch_role_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].stock_package_type_sk,16))), v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].stock_type_ind)), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].sub_account_ref,16))),
   v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].average_lead_time)), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].average_lead_time_uom_ref,16))), v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].consignment_ind)),
   v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].economic_order_qty)), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].fill_loc,16))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].primary_vendor_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].primary_vendor_item_sk,16))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].product_origin_ref,16))), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].reorder_package_type_sk,16))),
   v_bar,
   CALL print(trim(edw_item_loc->qual[d.seq].syscalc_eoq_ind)), v_bar,
   CALL print(trim(cnvtstring(edw_item_loc->qual[d.seq].vendor_site_sk,16))), v_bar, "3",
   v_bar, extract_dt_tm_fmt, v_bar,
   row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
END GO
