CREATE PROGRAM edw_create_pha_disp_hist_files:dba
 SELECT INTO value(pha_disp_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE cur_list_size > 0
  DETAIL
   pha_disp_file_cnt = (pha_disp_file_cnt+ 1), col 0,
   CALL print(trim(health_system_id)),
   v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].pharm_order_sk,16))), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].pharm_dsp_hist_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].action_seq))), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].authorization_nbr)), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].bill_qty)),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,pha_disp->qual[d.seq].charge_dt_tm,0,
      cnvtdatetimeutc(pha_disp->qual[d.seq].charge_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(pha_disp->qual[d.seq].charge_ind)), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].charge_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(pha_disp->qual[d.seq].charge_dt_tm,cnvtint(pha_disp->qual[d
      .seq].charge_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].copay_amt)), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].credit_pharm_dispense_hist_sk,16))),
   v_bar,
   CALL print(trim(pha_disp->qual[d.seq].discount_amt)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,pha_disp->qual[d.seq].dispense_dt_tm,0,
      cnvtdatetimeutc(pha_disp->qual[d.seq].dispense_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm")
    )), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].dispense_fee_amt)),
   v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].dispense_prsnl,16))), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].dispense_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(pha_disp->qual[d.seq].dispense_dt_tm,cnvtint(pha_disp->
      qual[d.seq].dispense_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].dispense_event_type_ref,16))), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].dispense_loc,16))), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].dispense_priority_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,pha_disp->qual[d.seq].dispense_priority_dt_tm,
      0,cnvtdatetimeutc(pha_disp->qual[d.seq].dispense_priority_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].dispense_priority_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(pha_disp->qual[d.seq].dispense_priority_dt_tm,cnvtint(
      pha_disp->qual[d.seq].dispense_priority_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(pha_disp->qual[d.seq].dispense_qty)), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].dispense_qty_unit_ref,16))), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].dispense_svc_res_dept_hier_sk,16))),
   v_bar,
   CALL print(trim(pha_disp->qual[d.seq].dispense_doses)), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].early_refill_reason_ref,16))), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].event_sk,16))),
   v_bar,
   CALL print(trim(pha_disp->qual[d.seq].dispense_event_total_price_amt)), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].refill_extra_reason_ref,16))), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].fill_list_hist_sk,16))),
   v_bar,
   CALL print(trim(pha_disp->qual[d.seq].fill_list_nbr)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,pha_disp->qual[d.seq].first_dose_dt_tm,0,
      cnvtdatetimeutc(pha_disp->qual[d.seq].first_dose_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].first_dose_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(pha_disp->qual[d.seq].first_dose_dt_tm,cnvtint(pha_disp->
      qual[d.seq].first_dose_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].first_iv_seq)), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].future_charge_ind)),
   v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].dispense_hlthpln,16))), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].incentive_amt)), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].late_refill_reason_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,pha_disp->qual[d.seq].next_dispense_dt_tm,0,
      cnvtdatetimeutc(pha_disp->qual[d.seq].next_dispense_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].next_dispense_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(pha_disp->qual[d.seq].next_dispense_dt_tm,cnvtint(pha_disp
      ->qual[d.seq].next_dispense_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")),
   v_bar,
   CALL print(trim(pha_disp->qual[d.seq].orig_action_seq)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,pha_disp->qual[d.seq].orig_action_dt_tm,0,
      cnvtdatetimeutc(pha_disp->qual[d.seq].orig_action_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].orig_action_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(pha_disp->qual[d.seq].orig_action_dt_tm,cnvtint(pha_disp->
      qual[d.seq].orig_action_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].orig_action_com_type_ref)), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].orig_action_prsnl)),
   v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].partial_refill_reason_ref,16))), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].pharm_type_ref,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,pha_disp->qual[d.seq].prev_dispense_dt_tm,0,
      cnvtdatetimeutc(pha_disp->qual[d.seq].prev_dispense_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].prev_dispense_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(pha_disp->qual[d.seq].prev_dispense_dt_tm,cnvtint(pha_disp
      ->qual[d.seq].prev_dispense_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].remaining_qty)),
   v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].reason_ref,16))), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].remaining_refill_qty)), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].reimbursement_amt)),
   v_bar,
   CALL print(trim(pha_disp->qual[d.seq].residual_doses_qty)), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].residual_price_amt)), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].dispense_reverse_ind)),
   v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].dispense_event_prsnl,16))), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].sale_tax_amt)), v_bar,
   CALL print(trim(pha_disp->qual[d.seq].track_nbr)),
   v_bar,
   CALL print(trim(pha_disp->qual[d.seq].usual_customary_price_amt)), v_bar,
   CALL print(trim(cnvtstring(pha_disp->qual[d.seq].witness_prsnl,16))), v_bar, "3",
   v_bar, extract_dt_tm_fmt, v_bar,
   "1", v_bar, row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
 SET script_version = "002 09/07/07 YC3429"
END GO
