CREATE PROGRAM edw_create_enc_accident:dba
 SELECT INTO value(enc_acc_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  DETAIL
   col 0,
   CALL print(trim(health_system_id)), v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(enc_accident->qual[d.seq].encounter_nk)),
   v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].encounter_sk,16))), v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].encntr_accident_id,16))), v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].acc_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_accident->qual[d.seq].acc_dt_tm,0,
      cnvtdatetimeutc(enc_accident->qual[d.seq].acc_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm"))
   ), v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].acc_tm_zn,16))), v_bar,
   CALL print(enc_accident->qual[d.seq].acc_tm_vld_flg),
   v_bar,
   CALL print(trim(replace(enc_accident->qual[d.seq].acc_loctn_text,str_find,str_replace,3))), v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].acc_death_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].acc_emp_org,16))),
   v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].acc_job_reltn_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].acc_state_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].ambul_arrive_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].ambul_geog_ref,16))), v_bar,
   CALL print(trim(replace(enc_accident->qual[d.seq].ambul_serv_nbr,str_find,str_replace,3))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_accident->qual[d.seq].appl_dt_tm,0,
      cnvtdatetimeutc(enc_accident->qual[d.seq].appl_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm")
    )),
   v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].appl_tm_zn,16))), v_bar,
   CALL print(enc_accident->qual[d.seq].appl_tm_vld_flg), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_accident->qual[d.seq].attd_dt_tm,0,
      cnvtdatetimeutc(enc_accident->qual[d.seq].attd_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm")
    )),
   v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].attd_tm_zn,16))), v_bar,
   CALL print(enc_accident->qual[d.seq].attd_tm_vld_flg), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_accident->qual[d.seq].init_asse_dt_tm,0,
      cnvtdatetimeutc(enc_accident->qual[d.seq].init_asse_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].init_asse_tm_zn,16))), v_bar,
   CALL print(enc_accident->qual[d.seq].init_asse_tm_vld_flg), v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].place_ref,16))),
   v_bar,
   CALL print(trim(replace(enc_accident->qual[d.seq].police_badge_nbr,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].police_force_ref,16))), v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].police_invo_ref,16))),
   v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,enc_accident->qual[d.seq].treat_start_dt_tm,0,
      cnvtdatetimeutc(enc_accident->qual[d.seq].treat_start_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(enc_accident->qual[d.seq].treat_start_tm_zn,16))), v_bar,
   CALL print(enc_accident->qual[d.seq].treat_start_tm_vld_flg),
   v_bar, "3", v_bar,
   CALL print(enc_accident->qual[d.seq].ea_active_ind), v_bar, extract_dt_tm_fmt,
   v_bar,
   CALL print(trim(replace(enc_accident->qual[d.seq].accident_text,str_find,str_replace,3))), v_bar,
   row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
 SET script_version = "003 09/01/11 CG022883"
END GO
