CREATE PROGRAM edw_create_sch_appointment:dba
 SELECT INTO value(sch_appt_extractfile)
  FROM (dummyt d  WITH seq = value(cur_list_size))
  WHERE cur_list_size > 0
  DETAIL
   col 0,
   CALL print(trim(health_system_id)), v_bar,
   CALL print(trim(health_system_source_id)), v_bar,
   CALL print(trim(sch_appt->qual[d.seq].encounter_nk)),
   v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].encounter_sk,16))), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].person_sk,16))), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].sch_appointment_sk,16))),
   v_bar,
   CALL print(trim(replace(sch_appt->qual[d.seq].requested_reason_txt,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].appt_type_synonym_ref,16))), v_bar,
   CALL print(trim(replace(sch_appt->qual[d.seq].appt_type_synonym_txt,str_find,str_replace,3))),
   v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].appt_type_dtl_sk,16))), v_bar,
   CALL print(trim(replace(sch_appt->qual[d.seq].group_desc,str_find,str_replace,3))), v_bar,
   CALL print(trim(sch_appt->qual[d.seq].group_type_flg)),
   v_bar,
   CALL print(trim(sch_appt->qual[d.seq].group_capacity_qty)), v_bar,
   CALL print(trim(sch_appt->qual[d.seq].group_closed_ind)), v_bar,
   CALL print(trim(sch_appt->qual[d.seq].group_sched_person_qty)),
   v_bar,
   CALL print(trim(sch_appt->qual[d.seq].group_shared_ind)), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,sch_appt->qual[d.seq].
      first_group_ses_beg_dt_tm,0,cnvtdatetimeutc(sch_appt->qual[d.seq].first_group_ses_beg_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].first_group_ses_beg_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(sch_appt->qual[d.seq].first_group_ses_beg_dt_tm,cnvtint(
      sch_appt->qual[d.seq].first_group_ses_beg_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,sch_appt->qual[d.seq].
      last_group_ses_end_dt_tm,0,cnvtdatetimeutc(sch_appt->qual[d.seq].last_group_ses_end_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].last_group_ses_end_tm_zn))),
   v_bar,
   CALL print(evaluate(datetimezoneformat(sch_appt->qual[d.seq].last_group_ses_end_dt_tm,cnvtint(
      sch_appt->qual[d.seq].last_group_ses_end_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].offset_sch_appointment_sk,16))), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].offset_from_type_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].offset_type_ref,16))), v_bar,
   CALL print(trim(sch_appt->qual[d.seq].offset_beg_appt_qty)), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].offset_beg_appt_units_ref,16))),
   v_bar,
   CALL print(trim(sch_appt->qual[d.seq].offset_end_appt_qty)), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].offset_end_appt_units_ref,16))), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].protocol_sch_appointment_sk,16))),
   v_bar,
   CALL print(trim(sch_appt->qual[d.seq].protocol_seq)), v_bar,
   CALL print(trim(sch_appt->qual[d.seq].protocol_type_flg)), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].recur_sch_appointment_sk,16))),
   v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].recur_seq))), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].recur_type_flg))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,sch_appt->qual[d.seq].referred_dt_tm,0,
      cnvtdatetimeutc(sch_appt->qual[d.seq].referred_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm")
    )),
   v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].referred_tm_zn))), v_bar,
   CALL print(evaluate(datetimezoneformat(sch_appt->qual[d.seq].referred_dt_tm,cnvtint(sch_appt->
      qual[d.seq].referred_tm_zn),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].sch_appointment_state_ref,16))),
   v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].scheduled_loc,16))), v_bar,
   CALL print(trim(replace(sch_appt->qual[d.seq].scheduled_loc_txt,str_find,str_replace,3))), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].scheduled_location_type_ref,16))),
   v_bar, "3", v_bar,
   extract_dt_tm_fmt, v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].active_ind))),
   v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].nhs_providing_org,16))), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].schedule_seq,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,sch_appt->qual[d.seq].
      first_chart_access_dt_tm,0,cnvtdatetimeutc(sch_appt->qual[d.seq].first_chart_access_dt_tm,3)),
     utc_timezone_index,"MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].first_chart_access_tz))), v_bar,
   CALL print(evaluate(datetimezoneformat(sch_appt->qual[d.seq].first_chart_access_dt_tm,cnvtint(
      sch_appt->qual[d.seq].first_chart_access_tz),"HHmmsscc"),"00000000","0","        ","0",
    "1")), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].scheduled_loc_org,16))),
   v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].patient_appt_ind))), v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].sch_appt_sk,16))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,sch_appt->qual[d.seq].active_stat_dt_tm,0,
      cnvtdatetimeutc(sch_appt->qual[d.seq].active_stat_dt_tm,3)),utc_timezone_index,
     "MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].active_stat_tm_zn))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,sch_appt->qual[d.seq].active_stat_dt_tm,0,
      cnvtdatetimeutc(sch_appt->qual[d.seq].active_stat_dt_tm,2)),sch_appt->qual[d.seq].
     active_stat_tm_zn,"MM/DD/YYYY HH:mm"))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,sch_appt->qual[d.seq].beg_dt_tm,0,
      cnvtdatetimeutc(sch_appt->qual[d.seq].beg_dt_tm,3)),utc_timezone_index,"MM/DD/YYYY HH:mm"))),
   v_bar,
   CALL print(trim(cnvtstring(sch_appt->qual[d.seq].beg_tm_zn))), v_bar,
   CALL print(trim(datetimezoneformat(evaluate(curutc,1,sch_appt->qual[d.seq].beg_dt_tm,0,
      cnvtdatetimeutc(sch_appt->qual[d.seq].beg_dt_tm,2)),sch_appt->qual[d.seq].beg_tm_zn,
     "MM/DD/YYYY HH:mm"))), v_bar, row + 1
  WITH noheading, nocounter, format = lfstream,
   maxcol = 1999, maxrow = 1, append
 ;end select
 SET script_version = "009 12/05/14 SB026554"
END GO
